### ISSUE TITLE
Leaf with default value and defined as unique, then query failed.

### ISSUE THREAD

**Issue by longjianglzt** [CESNET/libyang#1010]
yang module like this:
```yang
list test {
	key "testIndex";
	unique "testUint16";
	leaf testIndex {
	  type uint32 {
		range "0..4294967295";
	  }
	}
	leaf testUint16 {
	  type uint16 {
		range "1..32";
	  }
	  default "3";
	}
}
```
If list test has 2 instances, then below request will return error from libyang, because libyang check the default values are the same for both instances with unique leaf：
```xml
<filter type="subtree">
  <testmodel xmlns="urn:Huawei:yang:test-model">
     <test>
         <testIndex>1</testIndex>
      </test>
      <test>
         <testIndex>2</testIndex>
       </test>
  </testmodel>
</filter>
```
Wether do not check default value for unique leaf when query request?

**Comment by longjianglzt** [comment]
Supplementing query RPC:
###
<get-config xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
  <source>
    <running/>
  </source>
  <filter type="subtree">
    <testmodel xmlns="urn:Huawei:yang:test-model">
        <test>
          <testIndex>1</testIndex>
        </test>
        <test>
          <testIndex>2</testIndex>
        </test>
    </testmodel>
  </filter>
</get-config>
####

**Comment by longjianglzt** [comment]
<filter type="subtree">
    <testmodel xmlns="urn:Huawei:yang:test-model">
        <test>
          <testIndex>1</testIndex>
        </test>
        <test>
          <testIndex>2</testIndex>
        </test>
    </testmodel>
  </filter>

**Comment by longjianglzt** [comment]
query PRC can not be shown in comment......

**Comment by michalvasko** [comment]
Hi,
this is an interesting problem. You have not mentioned what exactly your use-case is, whether you have your own NETCONF server that is parsing this subtree filter and is throwing an error, because that is possible. In our server we use only XML parser from *libyang* for parsing this filter and then we transform it into an XPath filter. The only way of parsing this would be to use `LYD_OPT_TRUSTED` flag, which would still create the default values but do not validate them. However, there are many other cases where even this would not work such as defining one leaf with several values (acceptable for filter). I am afraid there is no way of parsing that into *libyang*.

Note that we are working on new *libyang* without a separate XML parser meaning we will have to solve it somehow. The solution would probably be to define a special flag that would allow parsing such an XML into data tree without errors. But that is still far away.

Regards,
Michal
