### ISSUE TITLE
Creating a `libyang::Context` from `ly_ctx*` I get from libnetconf2

### ISSUE THREAD

**Issue by syyyr** [CESNET/libyang#1017]
Hi,

I'm trying to create a `libyang::Context` instance from `ly_ctx*` I get from libnetconf2 through the `nc_session_get_ctx` function. libnetconf2 fills the context with all the schemas and I want to reuse that for my program (right now I create my own context and also fill it with all the schemas, so the schemas are retrieved twice). There is `libyang::Context` constructor, which consumes `ly_ctx*`, but is marked internal use only. Is there another way to reuse the libyang context I get from libnetconf?

**Comment by jktjkt** [comment]
I think that our use case (i.e., using C++ bindings of libyang from within C++ bindings of libnetconf2 that we're working on) counts as a good use case even for calling to internal functions.

**Comment by michalvasko** [comment]
@syyyr You should not be discouraged that easily :) Seriously though, nothing can prevent you from using that function and is part of the API. The comments are, I guess, slightly misleading and what is meant by `internal use only` is that you should use the function only if you really know what you are doing. These functions are actually in the API mostly because of various uses in other bindings of our projects, which is yours exactly. You should just not need to use those functions when you operate only with libyang C++ bindings and create all the objects with them.

Regards,
Michal

**Comment by syyyr** [comment]
Thank you for the answer.
