### ISSUE TITLE
lys_xpath_atomize aboslute path fails for cur_snode different from first children

### ISSUE THREAD

**Issue by lukasmacko** [CESNET/libyang#102]
lys_xpath_atomize returns NULL if context is different from first children.  
```C
#include <stdio.h>
#include <stdlib.h>
#include <libyang/libyang.h>

void atomize_test(const struct lys_node *start, const char *xpath)
{
   struct ly_set *atoms = NULL;
   if (!(atoms = lys_xpath_atomize(start, xpath, 0))) {
      puts("error");
   } else {
      for (int i=0; i < atoms->number; i++){
          puts(atoms->set.s[i]->name);
      }
      ly_set_free(atoms);
   }
}

int main(int argc, char **argv)
{
   struct ly_ctx *ctx = ly_ctx_new(".");
   const struct lys_module *module = ly_ctx_load_module(ctx, "state-module", NULL);
   char *xpath = "/state-module:bus/distance_travelled";

   atomize_test(module->data, xpath); /*ok*/
   puts("=====================");
   atomize_test(module->data->next, xpath);  /*ERROR*/
   ly_ctx_destroy(ctx, NULL);
   return 0;
}
```
[state-module.yang](https://github.com/sysrepo/sysrepo/blob/devel/tests/yang/state-module%402016-07-01.yang)

**Comment by michalvasko** [comment]
Hi,
this is actually correct (the behavior is intentional at least). The accessible tree in the first example is different from the tree in the second example. In the first, the context node is a state one, so both the configuration and state data are accessible. In the other case, the context node represents configuration, so state data are inaccessible as per [YANG 1.1 RFC](https://tools.ietf.org/html/draft-ietf-netmod-rfc6020bis-14#section-6.4.1) (no difference in YANG 1.0).

Regards,
Michal
