### ISSUE TITLE
date-and-time before the Epoch (1970-01-01) does not pass the validation

### ISSUE THREAD

**Issue by maniowy** [CESNET/libyang#1021]
Validating data containing `1969-12-31T23:59:59Z` value of `ietf-yang-types:date-and-time` type results with `lyd_parse_mem` failure:

`Checking date-and-time value "1969-12-31T23:59:59Z" failed (Transport endpoint is not connected).`

`1969-12-31T23:59:59Z` is a valid `date-and-time` value according to [RFC 6991](https://tools.ietf.org/html/rfc6991#page-11) and [RFC 3339](https://tools.ietf.org/html/rfc3339#section-5.6).

The validation fails because of `mktime` function call in `src/user_types/user_yang_types.c:139` (`master` revision `1b7d73d4`).

**Comment by fredgan** [comment]
Exactly, this date-and-time value is valid.
I tried to reproduce your issue with `yanglint`, but failed.

Will you mind show more information about how you encounted this error?

**Comment by michalvasko** [comment]
Hi,
this was quite an interesting problem. Actually, `mktime()` is able to process date before the epoch, it simply returns negative number of seconds in that case. So, the only problematic use-case was exactly 1 second before the epoch, because return value was tested for `-1`. Fixed simply by checking `errno` instead.

Also, I have not managed to reproduce it at first because of DST, the problematic date for me was `1970-01-01T00:59:59Z`. But now both are included in the tests.

Regards,
Michal

**Comment by fredgan** [comment]
@michalvasko Wow, It's really as what you said. I tried my problematic  date is `1970-01-01T07:59:59Z`

**Comment by maniowy** [comment]
Hi,

thank you for quick and thorough investigation and an immediate fix, I am impressed. You are absolutely right, it happened that my dataset contained the only problematic date (with regard to DST settings) and I have incorrectly made an generic interpretation expanding it for all pre-epoch dates, thus I am removing the invalid mktime statement from the first post.

Regards
Mateusz
