### ISSUE TITLE
ly_register_types() isn't working anymore

### ISSUE THREAD

**Issue by rwestphal** [CESNET/libyang#1047]
Commit df6ec7bd1189651e3f202e70f43aaea830ebe851 introduced a regression that caused the `ly_register_types()` function to not work anymore. This function doesn't return any error, but the provided user type callbacks are not called when expected. Additionally, the `ly_get_loaded_plugins()` API function doesn't return the loaded user types. I can provide a test program later if necessary (maybe an unit test).

I'm using libyang from the `devel` branch.

Thanks in advance!

**Comment by michalvasko** [comment]
Hi Renato,
this will be more difficult to reproduce than what you described. My guess is that you are registering types for `ietf-inet-types` (but it does not matter, will be used as example) but you also have this module in a different revision somewhere in your schema search directories. This change simply caused that even when an internal module is being loaded, it is searched for because there may be a newer revision available, in which case it must be used. Can you please check this?

Regards,
Michal

**Comment by rwestphal** [comment]
> this will be more difficult to reproduce than what you described. My guess is that you are registering types for `ietf-inet-types` (but it does not matter, will be used as example) but you also have this module in a different revision somewhere in your schema search directories.

Bingo :) That's exactly what was happening here. I was implementing _ietf-inet-types@2013-07-15_ but I had _ietf-inet-types@2019-07-21_ in my libyang search directory. Removing that module fixed the problem.

> This change simply caused that even when an internal module is being loaded, it is searched for because there may be a newer revision available, in which case it must be used. Can you please check this?

That makes sense to me. I'll probably start using `LY_CTX_DISABLE_SEARCHDIRS` in FRR and embed all necessary modules in the binaries to avoid problems of this nature in the future.

Thank you again Michal! I'll close this issue now.

**Comment by michalvasko** [comment]
Hi Renato,
you can also do what *libyang* advises you to do and that is to register your user-types for both revisions. It does not cost you anything and if either of the modules will be used, it will work as expected. You can even register your types without a revision, which may make sense in this case. But generally it may not be a good idea because you are essentially handling unknown types (you can never be certain how a particular type changes in future revisions). The choice is up to you.

Regards,
Michal

**Comment by rwestphal** [comment]
@michalvasko that's very useful information to know, thanks!
