### ISSUE TITLE
Printing anyxml data in XML keeps characters supposed to be escaped

### ISSUE THREAD

**Issue by rkrejci** [CESNET/libyang#106]
It is unclear when the anyxml node contains XML data or a pure string. In some cases even a text can containe characters such as `<` which are supposed to be escaped.

As reported in CESNET/Netopeer2#18, this currently happens when NETCONF server replies to a `get-schema` request with a YANG schema content.

**Comment by rkrejci** [comment]
Since the issue is quite complex, we have decided to solve it in the devel branch (0.10.x) and connect fixing this issue with adding support for `anydata` introduced in YANG 1.1

**Comment by rkrejci** [comment]
The issue is solved by a set of commits available in version 0.10.56

**Comment by dmcpriv** [comment]
I suppose I have the opposite problem.  All XML strings I used to encode as Raw XML in a leaf are now being escaped.  Is there a way to specify a string that should not be escaped at all?

**Comment by rkrejci** [comment]
Currently you can create XML tree (e.g. using lyxml_parse_mem()) and create anyxml/anydata (lyd_new_anydata) with LYD_ANYDATA_XML. The problem with not escaping XML tags is that XML is not the only format supported by libyang. In case of JSON, the '<' or '&' are not being escaped. Therefore, internaly the string is not stored with the escaped characters, they are escaped when the anydata/anyxml node is being printed as XML and the type of its content is LYD_ANYDATA_(CONST)STRING.

I understand, that storing XML data only as XML tree can be limiting, so what about adding new anydata type LYD_ANYDATA_XMLSTRING? As LYD_ANYDATA_JSON, it would be actually string, but with aditional information from a caller that the content is XML and it is not supposed to be escaped when printed as XML?

**Comment by davemiedema** [comment]
Thanks.  Understand a bit more about the JSON/XML dilemma now.  So if "anyxml" is really "any unvalidated hierarchy that can be serialized to JSON or XML (or anything else)",  shouldn't that be when you create a tree via lyxml_parse_mem?  Then you can serialize it to the desired output and not worry about doing escapes.  If you treat it as such, would a JSON user expect to see it as escaped XML or JSON?  If XML, then you would need to be able to escape it as you suggest.

A new anydata of "RAWSTRING" or something to indicate it should not be escaped would be a good approach I think.  In my fork I currently have changed all the print calls for ANYDATA to use ly_print rather than dump, but selecting this behavior based on a new type would be a good addition in my opinion

**Comment by dmcpriv** [comment]
Thanks. Understand a bit more about the JSON/XML dilemma now. So if "anyxml" is really "any unvalidated hierarchy that can be serialized to JSON or XML (or anything else)", shouldn't that be when you create a tree via lyxml_parse_mem? Then you can serialize it to the desired output and not worry about doing escapes. If you treat it as such, would a JSON user expect to see it as escaped XML or JSON? If XML, then you would need to be able to escape it as you suggest.

A new anydata of "RAWSTRING" or something to indicate it should not be escaped would be a good approach I think. In my fork I currently have changed all the print calls for ANYDATA to use ly_print rather than dump, but selecting this behavior based on a new type would be a good addition in my opinion

**Comment by rkrejci** [comment]
Actually the definition you are using is from YANG 1.0. But the original intention of YANG authors was actually "an unknown set of nodes that can be modeled with YANG", which is more limiting. Therefore, there is `anydata` in YANG 1.1. libyang represents both with the same data structure.

When the data is read by libyang in XML format, the anyxml content is stored as XML tree. But the content can be also created programmaticaly and then it can be more effective to store it in some other format. Similarly, data can be read as JSON and because libyang does not use any internal JSON tree representation, it has to be kept in string, because it does not have model for the data (yet).

Printing XML data tree into JSON is another challenging task, because JSON formatting depends on the element's YANG definition - e.g. leaf and leaf-lists are encoded in a different way. So you cannot simply print XML tree anyxml content in JSON (libyang will print warning, but the data are skipped).

From the anydata definition, common usage of anydata/anyxml in libyang is the following:
1. in input phase,  the content is taken in some format which is not connected with YANG schema, but that can be used later to build regular data (`lyd_node`) tree - this is the case of strings (including JSON) and XML tree
2. before the data tree is used on output (printed somewhere), the best approach is to get know (somehow) the YANG schema for the anydata content and transform the string or XML tree into data tree (`LYD_ANYDATA_DATATREE`).

I'm going to add a new `LYD_ANYDATA_something` to indicate that it is serialized XML.

**Comment by dmcpriv** [comment]
Thanks for the explanation.  Agree that it is challenging and that the ANYDATA_something is a good stopgap.

Thanks for all your efforts!

**Comment by rkrejci** [comment]
There is new `LYD_ANYDATA_SXML` (and `LYD_ANYDATA_SXMLD`) you can use now, please check that it works as expected.
