### ISSUE TITLE
Why isn't the ly_errno_glob's type uint32_t or int32 ?

### ISSUE THREAD

**Issue by foxge** [CESNET/libyang#1073]
https://github.com/CESNET/libyang/blob/1b7d73d442dc58e1feec6d518372e0aaccebca37/src/common.c#L34

**Comment by michalvasko** [comment]
Hi,
do you have a specific problem with it? I suppose it was defined that way because it does not need to hold larger values. But I guess it could cause some problems, in theory, as an enum value is being written/read from this variable.

Regards,
Michal

**Comment by foxge** [comment]
Because I try to define a new thread variable, and observed it.

**Comment by fredgan** [comment]
Hi Michal,
I agree with foxge, because in the API `ly_errno_glob_address`, this variable will be cast into an enum pointer (`LY_ERR *`), which points to a 4 bytes data. If we dereference pointer returned by `ly_errno_glob_address`, we may get an wrong value(other 3 bytes are random). 

But in fact, when the variable `ly_errno_glob` is as global variable, it won't cause any problem. (Maybe compiler init all the global variable area to 0 before storing the global variable, I don't know)

https://github.com/CESNET/libyang/blob/773653e17440ef8d00fd1dbf9a06560b73f4361d/src/common.c#L35-L42

**Comment by michalvasko** [comment]
HI,
okay, it was changed (in f7258d6a80ccc408cddfd6ad2b956fb656350bb1, forgot to reference it).

Regards,
Michal

**Comment by foxge** [comment]
okay.
