### ISSUE TITLE
Question regarding lyd_dup_to_ctx()

### ISSUE THREAD

**Issue by gitter-runner** [CESNET/libyang#1089]
Hi!

When trying to implement the edit-data operation using _sr_edit_batch()_, I ran into the issue that the config parameter of the function must be of the same context as the _sysrepo_.

The problem is, I use 2 different contexts for the _sysrepo_ and the server (to separate certain capabilites and other functionalities), so when the server passes the config to
_sr_edit_batch()_ I get the "Data trees must be created using the session connection libyang context." error.

To solve this, I thought about using _lyd_dup_to_ctx()_ on the config to duplicate it into the _sysrepo's_ context, but to get the _sysrepo_ context _sr_get_context()_ returns the context as a const and (for some reason) _lyd_dup_to_ctx()_ modifies the context, so this doesn't work.

My question is, is there any other way to solve this and move _lyd_node_ structures between contexts? Wouldn't _lyd_dup_to_ctx()_ work with _const ly_ctx*_?

Versions:
libyang version: 1.0.130
sysrepo version: 1.4.41

Thanks!

**Comment by michalvasko** [comment]
Hi,
yes, you can use `lyd_dup_to_ctx()` even with `const` context. Only its dictionary is modified, which is harmless even though *libyang* does not reflect this in its function prototypes.

However, note that *libyang* version 2 does not have this function or any other that work with several contexts because it was present mostly cause of the legacy *sysrepo* that needed it. But it is discouraged. Strictly speaking, it will always be possible by printing the data and parsing them again but very efficient.

Regards,
Michal

**Comment by gitter-runner** [comment]
Thanks for the answer!
