### ISSUE TITLE
If node value has some sensitive information，just use "free" function may lead information leakage

### ISSUE THREAD

**Issue by dongwenshuai666** [CESNET/libyang#1111]
https://github.com/CESNET/libyang/blob/bf5e182a9f2741d714c08048ac60909affbbb94f/src/hash_table.c#L214

**Comment by michalvasko** [comment]
Hi,
okay, I suppose it may be a problem although it seems to be a bit far-fetched. So a solution where a compile-time option would decide whether you want the memory properly cleaned seems fine to us, but it all depends on any performance cost this feature may have. So, we would consider it if you could provide such measurements (using `explicit_bzero()` after the `free()` and test freeing data). Otherwise it is difficult to design a proper solution.

Regards,
Michal
