### ISSUE TITLE
YANG extension support

### ISSUE THREAD

**Issue by bushsf** [CESNET/libyang#1128]
I’m using yanglint to convert XML to JSON with YANG modules that use extension statements.
The YANG modules using extension statements validate successfully with pyang.

However, leaves created with the extensions do not appear in the pyang tree format. Similarly for yanglint. 
Shouldn’t leaves appear that we created using extension statements?

Thanks,
Steve

**Comment by michalvasko** [comment]
Hi Steve,
extensions are really difficult to handle because of their loose definition. So, even if you define some leaves in an extension, there is no specification saying that these leaves are supposed to be treated as YANG `leaf` statements or not. That is why they do not show up in tree printer.

Regards,
Michal

**Comment by bushsf** [comment]
Michal,

Thank you. I’m trying to validate and convert instance data from XML to JSON whose yang modules use extensions, but the extended leaves seem to be unrecognized.

Do you know if there are any yang tools (e.g. yanglint) that recognize extensions?

Steve

**Comment by michalvasko** [comment]
Hi,
well, there is no tool that can support all the extensions out-of-the-box, that is the problem. Support can only be added for specific extensions and *libyang* (`yanglint`) supports that in the form of plugins. So, you would have to write one.

Regards,
Michal
