### ISSUE TITLE
RPC validation adds incorrect container

### ISSUE THREAD

**Issue by lukasmacko** [CESNET/libyang#114]
There is a container incorrectly added by validation.

```C
int main (int argc, char **argv)
{
   struct ly_ctx *ctx = ly_ctx_new(".");
   ly_ctx_load_module(ctx, "test-module", NULL);
   struct lyd_node *node = lyd_new_path(NULL, ctx,"/test-module:activate-software-image/status", "The image acmefw-2.3 is being installed.", 0, LYD_PATH_OPT_OUTPUT);
   lyd_new_path(node, ctx, "/test-module:activate-software-image/version", "2.3", 0, LYD_PATH_OPT_OUTPUT);

   lyd_validate(&node, LYD_OPT_STRICT | LYD_OPT_RPCREPLY);

   if (node->child->next->next->next) {
      puts(node->child->next->next->next->schema->name);
      /*REDUNDANT CONTAINER init-log*/
   }
   lyd_free(node);

   ly_ctx_destroy(ctx, NULL);
   return 0;
}
```
Libyang: latest devel branch
[test-module.yang](https://github.com/sysrepo/sysrepo/blob/devel/tests/yang/test-module.yang#L230-L276)

**Comment by lukasmacko** [comment]
The problem appears also with config data, validation incorrectly adds a container.

**Comment by rkrejci** [comment]
This is actually correct, because empty containers are supposed to be part of accessible tree - see RFC 7950, sec 6.4.1, the last but one paragraph: 
```
If a node that exists in the accessible tree has a non-presence
container as a child, then the non-presence container also exists in
the accessible tree.
```

Note that the container has the `dflt` flag set, so it is kind of a default node and it is not printed by libyang. On the other hand, it is present in the data tree because of correct evaluation of XPath expressions.
