### ISSUE TITLE
libyang2: incorrect detection of duplicate instance

### ISSUE THREAD

**Issue by rwestphal** [CESNET/libyang#1148]
I'm experimenting a bit with libyang2, mostly to see how well it performs compared to libyang 1.x, but stumbled upon a problem where `lyd_validate()` is incorrectly detecting a duplicate list entry (a prefix-list in a data tree with 50k prefix-lists).

Here's a tarball containing all files required to reproduce the problem: [l2_perf.zip](https://github.com/CESNET/libyang/files/4909554/l2_perf.zip)

And here the error I'm getting with my test program:
```
# ./l2_perf
libyang[0]: Duplicate instance of "prefix-list". (path: /frr-filter:lib/prefix-list[type='ipv4'][name='207'])
l2_perf: lyd_validate(): Duplicate instance of "prefix-list"
```

I'm aware that libyang2 is still under heavy development (I noticed several things are still missing) but I'm reporting this issue anyway in case this problem is new to you.

Thanks in advance!

**Comment by michalvasko** [comment]
Hi Renato,
your use-case actually exposed a major (but quite well-hidden) bug in hashes but now it should work as intended, thanks for the example.

As for the state of *libyang* version 2, the functionality should be finished so you can report anything missing. But yes, for the next few weeks we are still finishing up the code with some major behavior changes still left to implement. However, you can actually start testing the performance, which will save us the trouble.

You may find that certain specific use-cases take even longer time than in the current *libyang* (but it should be negligible) because those should be balanced by much faster connected use-case (for example, a bit slower validation but much faster inserting a node into the validated tree beforehand). What I am trying to say that while, overall, the performance should be significantly better, some specific picked use-cases may not. Nevertheless, if you want to provide the full feedback we need, for the tested use-cases please provide the performance with the current *libyang*, with the new one, example code for the new *libyang*, and optionally even `callgrind` output for the new *libyang* (but I can get that easily with the provided example). Thanks!

Finally, like I said, the performance may easily change in the upcoming 1-2 weeks, hopefully not much more after that.

Regards,
Michal

**Comment by rwestphal** [comment]
> Hi Renato,
> your use-case actually exposed a major (but quite well-hidden) bug in hashes but now it should work as intended, thanks for the example.

Thank you Michal!

> As for the state of _libyang_ version 2, the functionality should be finished so you can report anything missing. But yes, for the next few weeks we are still finishing up the code with some major behavior changes still left to implement. However, you can actually start testing the performance, which will save us the trouble.

Ok. From my brief testing, I noticed the following things missing (and some possible bugs):
* JSON parser;
* A priv pointer for schema nodes and `lys_set_private()`;
* `lyd_validate()` doesn't seem to process "when" statements correctly anymore;
* yanglint is barely usable (most options don't seem to be parsed correctly).

> You may find that certain specific use-cases take even longer time than in the current _libyang_ (but it should be negligible) because those should be balanced by much faster connected use-case (for example, a bit slower validation but much faster inserting a node into the validated tree beforehand). What I am trying to say that while, overall, the performance should be significantly better, some specific picked use-cases may not. Nevertheless, if you want to provide the full feedback we need, for the tested use-cases please provide the performance with the current _libyang_, with the new one, example code for the new _libyang_, and optionally even `callgrind` output for the new _libyang_ (but I can get that easily with the provided example). Thanks!
> 
> Finally, like I said, the performance may easily change in the upcoming 1-2 weeks, hopefully not much more after that.

Thanks for the information.

I got these numbers doing some benchmarks to compare 1.x vs 2.x:
```
# ./l1_perf
validate (s): 0.066725
diff (s): 0.028899
find (s): 0.114205

# ./l2_perf
validate (s): 0.365091
diff (s): 0.041345
find (s): 0.000022
```

In FRR, the three most expensive libyang functions we're using are these: `lyd_validate()`, `lyd_diff()` and `lyd_find_path()` (according to frequency of use). Looking at the benchmark results, I was happily surprised to notice how much faster `lyd_find_xpath()` got compared to the 1.x version (both for absolute and relative paths). I don't know what magic you did there but it worked! `lyd_compare()` is a tad slower compared to the old `lyd_diff()`, but this shouldn't be a problem for us as we can make some changes on our side to compare subtrees instead of full trees in the cases where performance is more critical (i.e. when not using the transactional CLI). My only concern is `lyd_validate()`, which is already a problem for us and got considerably slower on 2.x.

Early next week I should do more performance tests and send you more feedback on libyang2, including details about our use case.

Thanks again!

**Comment by michalvasko** [comment]
Hi Renato,
> Ok. From my brief testing, I noticed the following things missing (and some possible bugs):
    JSON parser;
    A priv pointer for schema nodes and lys_set_private();
    lyd_validate() doesn't seem to process "when" statements correctly anymore;
    yanglint is barely usable (most options don't seem to be parsed correctly).

Right, all of that is true except for the `when` statements, what exactly is the problem there? Another missing item is documentation, which can be the problem here because validation was considerably changed.

> I got these numbers doing some benchmarks to compare 1.x vs 2.x:
 ./l1_perf
validate (s): 0.066725
diff (s): 0.028899
find (s): 0.114205
 ./l2_perf
validate (s): 0.365091
diff (s): 0.041345
find (s): 0.000022

I see. Note that the whole *libyang* 2 code includes only "theoretical" optimizations for now, we have not performed any measurements and actual optimizations based on that, yet. So, it is likely that there are essentially some bugs that are causing the performance to be worse than it should be.

Interesting that you mention `lyd_compare()` (which is completely new) and `lyd_diff()` (which is still present, it was not some days ago yet, but generates completely different diff format). So, whichever you decide to use, we are interested in some benchmarks of those, too. `lyd_diff()` will definitely be slower because it now generates a separate data tree independent from the compared trees but I still would not expect the performance to be that much worse.

Finally, thanks for this input and if you can provide more, we will appreciate it. However, I am not sure when I will actually get to the optimizations, we first need to finish the functionality itself.

Regards,
Michal
