### ISSUE TITLE
YANG parsing error in `must` expression

### ISSUE THREAD

**Issue by kwatsen** [CESNET/libyang#1180]
Synched to the latest "devel" branch:
```
$ yanglint --version
yanglint SO 1.9.5
```

With YANG module "test.yang" as:
```
module test {
  yang-version 1.1;
  namespace "https://example.net/test";
  prefix "t";

  container tenants {
    list tenant {
      key key;
      must "not(preceding-sibling::tenant[admins/admin/name = current()/admins/admin/name])";
      leaf key {
        type string;
      }
      container admins {
        list admin {
          key name;
          leaf name {
            type string;
          }
        }
      }
    }
  }
}
```

The module validates with `pyang` but not so with `yanglint`:
```
$ pyang test.yang 
$ yanglint test.yang 
err : Unexpected character(s) 'p' (preceding-sibli).
err : Module "test" parsing failed.
```

Note that the `preceding-sibling` must expression syntax is from Lada, posted on the YANG Doctors mailing list.

**Comment by michalvasko** [comment]
Hi,
based on the YANG 1.1 RFC ([3rd paragraph](https://tools.ietf.org/html/rfc7950#section-6.4)), *libyang* does not support XPath axes at all, hence the error. We are aware of this use-case because we were notified by Lada himself but it has not been such a critical issue to take precedence over other work.

Note that *libyang* does support XPath function `position()`, which can always be used with the same meaning, just different syntax.

**Comment by kwatsen** [comment]
Correct, but https://tools.ietf.org/html/rfc8407#section-4.6.3 says:

>    The "preceding-sibling" and "following-sibling" axes SHOULD NOT be
>    used; however, they MAY be used if document order is not relevant to
>    the outcome of the expression.

The "must" expression in the OP does not rely on document order, so it seems that it should be supported?

**Comment by michalvasko** [comment]
Okay, but like I said, implementing axes would not be a trivial change. However, it seems we should have some available resources and by the end of this year (latest) it should be implemented. Will let you know in this issue.
