### ISSUE TITLE
ly2: issue with lysc_module_dfs_full()

### ISSUE THREAD

**Issue by rwestphal** [CESNET/libyang#1351]
I've just done a simple test with the new `lysc_module_dfs_full()` function but it doesn't seem to be working properly, at least not with the "ietf-isis" YANG module. The issue is that `lysc_module_dfs_full()` sometimes calls its callback providing an invalid schema node pointer.

Code to reproduce the problem (should crash in the `snprintf()` line while trying to derefence the `snode` pointer):
```c
#include <stdlib.h>
#include <stdio.h>
#include <err.h>

#include <libyang/libyang.h>

#define YANG_SEARCH_PATH "/usr/local/share/yang/"

LY_ERR snode_print_config_flag(struct lysc_node *snode, void *data,
			       ly_bool *dfs_continue)
{
	char buf[BUFSIZ];

	//lysc_path(snode, LYSC_PATH_LOG, buf, sizeof(buf));
	snprintf(buf, sizeof(buf), snode->name);
	printf("%s: %u", buf, snode->flags & LYS_CONFIG_W);

	return LY_SUCCESS;
}

int main(int argc, char **argv)
{
	struct ly_ctx *ly_ctx;
	const struct lys_module *module;

	/* initialization */
	if (ly_ctx_new(YANG_SEARCH_PATH, 0, &ly_ctx) != LY_SUCCESS)
		errx(1, "ly_ctx_new(): %s", ly_errmsg(ly_ctx));

	module = ly_ctx_load_module(ly_ctx, "ietf-isis", NULL, NULL);
	if (module == NULL)
		errx(1, "ly_ctx_load_module: %s", ly_errmsg(ly_ctx));

	if (lysc_module_dfs_full(module, snode_print_config_flag, NULL)
	    != LY_SUCCESS)
		errx(1, "lysc_module_dfs_full(): %s", ly_errmsg(ly_ctx));

	/* cleanup */
	ly_ctx_destroy(ly_ctx, NULL);

	return 0;
}
```

**Comment by rkrejci** [comment]
the callback receives all the nodes in the tree and the problem is they are not `struct lysc_node` in all cases - the input/output structures differ. The common part is always the `nodetype`. I see 2 possible options here:
1. we will live with `lysc_node` here and will improve documentation for the callbacks
2. we will add a new structure with only the `nodetype` member for these cases to be clear that such nodes cannot be used without a proper cast

What do you think? @michalvasko ? I vote for 2, but I'm afraid that we won't be able to identify all the points in API which should be changed this way either. But I believe that changing API this way is backward compatible, so it shouldn't be a problem to do such changes in the future.

**Comment by michalvasko** [comment]
Solution 2 should be fine and all that is probably needed is to change the callback where this function is used internally (if it is even, but I think so). It is true that there probably are some other places, where a function could have this generic structure as a parameter instead of `lysc_node` but it does not really matter.

But note that it would then also be good to change the return values of `lysc_node_children_full()` and `lysc_node_parent_full()`. I do not really like that because it is just going to add a lot of casting.

**Comment by rkrejci** [comment]
Seems that the narrower type is not a good solution and I will try to redesign the structures and make them compatible at the cost of several wasted bytes.

**Comment by rwestphal** [comment]
> Seems that the narrower type is not a good solution and I will try to redesign the structures and make them compatible at the cost of several wasted bytes.

Sounds good to me.

My two cents: for schema trees it makes sense to prioritize API ergonomics over optimizing for low memory footprint, considering that the bulk of memory consumption should be instance data in most cases.

**Comment by rwestphal** [comment]
I've tested the latest version and I confirm the problem was fixed. Thanks!
