### ISSUE TITLE
libyang2 schema parsing issues with multiple augments

### ISSUE THREAD

**Issue by awesomenode** [CESNET/libyang#1370]
Hi!

I ran into the following problem, when augmenting the ietf-microwave-radio-link module.

libyang[0]: Invalid absolute-schema-nodeid value "/mrl:xpic-pairs" - target node not found. (path: /test-aug:{augment='/mrl:xpic-pairs/mrl:xpic-pair'})
ly_parse_error: Invalid absolute-schema-nodeid value "/mrl:xpic-pairs" - target node not found.

It seems to me this problem is a bit similar to the previous one ([link](https://github.com/CESNET/libyang/issues/1355)), I'll link the relevant YANG files I used for the context, and the source of the parser software.

libyang2 version: 5a443cff642642b478aab74e828ab5940e64340f
[ly2_parse_aug.tar.gz](https://github.com/CESNET/libyang/files/5855048/ly2_parse_aug.tar.gz)

Thanks!

**Comment by michalvasko** [comment]
The problem is that you are enabling the features on-by-one, that is not how `lys_set_implemented()` works and I tried to clarify it in its description. You must enable all the features at once because in *libyang* version 2 it is no longer just a simple flag change but can lead to the whole context recompiling, you want to avoid that if possible.

**Comment by awesomenode** [comment]
Seems to be working with `lys_parse()` now, thanks!
