### ISSUE TITLE
ly2: wrong namespace in augment

### ISSUE THREAD

**Issue by choppsv1** [CESNET/libyang#1398]
Per https://tools.ietf.org/html/rfc7950#page-28

> If a module augments another module, the XML elements that are added to the encoding are in the namespace of the augmenting module.

Here's a pair of modules to recreate:

main.yang:
```
module main {
  yang-version 1.1;
  namespace "http://example.com/main";
  prefix m;

  import augmented { prefix augmented; }

  augment "/augmented:c/augmented:achoice" {
    case bar {
      when "./eleaf = 'bar'";
      leaf bar-string { type string; }
    }
  }
}
```
augmented.yang:
```
module augmented {
  yang-version 1.1;
  namespace "http://example.com/augmented";
  prefix a;

  container c {
    leaf eleaf { type string; }
    choice achoice {
      case foo {
        when "./eleaf = 'foo'";
        leaf foo-string { type string; }
      }
    }
  }
}
```

Produces:
```
$ yanglint main.yang
libyang warn: Schema node "eleaf" not found ("./eleaf") with context node "/augmented:c".
```

**Comment by choppsv1** [comment]
Another thing of interest that isn't show in the example modules is if the `when` is testing against an enumeration defined in the `augmented` module, the right-hand-side quoted value *cannot* use the `augmented:` prefix, while using the `augmented:` prefix on the left-hand-side of the `when` test in the augment statement does work around the problem.

**Comment by michalvasko** [comment]
I believe the warning is correct although it is definitely not easy to find all the relevant information. What you referenced talks about XML data. This is strictly a YANG parsing issue so it is not valid.

This is the [important section](https://tools.ietf.org/html/rfc7950#section-6.4.1):
> Names without a namespace prefix belong to the same namespace as
      the identifier of the current node.  Inside a grouping, that
      namespace is affected by where the grouping is used (see
      Section 7.13).  Inside a typedef, that namespace is affected by
      where the typedef is referenced.  If a typedef is defined and
      referenced within a grouping, the namespace is affected by where
      the grouping is used (see Section 7.13).

The question then is, what is the current node? Based on some other text I was thinking for a long time it is the context node of the expression, so the warning would indeed be invalid. However, I was then explicitly corrected on the mailing list (please do not ask me to find it) that in these cases the current node simply means the schema node where the expression is defined (except for the constructs that modify the namespace, `grouping` and `typedef`). So that would leave the `case` `bar` node namespace for the `eleaf` in the `when`, which is invalid.

I did not quite understand the other problem, why would you not be able to use the prefix? Enumeration values do not belong to any namespaces, you should never use a prefix for them (not to be confused with identityrefs).

**Comment by choppsv1** [comment]
In fact the RFC has an example that seems to back you up here https://tools.ietf.org/html/rfc7950#section-7.17.3

However, and this may be an RFC issue, the particulars of the choice/case make this more complex https://tools.ietf.org/html/rfc7950#section-6.2.1:

> All cases within a choice share the same case identifier namespace.  This namespace is scoped to the parent choice node.

It's interesting that the RFC is not just saying the parent node here. The text immediately above the `case` text says

> All leafs, leaf-lists, lists, containers, choices, rpcs, actions, notifications, anydatas, and anyxmls defined (directly or through a "uses" statement) within a parent node or at the top level of the module or its submodules share the same identifier namespace.  This namespace is scoped to the parent node or module, unless the parent node is a case node.  In that case, the namespace is scoped to the closest ancestor node that is not a case or choice node.

I think this is saying that 'bar-string' is in namespace main (that would be very clearly the case if we weren't talking about choice/cases). However, since the next bullet item says all case identifiers are in the same namespace it makes me think that `bar` might be in the `augmented` namespace since that's where the original cases are defined. So that would mean the when statement was also in the namespace `augmented`. Unfortunately the example I found in the RFC uses a prefix for both the current module *and* the augmented one in a xpath context. :)

```
      augment "/if:interfaces/if:interface" {
          when 'derived-from-or-self(if:type, "mymod:some-new-iftype")';

          leaf mandatory-leaf {
             mandatory true;
             type string;
          }
       }
```
In this case the "if:" prefix is unneeded I believe sine explicit text says the context of the xpath in a `when` under an augment is the target of that augment.

**Comment by michalvasko** [comment]
It is possible a bit of interpretation is needed here (unfortunately not the only such case) but I believe all this text talks about is how to detect duplicate identifiers, nothing else. So it is not related to `when` and XPath in any way, even though from the text itself this is not apparent. Maybe in the phrase `identifier namespace`, which is not a generic namespace.
