### ISSUE TITLE
ly2: must stmt causes creation of default nodes to fail

### ISSUE THREAD

**Issue by choppsv1** [CESNET/libyang#1425]
A must statement is causing the creation of default nodes to fail. If you comment out the "must" statement in the below yang, the test programs succeeds, otherwise it fails in the final assert (the default nodes are not created).

main.yang:
```
module main {
  yang-version 1.1;
  namespace "http://example.com/main";
  prefix m;

  container c {
    container cc {
      must "./upper > ./lower";
      leaf lower {
        type uint32;
        default "100";
      }
      leaf upper {
        type uint32;
        default "200";
      }
    }
  }
}
```

main.c:
```
#include <assert.h>
#include <stddef.h>
#include <err.h>
#include <libyang/libyang.h>

int main(int argc, char **argv)
{
    struct ly_ctx *ctx = NULL;
    struct lyd_node *node = NULL;
    const struct lys_module *main = NULL;

    ly_log_options(LY_LOLOG | LY_LOSTORE);
    assert(!ly_ctx_new(".", 0, &ctx));
    main = ly_ctx_load_module(ctx, "main", NULL, NULL);
    assert(main);
    assert(!lyd_new_inner(NULL, main, "c", 0, &node));
    assert(!lyd_validate_all(&node, ctx, LYD_VALIDATE_NO_STATE, NULL));
    assert(!lyd_find_path(node, "cc/lower", 0, &node));
}
```

**Comment by michalvasko** [comment]
Right, these are again the implicit presence containers. If you run the example, you get
```
libyang[1]: Container "cc" changed to presence because it has a meaning from its "must" condition.
```
That means the `cc` container is no longer created on its own and must be created explicitly, so the behavior is as expected. The justification is a bit different, I will not repeat everything we discussed before. It was discovered that YANG implementations differ in these use-cases when some would leave no containers created with empty data being valid while some would create both containers and report a validation error (*libyang*). Yes, in this specific case the data would be valid but rarely so in general.

So the solution in *libyang* version 2 we went for is to make containers with `must` presence, then they cannot be created implicitly and no unexpected validation errors occur. Strictly speaking, you cannot expect the `cc` container to be created because it is not specified that way. It is *libyang* implementation-specific feature that all NP containers always exist.

**Comment by choppsv1** [comment]
So what should I do to solve this? FRR using libyang ly1 works and using ly2 is failing. FRR uses lots of musts. If I comment out the must statements it works in ly2 as well. The actual model is not really different (one just has more validation checks).

This seems very counter intuitive that the addition of a validation checks would change the requirement in code for whether one has to create all these nodes all over the place, or not.

FWIW, I missed the converted to presence warning b/c I have had to move all these warnings to debug level instead of warning level in my local ly2 source. I did this b/c it's causing massive failures in the FRR regression tests that look for unexpected output.

**Comment by michalvasko** [comment]
> So what should I do to solve this?

What is the actual use-case? The functionality changed so obviously any previous tests can fail now but the question is whether the tests need to be updated or the functionality fixed.

**Comment by choppsv1** [comment]
> > So what should I do to solve this?
> 
> What is the actual use-case? The functionality changed so obviously any previous tests can fail now but the question is whether the tests need to be updated or the functionality fixed.

Well there are 2 failures. I footnote mentioned the warnings causing regression failures, this just happens in any test that checks for output. This is a minor issue for me b/c changing the log level to debug fixes it.

The failure being discussed here is that e.g., /frr-isis:isis/instance[area-tag="1" vrf="default"] node is created in:

https://github.com/FRRouting/frr/blob/master/yang/frr-isisd.yang

and FRR is expecting all the defaults to be present e.g., in code like this:

	srgb_lbound = yang_dnode_get_uint32(args->dnode, "./lower-bound");
	srgb_ubound = yang_dnode_get_uint32(args->dnode, "./upper-bound");
	srlb_lbound = yang_dnode_get_uint32(args->dnode, "../srlb/lower-bound");
	srlb_ubound = yang_dnode_get_uint32(args->dnode, "../srlb/upper-bound");

All 4 of these leafs are defaults, but the first 2 function calls return results, the second and third abort b/c they expect a value to be there, but the value is not.

**Comment by michalvasko** [comment]
Okay, that was a fair expectation for *libyang* version 1, it is a wrong expectation for *libyang* version 2. Honestly, not sure what else to say.

**Comment by choppsv1** [comment]
> Okay, that was a fair expectation for _libyang_ version 1, it is a wrong expectation for _libyang_ version 2. Honestly, not sure what else to say.

How about how do I make it work? :)

**Comment by choppsv1** [comment]
```
modified   main.yang
@@ -5,12 +5,13 @@ module main {
 
   container c {
     container cc {
-      must "./upper > ./lower";
       leaf lower {
+        must "../upper > .";
         type uint32;
         default "100";
       }
       leaf upper {
+        must ". > ../lower";
         type uint32;
         default "200";
       }
```
Makes things work, but this all feels a bit wrong to me.

**Comment by michalvasko** [comment]
> and FRR is expecting all the defaults to be present

Generally, default values exist only if their parents exist or they are top-level. Specifically, the expectation that a default value exists in an empty data tree is conditional on whether it is top-level or has only NP containers as parents. This is true for both *libyang* 1 and 2.

You are talking about your specific use-case and I am simply not able to help because I do not know all the details.

**Comment by choppsv1** [comment]
> > and FRR is expecting all the defaults to be present
> 
> Generally, default values exist only if their parents exist or they are top-level. Specifically, the expectation that a default value exists in an empty data tree is conditional on whether it is top-level or has only NP containers as parents. This is true for both _libyang_ 1 and 2.
> 
> You are talking about your specific use-case and I am simply not able to help because I do not know all the details.

I suspect this is going to be a problem for more than just FRR. It's not really a specific use case. As you say, if the default is only contained by NP containers the default should exist. Using 2 semantically equivalent "must" validations forms except one form causes different behavior than the other (i.e., in the container node, defaults not present, in the leaf nodes, defaults are present) is not what people are going to expect.

**Comment by michalvasko** [comment]
> As you say, if the default is only contained by NP containers the default should exist.

That is why all those warnings are printed. Also, that is why the presence flags are set on the containers, so you can always check what you need easily in the code.

> Using 2 semantically equivalent "must" validations forms except one form causes different behavior than the other

They are not semantically equivalent then.

> not what people are going to expect

Look at this module.

```yang
module a {
  container cont {
    must "a > 5";
    leaf a {
      type uint32;
    }
  }
}
```
For empty data, *libyang* 1 prints a validation error. *libyang* 2 does not. I dare say the latter behavior is the more expected one. Yes, it has the consequence of changed behavior for nested default values but we still think the current behavior is generally (for all the affected use-cases) the more expected one.

**Comment by choppsv1** [comment]
Well to the module author I think they feel semantically equivalent. In any case I'm going to go replicate all the container "must" into their respective leafs to avoid this particular problem.

I'm worried about the "when"s as there are many more of them.

**Comment by michalvasko** [comment]
The main problem are still the NP containers and their vague behavior. We have tried to make them exact this way, if you have a better solution, let us know.

**Comment by choppsv1** [comment]
Talked this over with a colleague and we came up with perhaps a simple fix. We are thinking that for "auto-presence" containers (ones w/o LYS_SET_PRESENCE flag set) that child defaults should be created.

**Comment by michalvasko** [comment]
What is good about the current solution that it is fairly simple and consistent. Your suggestion would introduce special behavior which I think would cause more harm than good.

**Comment by choppsv1** [comment]
> What is good about the current solution that it is fairly simple and consistent. Your suggestion would introduce a special behavior which I think would cause more harm than good.

How so? It actually matches what one would expect I think, a container that isn't declared presence (only made so to make libyang2 consistent) would have it's default leaves instantiated. This matches the libyang1 behavior and also what I'd expect from a basic YANG knowledge, at the same time it allows for your local change to resolve some of the trickier P/NP issues with YANG.

**Comment by choppsv1** [comment]
BTW, the change I suggest also qualifies as rather simple and consistent I think. :)

**Comment by choppsv1** [comment]
I've submitted a PR that fixes this issue. I think the change is pretty straight-forward. Included unit-test which handles the case above you mention correctly along with a few other "when" conditions.

**Comment by rkrejci** [comment]
Hi, I've tried to review your discussion here as well in #1367. The key point for us, when we decided to change libyang behavior to implicitly convert NP containers with `must` and `when` to the P containers, was the following statement from RFC 7950:
```
non-presence container: A container that has no meaning of its
      own, existing only to contain child nodes.
```
And having `must` or `when` in NP container is against this, so it is not NP container then. Regarding `must`, in all the examples here, I believe that the `must` statements are actually connected with some other node and should be placed somewhere else. 

Accepting your PR would probably make libyang more intuitive. But when comes to explaining what is happening there, we have actually another exception in the existing exception (libyang does something special when NP container contains `must`, but if there are default children, the behavior is again different). I'm afraid of such complexity. So, it seems to me that just returning to the 1.x behavior would be better. Seems that ignoring the fact the NP container actually has some meaning may be more useful than strictly insist on that rule.

It was more complicated with the `when` statement since it changes schema according to the data. libyang then needs always check for when to decide if the default NP container is supposed to be there or not. But seems that we had to solve this already also for the default leaf nodes with `when`, so I believe it could work even with NP containers. @michalvasko, please check the consequences of reverting the behavior, back to what the libyang 1.x does, in sysrepo and libnetconf2.

**Comment by michalvasko** [comment]
Please try the latest version, the implicit presence containers were removed.
