### ISSUE TITLE
ly2: Please consider a new basename

### ISSUE THREAD

**Issue by choppsv1** [CESNET/libyang#1515]
During the FRR meeting we discussed how much better it would be if libyang version 2 would actually change it's name to `libyang2`. This would allow both major versions to coexist peacefully. Having to create multiple VMs or install and uninstall libyang package really impedes on development.

Perhaps more importantly, adoption of libyang2 will obviously not all happen at the same time, and without a peaceful way to coexist one can't use 2 packages where one depends on libyang v1 and the other on libyang v2.

This is a pretty common thing for library packages to do when changing major versions numbers.

**Comment by qlyoung** [comment]
I agree with this. Considering that libyang2 is a complete rewrite I think it is appropriate to change the basename. Obviously at a bare minimum the SONAME needs to be updated.

**Comment by michalvasko** [comment]
The idea was what @qlyoung said, to just increase the SONAME (already is). Meaning the base package + the binary ones (if yanglint is separate) can coexist on a machine but you can have only a single devel package. Is there any problem with this?

**Comment by qlyoung** [comment]
Increasing the `SONAME` does not mean you can have both packages `libyang` version 1 and `libyang` version 2 installed on the same system, they need to be two separate packages for that to happen.

Eg in Debian, it's called [libyang0.16](https://packages.debian.org/buster/libyang0.16); @choppsv1 is saying (and I agree with him) that the new one needs to be `libyang2`. We feel a larger distinction than `SONAME` needs to be made here since the two libraries are completely incompatible with each other.

**Comment by rkrejci** [comment]
Packages are something different, and honestly, the current codebase does not contain any supporting scripts or other files for packages (no matter if deb or rpm) yet. The crucial is the `SONAME`, which allows the linker to handle both library versions, so then you can install and use them both. The name of the packages is something different and more up to the maintainers of the packages (I expect that the name of the package will be really different and there will be just some Conflict relationship between the devel packages).

To be clear, our intention is to allow have libyang 1.x and libyang 2.x library binaries installed. As @michalvasko mentioned, the devel files (includes headers) and `yanglint(1)` are a different story.

We have some experience with changing the names of the projects after rewrite (libnetconf2, Netopeer2). The problem is, that such projects then coexists side-by-side and confuse new users, while our intention was to replace the previous generation. So, we have decided to be, let's say, more aggressive in the case of libyang.

So, while it shouldn't be a problem to have both library binaries available (for the compiled depending binaries), you are not allowed to install the devel files into the same location. For the developers and users with some experience (who compile something), it should be still quite easy to have both devel files versions in a different location (you don't have to install them) and provide them via `-I` option (or indirectly via a variable for Cmake/Automake) to the sources being compiled.

I know there is an inconvenience, but we take it as a part of the motivation to move to libyang 2.x and forget libyang 1.x. We still plan to support 1.x for some time, but we don't have the resources to keep such support for a long time.

**Comment by jktjkt** [comment]
> For the developers and users with some experience (who compile something), it should be still quite easy to have both devel files versions in a different location (you don't have to install them) and provide them via `-I` option (or indirectly via a variable for Cmake/Automake) to the sources being compiled.

I'm not saying that this decision is bad, but this extra-prefix workaround is not feasible on source-based distros (they need to keep the headers et al around in a stable location). It is also not possible when doing embedded builds in any sane manner (i.e., not a pile of custom scripts); these typically work as a source-based distro. Buildroot certainly does, and I would be surprised if Yocto was any different.

Anyway, given that there's effectively a requirement for a flag-day migration anyway because sysrepo, netopeer2 and "anything which pushes data there" can only reasonably use the same version of libyang, I think the practical implications are not that serious.

**Comment by michalvasko** [comment]
> For the developers and users with some experience (who compile something), it should be still quite easy to have both devel files versions in a different location (you don't have to install them) and provide them via -I option (or indirectly via a variable for Cmake/Automake) to the sources being compiled.

This is a possibility but should not be used, preferably. If you are developing and compiling applications, you should definitely choose only one *libyang* version.

So I assume this issue is resolved and everyone is mostly in agreement in how to organize the packages.

**Comment by choppsv1** [comment]
Already getting questions about this only a day or two after the merge... sigh.

**Comment by michalvasko** [comment]
Questions about what exactly? People wanting to have both *libyang2-dev* and *libyang-dev* packages installed?

**Comment by choppsv1** [comment]
> Questions about what exactly? People wanting to have both _libyang2-dev_ and _libyang-dev_ packages installed?

Right, they need to install libyang2 to compile master, but then they can't compile any of the released versions.
