### ISSUE TITLE
ly_ctx_get_node to get node pointer

### ISSUE THREAD

**Issue by masif-cs** [CESNET/libyang#1518]
Hi,

I am using this function to get node pointer. In this function i need to pass xpath? Does it need to have all keys populated or without keys? How should the format be for xpath with multiple keys.

For example:
I want to search node "g" whose xpath is a/b/c[d]/e/f[g]/g. So what should be the right format to be passed to this function?
a/b/c[d='1']/e/f[g='2']/g
a/b/c[d='1']/e/f/g
a/b/c[d]/e/f/g

**Comment by michalvasko** [comment]
This is a bit special function just so that you do not have to bother with a schema path to get a node in case you have a data path. The main point is that you skip all schema-only nodes (choice, case, ...). Other than that, I think all of the paths you mention will work because any predicates are simply skipped since they have no meaning in this particular use-case.
