### ISSUE TITLE
How to work with `lyd_value`

### ISSUE THREAD

**Issue by syyyr** [CESNET/libyang#1617]
Hello,

I have a `lyd_value` of some (known) type. For basic types I should use a union field directly (like `int8` for int8), that's pretty clear. But what about other types? Specifically:
1) If I have `binary` value, I should use `LYD_VALUE_GET` to cast `lyd_value` to `lyd_value_binary`. That's pretty clear to me. However, this structure has a `void*` and a size. How do I work with this? Or maybe it's some sort of an internal representation? I figure users will want the string representation of the value anyway, since it's a Base64 string, but still, `lyd_value_binary` might be of some use to the user.
2) If I have `string` value, how do I retrieve it? There's no special struct to cast to and there's no union field.

**Comment by syyyr** [comment]
I just realized I can just use `lyd_get_value` for the string.

**Comment by michalvasko** [comment]
1. You are right about `LYD_VALUE_GET` and you can use it for all the types, even the ones present in the union, it is up to you. About `lyd_value_binary`, it is as specific as it can be because a `binary` value is defined as simply any value so it is stored that way. You are right, the (canonical) string representation is this value encoded in base64 but here the whole principle of having `canonical` and the `union` should be seen. The `union` value is the value represented in as "useful" way as possible for further processing inside an application. The `canonical` value is simply the canonical text representation of each value. And you can always choose which one you want to work with. There are also some optimizations included. Such as, if you create a value from its binary representation (`LYB`) and work only with that, the canonical text representation is never generated. That may have a huge performance impact for large data sets and specific value types (millions of IPv6 addresses, for example).
2. Yes, `lyd_get_value()` should be used, as mentioned in the description of `_canonical`.

**Comment by syyyr** [comment]
Thank you for the explanation. I think I understand the difference between the union value and the string representation. However, I still don't have to work with the memebrs of the `lyd_value_binary`. It's a `void` pointer and a size. If it was a `char` pointer, I would understand - it would a char array with a size. But this is a void pointer. What's the type? And in what units is the size? How do I work with the `lyd_value_binary` struct?

**Comment by michalvasko** [comment]
> I still don't know how to work with the memebrs of the lyd_value_binary struct.

That is the point. Neither me (as the designer of C API) nor you (the designed of C++ API) know how to work with the value because it can be absolutely anything. Only the actual user knows what the particular binary value represents and I expressed this in C by defining the value type as `void *`, it is up to you to come up with something in C++.

For example, you can have a X.509 certificate stored in this value and in that case you could define a structure such as
```C
struct x509_cert {
  char subject[255];
  char issuer[255];
  ...
};
```
and then what you can do is
```C
struct x509_cert *cert = binary->data;
```
assuming the fields have static length (which I doubt, but as an example it should be enough).

> And in what units is the size?

That is a good point, fixed.

**Comment by syyyr** [comment]
Ohhh, okay, I didn't realize one would want to use it like this (casting to struct).

One last thing: I wonder why the `void*` isn't something like a `uint8_t*`? Even though the meaning of the binary data is unknown to libyang/YANG, clearly it's a sequence of bytes, so it could be a `uint8_t*` (or similar). Also, libyang internally must use something else than `void*`, otherwise it wouldn't be able to fill in the bytes. Is this maybe some kind of a C idiom? As in "I don't know the type, so I'll give a `void*`". Or maybe it's because you can't convert `uint8_t*` to `my_struct*` directly? If so, then I understand.

**Comment by michalvasko** [comment]
> Is this maybe some kind of a C idiom?

I am not sure but it is the way I have used it :) But when a value is `void *`, it means it can be anything. Using `uint8_t *` is a little more specific and I do not think there is a reason for it. Your rationale that "it is a sequence of bytes" is a bit weak because every single piece of data is a sequence of bytes. The point here is that it is an unknown sequence of bytes and you **should** cast it to something more specific, which you are now forced to. Ultimately, I do not think it makes much of a difference but i like it more the way it is now.

**Comment by syyyr** [comment]
The reason why I'm calling it a sequence of bytes (or octets I guess) is because that's how the YANG rfc describes it:
https://datatracker.ietf.org/doc/html/rfc7950#section-9.8
>9.8.  The binary Built-In Type
>
>   The binary built-in type represents any binary data, i.e., a sequence
>   of octets.

But anyway, I'm fine with your explanation, it makes sense. Thank you.

**Comment by syyyr** [comment]
Actually, I have more questions about `lyd_value`, specifically instance identifier. If I understand correctly, to get the pointed-to node, I should use the `lyd_target` function to retrieve it. My questions are:
1) Why does the function return a const value? I would think that the node returned by this function would be just a normal node which I could edit and do whatever I wanted with it.
2) Why does the function `lyd_node_term`? In my understanding, `lyd_node_term` can only be a leaf or a leaf-list. But the instance identifier can point to much more node types, like a container. For example:
```yang
module example-schema {
    yang-version 1.1;
    prefix ex;
    namespace "http://example.com";

    container cont {
    }

    leaf myInst {
      type instance-identifier;
    }
}
```
```json
{
    "example-schema:cont": {},
    "example-schema:myInst": "/example-schema:cont"
}
```

**Comment by michalvasko** [comment]
Both fair points, the function prototype is probably obsolete and was not updated when should have been. So I have added a new function to be used for this purpose.

**Comment by syyyr** [comment]
Thanks!
