### ISSUE TITLE
JSON vs XML limitations

### ISSUE THREAD

**Issue by pepa-cz** [CESNET/libyang#1620]
I would like to open a discussion regarding the use of JSON data modelled by Yang. We often use the presence of empty lists in data which is a perfectly valid element according to RFC7951.

The fact, that the list is defined by its items is given by Yang language that is primarily based on XML format where an empty list cannot exist by its nature. However, JSON does not have limitation like this.

If we perform edit-config merge operation and there is an empty list in the data, all the existing list items are removed. If there is no list in data, the existing one remains unchanged. That is something not possible using XML format because the list in XML does not have any covering element but is defined only by its items. However, this limitation is given by XML data format, not by NetConf itself.

So we are wondering how we can achieve using empty lists in the JSON data with libyang library. Is it possible, or would it be possible to add this feature to libyang?

**Comment by michalvasko** [comment]
I do not think there is anything to discuss, really. I will explain.

> this limitation is given by XML data format, not by NetConf itself.

Well, since NETCONF is defined with having only XML as the transport protocol, it is the limitation of NETCONF as well. Meaning there is nothing to be changed for *libnetconf2* or *netopeer2*.

> would it be possible to add this feature to libyang?

Now talking about *libyang*, what feature would that be? There is no `edit-config` or anything similar in *libyang*. The closest to it is `diff`. However, it always represents exact changes and "removing all instances **if any**" is not such a change.

We are left with *sysrepo* that supports such an edit by using a list instance with the proprietary `purge` operation.

**Comment by pepa-cz** [comment]
> Now talking about libyang, what feature would that be? 

We are using libyang primarily for JSON data validation. The example with edit-config was just a demonstration showing the limitation of XML format, which does not exist when using JSON. The reason why we started using libyang is a low performance that we observed when we were using [yangson](https://github.com/CZ-NIC/yangson) or [pyang](https://github.com/mbj4668/pyang). In both of them, validation of empty lists was working but with libyang is not possible to even parse the data.

> Well, since NETCONF is defined with having only XML as the transport protocol, it is the limitation of NETCONF as well. 

Okay, I respect your point of view. However, as stated in the documentation, libyang itself is a parser and toolkit for working with data modelled by yang compliant with RFC7951 which does not explicitly prohibit empty lists in the data.

**Comment by michalvasko** [comment]
Okay, the way I understand is that you would like to be able to parse empty lists in JSON using *libyang* and everything else was only justification as to why it should be possible (and could have been left out because like you said, *libyang* does not depend on NETCONF or any other protocol).

> list is defined by its items is given by Yang language that is primarily based on XML format

Firstly, I would like to present my opinion on lists and their encoding. I disagree with what you said and believe it is actually the other way around. XML has no data types, only element types, so there is nothing like a list. Hence it is not a problem to write a list instance (element with the name of the list) without any children elements, it would be a valid XML. But such a "list" has no use in YANG data and is not valid. My point being, if YANG instance data were not reusing existing formats of XML or JSON and were to define its own and it was up to me, I would create a format that could not express list instances without its keys. This is already reflected in *libyang* v2 where you cannot create a list instance without its keys.

Having said that, there is support for `opaque` nodes whose purpose is to be able to express any *item* (element, object, however the format calls its structures) in any format, ideally. And you should be able to parse empty JSON list into such a node. But I still do not know what exactly you want to do with it. We are using it, for example, for parsing leaves without values (invalid), which could appear in NETCONF `edit-config` with `delete` operation.
