### ISSUE TITLE
XML parsing

### ISSUE THREAD

**Issue by masif-cs** [CESNET/libyang#1650]
Hi,

I was going through libyang v2 version where I see XML parsing is entirely changed. Earlier we use to have something like below:
struct lyxml_elem *xml = lyxml_parse_mem(ctx, bufferPtr, 0)
where lyxml_elem was link list which carries name, content, child, namespace etc.

But now we have to do something like below:
ly_in_new_memory
lyxml_ctx_new
and then using lyxml_ctx_next iterate through the list which will give LYXML_ELEMENT, LYXML_ATTRIBUTE, LYXML_ATTR_CONTENT, LYXML_ELEM_CONTENT.

Please let me know if I am going in right direction or is there any other simpler approach?

**Comment by michalvasko** [comment]
Firstly, `xml.h` is not a public header (it is not installed) so I am not sure how you managed to call functions defined there. In short, there is no (public) XML parser in *libyang* v2 because it is inefficient (creating XML structures first, then data nodes) and was not needed anymore. Why do you need to parse generic XML? Strictly speaking, there is no use-case for that in NETCONF/YANG.

**Comment by masif-cs** [comment]
I totally agree, Netconf input and output is in XML format. But I have a use case where I need XML to be converted to XPATH so that we can identify an attribute uniquely using XPATH. So I was converting that XML into XML structure and then generating the xpath by traversing it.

Is it possible to get the XPATH directly for the data(get-config, notification, rpc reply etc) received from Server? Or could you please suggest any better approach?

**Comment by michalvasko** [comment]
You mean you have some data that may include an attribute anywhere and you want to generate an XPath identifying that attribute but you cannot parse the data into standard data tree (because you are missing their YANG module(s)) before you have the XPath?  If you want to use *libyang* for this specific use-case, there is only [`LYD_PARSE_OPAQ`](https://netopeer.liberouter.org/doc/libyang/master/html/group__dataparseroptions.html#ga61f9946bb1caff5bdf9995d051520fa7) flag that you can use.

**Comment by masif-cs** [comment]
No, I have same yang module on both client and server. But I want XML received from server in get-config, notification or any RPC reply output to be converted to XPATH in general.

Like we use netopeer cli to do get-config, it dumps the output in XML format, but what I want is XPATH.

**Comment by michalvasko** [comment]
How exactly do you want to convert an XML into XPath? They express different things, XML is elements and values (text elements), XPath is an expression generally selecting specific elements from an XML.

**Comment by masif-cs** [comment]
I have a module which understands only XPATH and I have a module(netconf client) which works only with XML with netconf server. So for making these two modules understand the context, I want to convert XML to XPATH and vice versa.

So I was thinking if i could iterate through the XML elements and values and find the elements in yang context and put that into proper XPATH format?
```
<a>
    <b>
         <c>value1</c>
         <d>value2</d>
     </b>
<a>

```
XPATH:
/a/b[c='value1']/d value2

**Comment by michalvasko** [comment]
So you want a list of XPaths identifying each node? That should be possible. So just parse the data normally into `struct lyd_node *` tree and call `lyd_path()` on all the nodes, that will get you their XPath.

**Comment by masif-cs** [comment]
Is there any api where I can pass the XML and get the lyd_node tree?

**Comment by michalvasko** [comment]
Yes, you simply call one of the most basic functions of *libyang* for parsing data (`lyd_parse*()`).

**Comment by afzalap** [comment]
i want to get all the container and corresponding leaf nodes is it possible to get from lyd_node in seesion_server
