### ISSUE TITLE
Include file name/line number in libyang errors?

### ISSUE THREAD

**Issue by abhikeshav** [CESNET/libyang#166]
With the below faulty yang, libyang produces the correct errors, but it is not clear which module/line number the issue is at:
```
module m {
...
leaf t
        {
            type1 string;
        }
}
```
```
libyang[0]: Invalid keyword "type1".
```

It would be helpful to have the file name and line number in the error message like the below
```
libyang[0]: b.yang:12: Invalid keyword "type1".
```

**Comment by michalvasko** [comment]
Hi,
libyang was always meant primarily to handle YANG data, not check schemas even though that changed and we do quite complex schema verification. Still, tracking lines would be too much of an effort and would consume additional memory, so we will not be adding this feature. You should easily be able to identify the module in question, because it should be displayed right after the error you pasted here, something like `Module "b" parsing failed.`. You can also increase verbosity level if you need more detailed messages.

Regards,
Michal
