### ISSUE TITLE
Default value "0000-00-00T00:00:00Z" of ietf-yang-types:date-and-time throws error

### ISSUE THREAD

**Issue by rharishkumar** [CESNET/libyang#1698]
I have below leaf in my YANG model.
```
        leaf timestamp {
          type yang:date-and-time;
          default "0000-00-00T00:00:00Z";
          description "Current time-stamp";
        }
```
When adding this YANG, below error is thrown.
```
libyang[0]: Checking date-and-time value "0000-00-00T00:00:00Z" failed, canonical date and time is "-001-11-30T00:00:00".
libyang[0]: Path is related to the previous error message. (path: /abc:timestamp)
libyang[0]: Module "abc" parsing failed.
```
As the default value "0000-00-00T00:00:00Z" specified matches the regular expression pattern of IETF date-and-time, we hope this should work without any error. Please explain.
```
  typedef date-and-time {
    type string {
      pattern '\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(\.\d+)?(Z|[\+\-]\d{2}:\d{2})';
    }
```

**Comment by michalvasko** [comment]
Seems that in *libyang* v1 `date-and-time` requires all the values to be "valid", which means that ignoring the timezone, the date and time must be correct. It is hard to explain (`mktime(3)` is simply used), so, for example, it will not allow you to specify 29. February in a year that did not have it. The problem in this case is that there is obviously a shift of not just a day (as the previous example would correctly be written as 1. March of the particular year) but a whole month, it seems. I will not tell you why exactly (these are questions for some historians), there is some exception in how the date was going forward in the interval of year 0 up to the present.

Now, this requirement seems to have been lifted in *libyang* v2 but I am not sure what to do for v1. I would prefer to keep it this way because it would be a fairly significant change and we only want to do bugfixes for *libyang* v1.
