### ISSUE TITLE
Different validation errors for different order of files

### ISSUE THREAD

**Issue by SlavomirMazurPantheon** [CESNET/libyang#1706]
Hello,

yanglint is used in our YANG Catalog solution for modules validation.
Following issue was reported: https://github.com/YangCatalog/bottle-yang-extractor-validator/issues/74
It seems like there is a difference in validation result when files are in different order.
As described in the issue also different order of augments resulted in different validation errors.

Regards,
Slavomir Mazur

**Comment by michalvasko** [comment]
Even though I am using `yanglint` 2.0.93, I do not think it matters; I have tried changing the order of the loaded files arbitrarily but could not reproduce the problem. Please attach a `mw.in` file (from the archive in the other issue) that reproduces the error.

**Comment by samans** [comment]
I have attached a zipfile.  I have compiled the devel branch of libyang on ubuntu 18.04 to use for the test.  when I run the mw.in expect script the validation works.  If I run yanglint *.yang, I get...  

libyang err : Invalid default - value does not fit the type (Invalid identityref
 "te-types:path-setup-rsvp" value - identity found in non-implemented module "ie
tf-te-types".). (Schema location /ietf-network:networks/network/node/ietf-te-top
ology:te/tunnel-termination-point/local-link-connectivities/path-constraints/sig
naling-type.)
YANGLINT[E]: Processing schema module from ietf-bandwidth-availability-topology.
yang failed.

This is different behavior than the online yangvalidator, but does indicate that order of the input files matters.  Since I can get the validation to work when using an input expect script to order the files, the "yanglint *.yang" is more a convenience than a necessity.
thanks,
-scott
[mw-test.zip](https://github.com/CESNET/libyang/files/7285181/mw-test.zip)
.

**Comment by michalvasko** [comment]
Yes, these kind of errors I got and while to some extent they are caused by different order of the modules, we based this functionality on the specs. However, it is simple to avoid these problems if needed by using `-i` argument for the `load` command. I have just now added this argument also for the `clear` command so that it does not have to be specified for each `load`. So, after starting yanglint just run `clear -i` and it should work, I have tested it.
