### ISSUE TITLE
Can lyd_validate make a `NULL` pointer from a non-`NULL` pointer

### ISSUE THREAD

**Issue by syyyr** [CESNET/libyang#1715]
Hi, the `lyd_validate` function takes the to-be-validated node as an output argument, which means that it can change it. I was wondering: is it ever possible that the function gets a non-`NULL` argument and changes it to be `NULL`? For example, there are some nodes, that libyang thinks are not needed and deletes them all and sets the output argument `NULL` (since there are no more nodes).

**Comment by michalvasko** [comment]
Well, I do not particularly like it but I suppose something like that could be supported but it may be quite complex. Because I am not able (or rather willing to) to report all the changes accurately for a data tree to be valid without actually modifying the tree, the modification can cause some other changes to be needed and making some "virtual" changes is a mess that I will not be adding to *libyang* code.
