### ISSUE TITLE
List instance is missing its key error while yang_xml parsing

### ISSUE THREAD

**Issue by shijinbose** [CESNET/libyang#1760]
Hi,
I am using the latest libyang ver 2.0.130. While am using the api, lyd_parse_data for parsing the xml data, I have been encountering an error at "List instance is missing its key "relation-type". (Schema location /o-ran-uplane-conf:user-plane-configuration/relations/types, data location /o-ran-uplane-conf:types, line number 227.)". 
 
`lyd_parse_data_path(ctx, xmlfile, LYD_XML, LYD_PARSE_ONLY, LYD_VALIDATE_OPTS_MASK, &tree_data);`
This is the format and flags which I used.
I am attaching the xml which I used.
[o-ran-uplane-conf.txt](https://github.com/CESNET/libyang/files/7788662/o-ran-uplane-conf.txt)

**Comment by syyyr** [comment]
Hi, your data file is invalid because the list instance `<types/>` on line 227 is missing a key `relation-type`.

Which is exactly what the error message says:
```
List instance is missing its key "relation-type". (Schema location /o-ran-uplane-conf:user-plane-configuration/relations/types, data location /o-ran-uplane-conf:types, line number 227.)
```

**Comment by shijinbose** [comment]
@syyyr Thanks for the responds, but I was able to parse the same xml file using libyang ver 1 and I got this error only with libyang ver 2. Is there any way to bypass this issue?

**Comment by syyyr** [comment]
That seems weird. Ideally, if something worked in libyang1 and is not working in current libyang, you would post the code that worked and which is now not working. According to what you're saying, the error is clear to me. I am not sure what kind of schema you're using, but if it's [this one](https://gerrit.o-ran-sc.org/r/c/scp/oam/modeling/+/5706/3/data-model/yang/published/o-ran/ru-fh/o-ran-uplane-conf%25402020-12-10.yang#2192), then the keys of the `types` list are definitely mandatory (and your XML is invalid).

**Comment by shijinbose** [comment]
@syyyr As you told am attaching the sample codes for version 1 and version 2 which I used to parse data from XML.
[yang_lib.zip](https://github.com/CESNET/libyang/files/7800807/yang_lib.zip)

**Comment by syyyr** [comment]
Okay, I have looked at the code you posted. I assume you mixed up the filenames by mistake, because software_test_yang_vr1.c contains v2 code and software_test_yang_vr2.c contains v1 code. Anyway, the reason your v1 code works and your v2 code doesn't is because of the flags you use for the `lyd_parse_path`/`lyd_parse_data_path` call:
```c
	lyd_parse_data_path(ctx, "o-ran-uplane-conf.xml", LYD_XML, LYD_PARSE_ONLY, LYD_VALIDATE_OPTS_MASK, &root);
```
vs
```
	root = lyd_parse_path(ctx, "o-ran-uplane-conf.xml", LYD_XML, LYD_OPT_GET, NULL);
```
In libyang1, the `LYD_OPT_GET` flag allows for list keys to be omitted, see [here](https://netopeer.liberouter.org/doc/libyang/libyang1/html/group__parseroptions.html#ga41ac1e01040721442dbf691921087f9d) for documentation.

However, in libyang2, there is no such flag to allow omitting list keys. Even if you use the `LYD_PARSE_ONLY` flag, list keys are still required. This is documented [here](https://netopeer.liberouter.org/doc/libyang/master/html/group__dataparseroptions.html).

So, to fix your issue, either remove the invalid list from your data on line 227, or make it valid by adding the mandatory keys to it.

**Comment by michalvasko** [comment]
Thanks for the general explanation @syyyr but some information is missing. The functionality to parse such invalid data is preserved in *libyang* v2 but a completely different approach was used. You can parse that data using `LYD_PARSE_OPAQ` flag (which can be used for parsing data returned from `<get>`, for instance) but it will then create opaque nodes (`struct lyd_node_opaq`) instead of standard data nodes because those must always be valid (list instances have all the keys).
