### ISSUE TITLE
Question about parsing edit-config

### ISSUE THREAD

**Issue by awesomenode** [CESNET/libyang#1767]
Hi!

I have a question regarding parsing the config of an edit-config
operation.

In libyang1 there was the `lyd_parse_mem()` function with the
`LYD_OPT_EDIT` flag that got the job done. My question is how to
replicate the same behavior?

I tried using `lyd_parse_data_mem()` with the `LYD_PARSE_STRICT` flag, but
that cannot parse delete/remove operations properly, e.g.:
```
    <config>
      <basics xmlns="urn:com:test">
        <scalar nc:operation="delete" xmlns:nc="urn:ietf:params:xml:ns:netconf:base:1.0"/>
      </basics>
    </config>
```

Results in:
`Invalid empty int32 value.`

Using the `LYD_PARSE_OPAQ` flag would work, if not for the different
context of the server and sysrepo. I need to check somehow if the
config has at least schema definition in the server context.

Is there perhaps a solution to this problem using libyang2?

Thanks!

**Comment by michalvasko** [comment]
Well, yes, you should be using `LYD_PARSE_OPAQ` whenever you know there may be "invalid YANG nodes" that actually need to be parsed and processed.

> I need to check somehow if the
config has at least schema definition in the server context.

You can do this manually, I guess. *libyang* actually prints a `VRB` message when it parses a node with a schema definition as opaque, but that is all. Ideas for improvements are welcome but the actual `lyd_node_opaq` node cannot be changed. Best I could do is to add a flag for this, something like `LYD_OPAQ_SCHEMA`. But I would also like to know what do you need this for because in *netopeer2* (NETCONF protocol functionality) it was not needed.
