### ISSUE TITLE
yanglint issue: Missing required element "module-set-id" in "modules-state".

### ISSUE THREAD

**Issue by abhikeshav** [CESNET/libyang#177]
Just following the instructions in the README file, I'm seeing the below error. Any idea why?

```
./yanglint 
> list
List of the loaded models (mod-set-id 6):
    yang@2016-02-11
    ietf-inet-types@2013-07-15
    ietf-yang-types@2013-07-15
    ietf-yang-library@2016-06-21
    ietf-netconf-acm@2012-02-22
> add ietf-netconf-acm.yin
> data datastore.xml
libyang[0]: Missing required element "module-set-id" in "modules-state". (path: /ietf-yang-library:modules-state)
Failed to parse data.
```

**Comment by rkrejci** [comment]
The examples needed update - I have done it in devel branch which I would like to merge into the master soon. The issue here is connected with loading data as complete datastore with status information, so also data from internal ietf-yang-library module is expected. it is fixed in devel branch where the ietf-yang-library data are automatically merged with the input data being parsed as complete datastore.

**Comment by abhikeshav** [comment]
Thanks. Do you guys have any timeline when the devel branch is intended to be merged to master?

**Comment by rkrejci** [comment]
it should be during the next week
