### ISSUE TITLE
Confusing error response for invalid data values on create

### ISSUE THREAD

**Issue by pfeige** [CESNET/libyang#1781]
Hi,

when an incoming edit-config contains a leaf with an invalid value not satisfying required constraints according to the corresponding schema the reaction of libyang depends on the actual operation.
For a replace the violated constraint is used to return an appropriate error message, e.g. "Unsatisfied pattern ..." or "Unsatisfied length ...".
For a create no error is returned. Instead, the data node is created with a schema node pointer set to NULL (see [parser_xml.c:512](https://github.com/CESNET/libyang/blob/957a91fe101a3b1bfab46d9307cc9f4c9b2b0118/src/parser_xml.c#L512) and [parser_xml.c:383](https://github.com/CESNET/libyang/blob/957a91fe101a3b1bfab46d9307cc9f4c9b2b0118/src/parser_xml.c#L383 )). This makes the data node opaque and in such case sysrepo returns the error "Opaque (invalid) node ...". But this is the same error message a completely invalid node would produce, i.e a node not contained in the schema. So, regarding the error response it is not possible to distinguish between an invalid value and an invalid node.
Do you see a chance to get this changed?

BR,
Peter

**Comment by michalvasko** [comment]
No problem, fixed.

**Comment by pfeige** [comment]
Hi Michal,

unfortunately this is not the change I hoped to see. My problem description was not clear enough. What I really need is a way to distinguish between an invalid value and an invalid element node. The error message "Opaque (invalid) ..." from sysrepo is the right one for an invalid element node. For an invalid value I would like to see the "Unsatisfied ..." error messages from libyang. Can this be achieved in any way?

BR,
Peter

**Comment by michalvasko** [comment]
Well, *libyang* would print the exact problem when parsing the edit if `LYD_PARSE_OPAQ` was not used. Using it means that whatever it is not able to parse is stored as opaque data node. It is used because before parsing the edit we do not know whether there are not some invalid nodes with `delete` or `remove` operations that are actually supposed to be parsed as opaque nodes.

To get the specific error we would basically need to later try parsing the opaque nodes into proper data nodes, which is a functionality I have tried to avoid supporting. Also note that there are more use-cases such as a list having a key with an invalid value, in which case I would really need to add quite a lot of code to get the specific error. The way it is now the error is at least consistent.

**Comment by pfeige** [comment]
I tried a workaround using a bit in lyd_node.flags to transport the information about a invalid value from libyang to sysrepo. The bit is set in parser_xml.c:512 after checking whether the schema node pointer was cleared. And it is checked in edit_diff.c where the "opaque" errors are set. But unfortunately the bit does not arrive in sysrepo for any reason. Do you have a hint here?

**Comment by michalvasko** [comment]
I do not know what but you are referring to, the lines do not match any recent branch, best to send links to the files directly. But if you care that much, you can try providing a patch. Best would be to keep the opaque (`!node->schema`) checks but instead of only printing the current generic error, you would make *libyang* generate the specific error, too. For values (leaves/leaf-lists) it should be quite simple to use `lyd_value_validate()`. For invalid list instances it is more difficult but should still be okay. Just write a function that will check all that is checked during parsing meaning whether the list has a schema definition and all its keys. If so, then just check the value of each key and you must get an error at some point.

**Comment by pfeige** [comment]
That works! In order to differentiate between invalid element or value it is sufficient to try to get the schema of the node (lyd_node_get_schema()). If it exists it must be the value if not then it is the element.
Thanks!

**Comment by michalvasko** [comment]
You have probably not read my reply carefully enough, I just gave you hints so that you can implement these changes yourself :) But it should not be too much work so I may do it once I find some time, not sure when that will be.

**Comment by michalvasko** [comment]
Okay, should work with the latest *libyang*/*sysrepo*.

**Comment by pfeige** [comment]
Hi Michal,

@ddomingos-daitan found a segmentation fault in your fix above. He created the issue #1798 and provided a call stack. It seems that lyxml_ns_get() is called with a parameter ns_set of NULL.

BR,
Peter
