### ISSUE TITLE
LYD_OPT_WHENAUTODEL in libyang2

### ISSUE THREAD

**Issue by pepa-cz** [CESNET/libyang#1788]
Is there something like [LYD_OPT_WHENAUTODEL](https://netopeer.liberouter.org/doc/libyang/libyang1/html/group__parseroptions.html#ga32a9478882ae7a6b543de926303fcf89) option when parsing data in libyang1 also in libyang2? I have data that I am able to parse with LYD_PARSE_ONLY flag but validation breaks due to the presence of items that do not meet when statement conditions and should be removed.

**Comment by michalvasko** [comment]
The flag should not be needed in *libyang2* as it behaves precisely as [specified](https://datatracker.ietf.org/doc/html/rfc7950#section-8.2). The silent data tree updates are defined only for data modifications. Our interpretation of that is that a `when` must first evaluate to true and only when after some data change and next validation that `when` evaluates to false, it is silently removed. If it is not satisfied on the first validation, it is not considered data modification and an error is raised.

It is possible to store/load such validated data but only in LYB format because that is the only one storing the data node validation flags, it is not possible to store them in an XML/JSON file. If really needed, it should not be too much trouble to support a use-case when you tell *libyang* directly that you are loading data that were validated before.

**Comment by michalvasko** [comment]
After thinking about this some more, you can manually go through the parsed data tree and for each node with when set `LYD_WHEN_TRUE` flag for it. After that validation will think when was true before and will silently remove the nodes. Also, are the data you are parsing ordered meaning are the data nodes in the same order as the schema nodes, same list and leaf-list instances following right after each other?

**Comment by pepa-cz** [comment]
> After thinking about this some more, you can manually go through the parsed data tree and for each node with when set LYD_WHEN_TRUE flag for it. After that validation will think when was true before and will silently remove the nodes. 

Good, that works as expected. Thanks!

> Also, are the data you are parsing ordered meaning are the data nodes in the same order as the schema nodes, same list and leaf-list instances following right after each other?

Not necessary but the schema is already used in process of preparing original data (there is some data rearrangement) and can be used also use for data reordering.

**Comment by michalvasko** [comment]
> Good, that works as expected. Thanks!

So are you fine with this solution?

> Not necessary but the schema is already used in process of preparing original data (there is some data rearrangement) and can be used also use for data reordering.

I was just asking to know how should I redesign the flags but if this works fine for you I will keep it the way it is.

**Comment by pepa-cz** [comment]
Yes, I think this solution is okay for us!
