### ISSUE TITLE
yanglint: cannot add module with if-feature in uses

### ISSUE THREAD

**Issue by pfeige** [CESNET/libyang#1789]
Hi,

when trying to add a YANG schema with dependent features in yanglint the following libyang error is shown:
~~~
$ yanglint
> searchpath /yang
> add /yang/issue-if-feature2.yang
libyang[0]: Feature "fb" cannot be enabled because its "if-feature" is not satisfied.
~~~
The used YANG modules are:
~~~
module issue-if-feature2 {
  namespace "urn:issue:if:feature2";
  prefix if;
    
  import issue-if-feature2-b {
    prefix if-b;
  }

  augment "/if-b:b" {
    leaf x {
      type string;
    }
  }
}

module issue-if-feature2-b {
  namespace "urn:issue:if:feature2:b";
  prefix if-b;
  
  import issue-if-feature2-c {
    prefix if-c;
  }
  
  feature fb {
    if-feature if-c:fc;
  }

  container b {
    uses if-c:c {
      if-feature fb;
    }
  }        
}

module issue-if-feature2-c {
  namespace "urn:issue:if:feature2:c";
  prefix if-c;

  feature fc;

  grouping c {
    container z {
      if-feature if-c:fc;
      leaf x {
        type string;
      }
    }
  }       
}
~~~
BR,
Peter

**Comment by michalvasko** [comment]
This behaves as intended although perhaps hard to grasp. By default, **all features** of **implemented** modules are enabled. In your scenario, `issue-if-feature2` and `issue-if-feature2-b` are implemented (because of the augment) so feature `issue-if-feature2-b:fb` is enabled. However, that fails because `issue-if-feature2-c:fc` is disabled because `issue-if-feature2-c` is not implemented.

The simplest fix is using `-ii` parameter, which causes all the modules to be implemented hence even `issue-if-feature2-c`, so its feature `fc` gets enabled as well. Or, you could manually specify the enabled features for each module.

**Comment by michalvasko** [comment]
This behaves as intended because by default **all features** of all **implemented** modules are enabled. But `issue-if-feature2-c` is not implemented so its feature `fc` cannot be enabled. To fix, you can create a context that makes all modules implemented with the command `clear -ii`. Or you can specify the enabled features manually and disable the feature `add -Fissue-if-feature2-b: /yang/issue-if-feature2.yang`.

**Comment by pfeige** [comment]
OK. This works works for me.
Thanks!
