### ISSUE TITLE
Cannot read `binary` values exported from libyang v1 sysrepo

### ISSUE THREAD

**Issue by jktjkt** [CESNET/libyang#1793]
When importing JSON data, `sysrepocfg` rejects `binary` leafs exported from libyang v1 sysrepo. Here's how the data look like (this example was exported by `sysrepocfg -f json -d startup -x /ietf-keystore:keystore/asymmetric-keys/asymmetric-key/public-key -X` on a box with sysrepo v1):
```json
{
  "ietf-keystore:keystore": {
    "asymmetric-keys": {
      "asymmetric-key": [
        {
          "name": "genkey",
          "public-key": "MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA80TWKw2n2nGEAlkjAclL\u000Ayy49XCILRb5oIm4sx4/S2YPdYFakpppSXDoC2chuo4DXFHjkQuUf+AYCt/j+8jwl\u000AfJQSZkfMzrMGTwy6jW2fji+p9srGpv+cPEMJfojmyoYQoNA86cyc0tpQLQiZeQlA\u000AI/kk2j/JD47QrK5V82H0Dh2tHXgXjsK1lm8zDpe8nD0YE6duYM2dx75OVL4WcgS5\u000AjQ2+B2KAvZgO7G3Nc/7M1JEpBL661BmKWQ+gg/6u9jIAOe+PucCginvg2fBwDKBJ\u000AVcysgiqpvKqYqpjCwcDi6C5v1Oxw7ocfQobl/mHjFdNxorfEMnuLatrafS5LXtd0\u000AnwIDAQAB"
        }
      ]
    }
  }
}
```
As you can see, the exported data contain `\u000A` -- a newline -- at offset 64 (and a few times more afterwards). These data were originally created by Netopeer2's installation scripts, and with sysrepo v1 they are being loaded just fine. Since we're using the JSON dump of the `startup` datastore for data persistency, the upgrades are broken by this strictness:
```console
root@box # /bin/sysrepocfg -d startup -f json --import=/cfg/sysrepo/startup.json
libyang error: Invalid Base64 character 0xa.
sysrepocfg error: Data parsing failed
For more details you may try to increase the verbosity up to "-v3".
```

Would you mind relaxing this check?

**Comment by michalvasko** [comment]
It is no secret that *libyang* v1 were often handling types in a practical manner ignoring the specs and this is one such a case (there can be only base64 characters according to specs). However, since PEM files use a newline after every 64 base64 characters, I am willing to allow this particular case and there should be no harm in it, I hope. But only ignoring newline every 64 characters, otherwise the valid value space would be too large accepting invalid values. Sounds fine?

**Comment by jktjkt** [comment]
Yes, it looks that these offsets are always divisible by 64.
