### ISSUE TITLE
build artifacts for 2.0.164

### ISSUE THREAD

**Issue by hellt** [CESNET/libyang#1832]
Hi all,
can someone trigger the build pipeline so that packages for 2.0.169 be produced?

**Comment by michalvasko** [comment]
What do you mean, why that version in particular? But you can build your own packages easily, look into the `distro` directory.

**Comment by hellt** [comment]
I mean that the latest release doesn't container build artifacts as seen here https://github.com/CESNET/libyang/releases

The reason I am interested in that one in particular is because it conaints a fix for wrongfully imposing schema ordering for extension keyword in module definition.
Also the past version had rpm/deb available, which warrants the question why the latest one doesn't.

We are now trying to use libyang instead of pyang for both linting and tree generation (https://twitter.com/ntdvps/status/1512528678210650112) and having an easy way to install libyang is a key in that endeavor.

Ultimately, what we do is we package libyang/yanglint in a container, and for the previous version our dockerfile could be as short as this https://github.com/hellt/yanglint-container/blob/main/Dockerfile (leveraging downloading deb files from GH releases).
If the new releases won't be published we would have need to build those artifacts ourselves, which is a step that was not needed before given that packages were available.

**Comment by michalvasko** [comment]
Well, there will be no packages of version 2.0.169 in any case since it is not a released version. I would really suggest you build your own packages, it is trivial. We do have provided some packages for the previous release but that was only because we knew the official ones will not be ready. Unfortunately, they still are not (soon) but generating packages manually is a chore that we would not like to repeat. It is much simpler to generate a single package for your specific distribution.

**Comment by hellt** [comment]
oh, I am sorry, I meant to say `2.0.164` version (the latest released one). Will fix the typo in the issue title.

So to sum my questions in a ordered list:

1. will yanglint maintainers provide packages for officially released versions (the ones listed in releases section of this repo)?
2. if not, can we rely on `apkg` to be the recommended way to build packages for distros?

**Comment by michalvasko** [comment]
1. We will provide packages for all the officially released versions once our submissions are accepted, updating should then be straightforward and fast. However, solving all the issues of the reviewers is a really slow process and despite doing what we can since the beginning of this year, it is still not done. But the progress is significant so ideally it several weeks, for RPM. DEB packages should follow after, rough estimate a few months, hopefully.
2. You can always reply on using `apkg` for generating the packages. Once the official package building scripts are accepted, they will be committed into the repo as well.

**Comment by hellt** [comment]
thanks @michalvasko. I guess my confusion came after seeing 2.0.164 release being available in gh releases section without packages, while the previous 2.0.112 was with them. My understanding is that packages will follow later for 2.0.164.

In the meantime I think I will create a build pipeline with `apkg` building packages locally from the releases/tagged source code
