### ISSUE TITLE
In libyang-2.0.194,  how to find a match and validate a value with leaf reference node in union at a given XPATH?

### ISSUE THREAD

**Issue by feanis** [CESNET/libyang#1877]
Hi,

There are lots of internal changes with libyang-2.0.194 in contrast of libyang-1-0-225, I had an working function(lyd_node_leafref_match_in_union) with libyang-1 to check if the value matches with leaf reference nodes in union at a given XPATH, as shown below.

```C
// Using libyang-1-0-225, Check if value matches with leafref node in union
int lyd_node_leafref_match_in_union(struct lys_module *module, const char *xpath, const char *value)
{
        struct ly_set *set = NULL;
        struct lys_node *node = NULL;
        int idx = 0;
        struct lys_node_leaflist* lNode;
        if (module == NULL)
        {
                return -1;
        }
        set = lys_find_path(module, NULL, xpath);
        if (set == NULL || set->number == 0) {
                return  -1;
        }
        node = set->set.s[0];
        ly_set_free(set);
        //Now check if it matches with any leafref node
        lNode = (struct lys_node_leaflist*)node;
        for (idx = 0; idx < lNode->type.info.uni.count; idx++)
        {
                if (lNode->type.info.uni.types[idx].base != LY_TYPE_LEAFREF)
                {
                        //Look for leafref type only
                        continue;
                }
                if (0 == lyd_validate_value((struct lys_node*)
                    lNode->type.info.uni.types[idx].info.lref.target, value))
                {
                        return 0;
                }
        }
        return -1;
}
```
Please help me to implement the above functionality with Libyang-2.0.194.

Thanks & Regards,
Feanis Das

**Comment by Haititi** [comment]
Hi,
I'm commenting here because i found myself stuck with some similar problem.
I was first using `lys_find_xpath()` to try to find the target, but I am having problems with prefix resolving (I might create another issue for that).
I found this issue and tried to use `lys_find_path()`, but it won't work with relative path starting with ddots (like "_../interface/name_" ), as show in the [RFC example](https://datatracker.ietf.org/doc/html/rfc7950#section-9.9.6).

when i use it:
`lys_find_path()` calls `ly_path_compile()` which calls `_ly_path_compile()` with `lref = 0`.
 `lref = 0` makes us unable to use relative path with ddots.

I also found `ly_path_compile_leafref()` but it's not usable in our case because we can't call `lyxp_expr_parse()` first, as it's not public. Moreover, the `limit_access_tree = 1` might be problematic.

is there any solution here?

**Comment by michalvasko** [comment]
I do not understand your use-case, exactly. If you have a leafref node, it is parsed and so you should be able to use `ly_path_compile_leafref()`. If not, then what exactly are you doing?

**Comment by Haititi** [comment]
Well, I have a `schema` node of type `LYS_LEAF`, so i cast it to `lysc_node_leaf` and retrieve the `lysc_type` type.
The type's `basetype` is `LY_TYPE_LEAFREF` so i casted it to `lysc_type_leafref`.
From here i can retrieve the `lyxp_expr* path`.
Then i did what you said : 
i called `const char * xpath = lyxp_get_expr(((struct lysc_type_leafref *)type)->path)`, and i got the path `"../interface/name"` .
I then called `target = lys_find_path(NULL, schema, path, 0)`, but this fails (`target` is NULL), because `lys_find_path()` uses `ly_path_compile()` internally, which does not support leafref nodes.

So i try to understand which method should be used here, as the one you gave in the previous comment is not working.

**Comment by michalvasko** [comment]
I see. Well, you can always use `lys_find_xpath()` that accepts all the XPaths.

**Comment by Haititi** [comment]
Thanks for your reply.
I will create another issue then for the problem i'm encountering.
