### ISSUE TITLE
Question: print "HIDDEN" for a leaf

### ISSUE THREAD

**Issue by lioyerar** [CESNET/libyang#1921]
Hello, I wonder if it is possible to print "HIDDEN" instead of leaf's value with lyd_print_clb?

**Comment by michalvasko** [comment]
No, the printing callback has no information about what it is printing, it is meant to enable a custom output handler, nothing else.

**Comment by lioyerar** [comment]
Thanks.

How can I do such a thing with libyang?

**Comment by michalvasko** [comment]
You cannot, currently. What you are asking for could be classified as an extension because no such functionality is available in YANG. But even so, *libyang* does not support a custom way of printing nodes with extensions, so it is not possible. But I am wondering whether you really do need this functionality. If you have some sensitive data that should not always be displayed, it is the responsibility of NACM in a NETCONF server to implement this. It should not be handled on *libyang* level.

**Comment by lioyerar** [comment]
Ok, I get it.

Thanks for you quick response.
