### ISSUE TITLE
test failure for utest_structure on big endian architectures

### ISSUE THREAD

**Issue by rfc1036** [CESNET/libyang#1968]
In the last Debian upload I enabled the test suite, but as shown on https://buildd.debian.org/status/package.php?p=libyang2 the "utest_structure" test fails on some architectures: s390x, hppa, powerpc, ppc64 and sparc64 (everything else can be ignored). Crucially, a build failure on s390x means that the package cannot be part of the next Debian release, which will be frozen soon.
By looking at https://wiki.debian.org/ArchitectureSpecificsMemo I see that all the faulty architectures are big endian and all the working ones are little endian.

**Comment by michalvasko** [comment]
I have tried to fix this in every way I could think of to no avail. The problem is in the function [`lyplg_ext_get_storage()`](https://github.com/CESNET/libyang/blob/devel/src/plugins_exts.c#L604) when `storage` points to a `uint32_t` value. Specifically, there is a value that should get copied but only `0`s are. You can take a look at how it was before (b987850c9) and may try to figure it our yourself, I do not have any big endian architecture available, unfortunately.

**Comment by glaubitz** [comment]
@michalvasko You can obtain access to a big-endian machine through the GCC Compile Farm. There are POWER and SPARC64 machines available, for example.

See: https://gcc.gnu.org/wiki/CompileFarm

**Comment by borntraeger** [comment]
For a quick test you can also use qemu-system-s390x to run a recent cloud image (fedora for example) if you are familiar with qemu. 

You can also request a free of charge test system in the Linuxone community cloud 
https://developer.ibm.com/articles/get-started-with-ibm-linuxone/ 
or a direct link
https://www.ibm.com/community/z/linuxone-cc/request-vm

Looking at the code

        *s = htole64(*s);
        memcpy(storage, s, storage_size);
        *storage = le64toh(*storage);

this will probably not work.
Assuming storage_size=32 and 0x12345678  
in memory for LE it is 0x7856341200000000 at the given address
after htole64 of this pointer then becomes 0x0000000012345678
and the memcpy will only copy the first 4 bytes (all zeroes).
So depending on wether you actually need the endianess conversion (and the original code did not convert it seems) you might need to change the offset (64-storage_size)/8 into the point for the memcpy or you should actually get rid of the htole64

**Comment by michalvasko** [comment]
Thanks, I will test it using some of these options but the current code (`devel`, the first [link](https://github.com/CESNET/libyang/blob/devel/src/plugins_exts.c#L604)) is not working either and is using simple `memcpy`, I have also tried explicit conversion to the respective `uint_t` types with no success.

**Comment by onitake** [comment]
@glaubitz This was exactly what I suspected as well - something is processing 64 bit data as 32 bit, and that will only copy the first 32 bits. On a little endian system, this will work. On a big endian system, it will only copy the 4 most significant bytes, which seem to be always 0 here.

**Comment by glaubitz** [comment]
> @glaubitz This was exactly what I suspected as well - something is processing 64 bit data as 32 bit, and that will only copy the first 32 bits. On a little endian system, this will work. On a big endian system, it will only copy the 4 most significant bytes, which seem to be always 0 here.

Yeah, fully agree. That reminds me, I think the qemu-user you debugged issue still hasn't been fixed.

**Comment by borntraeger** [comment]
> Yeah, fully agree. That reminds me, I think the qemu-user you debugged issue still hasn't been fixed.
@glaubitz any pointer to the qemu issue?

**Comment by noloader** [comment]
@michalvasko,

> Specifically, there is a value that should get copied but only 0s are. You can take a look at how it was before (https://github.com/CESNET/libyang/commit/b987850c94058bb44522544c59b9e4b5ba7f20ab) and may try to figure it our yourself, I do not have any big endian architecture available, unfortunately.

I'd be happy to help. I have a PowerMac G5 running Debian and hanging off the internet. You are welcomed to it.

Please send me your `authorized_keys` file. Send to noloader, gmail address.

**Comment by uweigand** [comment]
> Thanks, I will test it using some of these options but the current code (`devel`, the first [link](https://github.com/CESNET/libyang/blob/devel/src/plugins_exts.c#L604)) is not working either and is using simple `memcpy`, I have also tried explicit conversion to the respective `uint_t` types with no success.

I've debugged the `devel` branch on s390x, and it seems the problem is
https://github.com/CESNET/libyang/blob/2b7987727537beaaf2c0f7187a96ba8f76d6a705/src/plugins_exts.c#L334

This assumes the contents of `storage` are always a pointer.  When that pointer (`storagep`) is passed to `lys_compile_ext_instance_stmt`, but in the particular instance the contents of the storage actually were just an integer, that routine then does something like:
https://github.com/CESNET/libyang/blob/2b7987727537beaaf2c0f7187a96ba8f76d6a705/src/plugins_exts.c#L224

This doesn't work on big-endian architectures.  If the contents of storage are e.g. a `uint16_t`, the code in line 334 will re-interpret those as a pointer, where the `uint16_t` ends up in the least-significant bytes of the pointer value on little-endian platforms, but in the most-significant bytes on big-endian platforms.  The code in line 224 however always extracts the least-significant bytes, resulting in the wrong value (usually always 0) on big-endian.

Using hacks like this:
```
        *(uint16_t *)substmt->storage = *(const uint16_t *)&parsed;
```
in all relevant places makes it "work" for me (all tests pass).   However, this still isn't really clean, in particular it violates C aliasing rules.

It would be preferable to avoid the assumption that storage always contains a pointer in the first place, e.g. by just passing the original `extp->substmts[u].storage` to `lys_compile_ext_instance_stmt` and do the access using whatever type is appropriate in that routine instead of its caller.

There is then still a problem with implementing this memoization logic
https://github.com/CESNET/libyang/blob/2b7987727537beaaf2c0f7187a96ba8f76d6a705/src/plugins_exts.c#L336
but that seems likely broken for the cases where the content of storage are not a pointer anyway.

**Comment by noloader** [comment]
I don't think this is wise. It works on some architectures, but jumps up and bytes on others:

```c
*(uint16_t *)substmt->storage = *(const uint16_t *)&parsed;
```

You risk a `SIGBUS` on some architectures with some data.

A better approach is to `memcpy` to a storage location in case the data is misaligned.

**Comment by uweigand** [comment]
I think it will work in practice anywhere since these pointer casts only reduce required alignment, never increase it, so you shouldn't get a SIGBUS anywhere.  But as it said, it's a hack for demonstration purposes, and isn't actually valid C, so I agree it should better be done differently.  (I would prefer avoiding the integer-as-pointer reinterpretation to begin with, then it doesn't need to be reverted ...)

**Comment by noloader** [comment]
> But as it said, it's a hack for demonstration purposes, and isn't actually valid C, so I agree it should better be done differently.

Awesome. A lot of folks want to keep those hacks for some reason. It does not matter if you explain to them it is undefined behavior, and the compiler can (and sometimes will) remove the code.

I eat my own dogfood. I've been through that with [Crypto++](https://www.cryptopp.com/). We had to remove those i386/i686/x86_64 micro-optimizations because we were getting `SIGBUS` and incorrect results because the compiler removed the [UB] code. Nowadays I use the pattern:

```
uint16_t t;
memcpy(&t, &parsed, sizeof(t));
substmt->storage = t;
```

It works everywhere with misaligned data, without the endian dance, and without undefined behavior. And better, the compiler will often elide/optimize the `memcpy` so you get the same code you were aiming for.

**Comment by michalvasko** [comment]
Okay, I have not expected such a discussion to be started here...

@noloader I have sent you my public key and I will try to use the solution you proposed but I am still not sure what exactly will work. There used to be [this code](https://github.com/CESNET/libyang/blob/master/src/plugins_exts.c#L604) that is fairly similar and was not working. So I guess I will try
```C
uint16_t t;
memcpy(&t, &parsed, sizeof(t));
substmt->storage = t;
```
but I am wondering about the other snippet
```C
uint64_t t;
memcpy(&t, &parsed, sizeof(t));
substmt->storage = (uint16_t)t;
```
which I do not think I need because I just need to copy values of various sizes (ideally in an endian-transparent manner), not truncate anything.

**Comment by michalvasko** [comment]
@noloader Thanks for the test environment, the problem turned out to be of the same nature but at different place and the solution really simple. The tests should be passing now.

**Comment by uweigand** [comment]
@michalvasko thanks for the fix!  I can confirm the current `devel` branch passes all tests on s390x as well.

**Comment by rfc1036** [comment]
I have backported https://github.com/CESNET/libyang/commit/118eb525978887b097df9413e6437ec257e25e6c to 2.1.4, but that test still fails. Do I need to backport more commits?

**Comment by michalvasko** [comment]
You need the referenced commit 118eb525978887b097df9413e6437ec257e25e6c.

**Comment by michalvasko** [comment]
Well, if what you say is true then obviously so.

**Comment by utkarsh2102** [comment]
Hi @michalvasko,

The same thing happens on the Ubuntu side as well. With 2.1.4 as base and backporting the above commit, the test still fails on s390x. Here are the build logs for your reference: https://launchpadlibrarian.net/646673133/buildlog_ubuntu-lunar-s390x.libyang2_2.1.4-2ubuntu1_BUILDING.txt.gz :(

**Comment by utkarsh2102** [comment]
@rfc1036: hey, perhaps try 2.1.30? It was released two hours ago, perhaps that should fix things.

**Comment by glaubitz** [comment]
> @rfc1036: hey, perhaps try 2.1.30? It was released two hours ago, perhaps that should fix things.

Just gave it a try on 32-bit PowerPC (big-endian). All tests pass!
