### ISSUE TITLE
False positive errors on cyclic dependencies

### ISSUE THREAD

**Issue by willtoth** [CESNET/libyang#1986]
When parsing [this IOS-XE model](https://github.com/YangModels/yang/blob/main/vendor/cisco/xe/1791/Cisco-IOS-XE-isis.yang) I get the following error:

```
> add Cisco-IOS-XE-isis.yang
libyang[0]: When condition cyclic dependency on the node "route-map". (path: Schema location "/Cisco-IOS-XE-native:native/router/Cisco-IOS-XE-isis:isis-container/isis/distribute-list/gateway-or-prefix".)
```

Here is a simple test with a similar structure gets flagged the same way

```yang
module cyclic-test {
  namespace "http://cisco.com/ns/yang/cyclic-test";
  prefix cyclic-test;

  container c1 {
    description
      "Container c1";
  
    container c1-c2 {
      when 'not(../c1-c3/c1-c3-l1)';
      leaf c1-c2-l1 {
        description
          "Leaf c1-c2-l1";
        type string;
      }
      leaf c1-c2-l2 {
        description
          "Leaf c1-c2-l2";
        type string;
      }
    }

    container c1-c3 {
      when 'not(../c1-c2/c1-c2-l1)';
      leaf c1-c3-l1 {
        description
          "Leaf c1-c3-l1";
        type string;
      }

      leaf c1-c3-l2 {
        description
          "Leaf c1-c3-l2";
        type string;
      }
    }
  }
}
```

Gives the same error

```
> add cyclic-test.yang
libyang[0]: When condition cyclic dependency on the node "c1-c3". (path: Schema location "/cyclic-test:c1/c1-c2".)
```

**Comment by michalvasko** [comment]
What makes you think this is a false-positive?

**Comment by willtoth** [comment]
I'm not able to find anything in the YANG RFC that shows this constraint is invalid. Do you have a reference from an RFC that there is something wrong with it as is?

For context, the example model works as expected when run with CONFD. I've attached some example RPCs done with this.

[circulat_dep_test.txt](https://github.com/CESNET/libyang/files/10842218/circulat_dep_test.txt)

**Comment by michalvasko** [comment]
The main reference would be [this](https://www.rfc-editor.org/rfc/rfc7950.html#page-137) text:
```
   If the XPath expression references any node that also has associated
   "when" statements, those "when" expressions MUST be evaluated first.
   There MUST NOT be any circular dependencies among "when" expressions.
```
It is just not clear what `reference` means exactly but let's look at your example. You have some YANG data with both `c1-c2-l1` and `c1-c3-l1` leaves (so their parent containers as well). You are then validating these data and come to the `c1-c2` container. You try to evaluate the *when* `not(../c1-c3/c1-c3-l1)`. Okay, so you are evaluating it and get to the point where you want to check the existence of `c1-c3` because that is one thing among those that affect the evaluation result. But, even according to the specs, you need to evaluate its *when* `not(../c1-c2/c1-c2-l1)` because that will determine `c1-c3` existence. So you try to evaluate it and this is the point where you get stuck in a loop between evaluating the 2 *whens*.

That is why `circular dependencies` are forbidden and I really do not care `CONFD` can work with this, I do not think it is possible so I must assume it is doing something wrong. We have our own XPath evaluator which supports all the features that YANG needs.

**Comment by willtoth** [comment]
Thanks for the detailed response, this is real helpful.

There are a number of published IOS-XE models that have a few errors and fail to load as a result. Is there any possibility to add a mechanism to allow setting some errors to be warnings?

While according to the spec this is a strict requirement about when's referencing when's, but without this restriction it is still possible to build up a model with these constraints. The confd trace shows what this could look like.

This question also goes for other errors that are seen in the IOS-XE models, such as in Cisco-IOS-XE-switch.yang

```
Status "deprecated" of "<uses>" is in conflict with "obsolete" status of parent "switchport".
```

**Comment by michalvasko** [comment]
> The confd trace shows what this could look like.

Then please mention, in detail, how to evaluate the example you provided. I have explained in exact steps why *libyang* throws the error.

> This question also goes for other errors that are seen in the IOS-XE models, such as in Cisco-IOS-XE-switch.yang

The status-inheritance problem is not explicitly mentioned in YANG specs so some changes may be possible. However, this error is quite sensible because `obsolete` data should not be instantiated and you cannot instantiate the child `deprecated` data without the parent so the situation does not make sense, at the very least. But, printing just a warning and forcing `obsolete` for all the children would be a solution as well.

**Comment by willtoth** [comment]
> Then please mention, in detail, how to evaluate the example you provided. I have explained in exact steps why libyang throws the error.

Okay let me put something together. I understand your point on why the error is currently thrown, and it makes sense to me.

> However, this error is quite sensible because obsolete data should not be instantiated and you cannot instantiate the child deprecated data without the parent so the situation does not make sense, at the very least.

Totally agree, this is an error in the model.

In both of these cases, if an opt-in option to make these warnings was available, I believe it would be useful for the library to increase compatibility with existing released vendor models that are not quite compliant.

**Comment by michalvasko** [comment]
> I believe it would be useful for the library to increase compatibility with existing released vendor models

In general, I am not against that but at the same time this is a dangerous way to go and defeats the purpose of standards. So, I mostly do not care that *libyang* refuses to load such modules.

**Comment by willtoth** [comment]
Thanks again for walking through this with me. We've temporarily forced these from errors to warnings in a custom patch, and plan to resolve this by getting the YANG models themselves fixed. I'll go ahead and close this as answered.
