### ISSUE TITLE
anyxml content is not printed by json printer

### ISSUE THREAD

**Issue by rastislavszabo** [CESNET/libyang#200]
This code attempts to print anyxml node content into a JSON file:
```c
#include <stdio.h>
#include <stdlib.h>
#include <libyang/libyang.h>


int main(int argc, char **argv)
{
  struct ly_ctx *ctx = ly_ctx_new("/home/rasto/sysrepo/tests/yang");
  ly_ctx_load_module(ctx, "test-module", NULL);

  struct lyd_node *root1 = lyd_new_path(NULL, ctx, "/test-module:main/xml-data",
    "<p xmlns=\"http://www.w3.org/1999/xhtml\">This is <em>very</em> cool.</p>", 0, 0);
  lyd_validate(&root1, LYD_OPT_CONFIG, ctx);

  FILE *fp1;
  fp1 = fopen ("test1.json", "w+");
  lyd_print_file(fp1, root1, LYD_JSON, LYP_FORMAT);
  fclose(fp1);

  lyd_free_withsiblings(root1);
  ly_ctx_destroy(ctx, NULL);
}
```
Produces following JSON (the content of `xml-data` gets lost):
```json
{
  "test-module:main": {
    "xml-data": {
    }
  }
}
```

YANG excerpt:
```yang
  container main {
    anyxml xml-data;
    anydata any-data;
  }
```

**Comment by rkrejci** [comment]
it should be fixed for anyxml, but note that this behaviour is sort of correct for anydata. In contrast to anyxml, anydata is limited  to the data that are modeled by a YANG module (despite it is unknown). However, libyang is not able to print XML data in JSON format without knowing the data model since JSON YANG data format differently encodes container and lists or it is important to know the datatype of the leaf/leaf-list to be able to decide if `<x>11</x>` is number or string, so converting XML data in anydata to JSON will be always limited.
