### ISSUE TITLE
c++ compilation error

### ISSUE THREAD

**Issue by sourcema** [CESNET/libyang#2012]
hi, my project is c++, using the latest ilbyang version 2.1.55, this problem occurs when compiling:  error: '_Atomic' does not name a type, i found that this is because the "compat.h" fiile contains the "stdatomic.h" file caused. does anyone have this problem? how to solve this?

**Comment by jktjkt** [comment]
It is not clear what exactly you're doing since `compat.h` is an internal header. It is not installed in the system, it's just used for building libyang itself -- and building libyang requires a C compiler, not a C++ one. What exactly are you doing? Are you aware of the [C++ bindings to libyang](https://github.com/CESNET/libyang-cpp/)?

**Comment by sourcema** [comment]
> It is not clear what exactly you're doing since `compat.h` is an internal header. It is not installed in the system, it's just used for building libyang itself -- and building libyang requires a C compiler, not a C++ one. What exactly are you doing? Are you aware of the [C++ bindings to libyang](https://github.com/CESNET/libyang-cpp/)?

can this compat.h file not be included when compiling? I understand that it is used to solve thread safety issues and needs to be included. I found this in the CMakeLists file: use_compat(); I included it when compiling libyang It, but the library compilation that references libyang.so in the c++ project will cause errors. I found this project([C++ bindings to libyang](https://github.com/CESNET/libyang-cpp/)), I didn't look carefully, it uses c++ to parse the yang model?

**Comment by michalvasko** [comment]
[This](https://github.com/CESNET/libyang/#usage) is how you are supposed to use *libyang* and you can additionally use the provided `FindLibYANG.cmake` if your project is using `cmake`. `compat.h` is not even being installed so you must be using it from the source, which you should never do.

**Comment by jktjkt** [comment]
@sourcema, what is the end result that you want to achieve?

**Comment by sourcema** [comment]
> @sourcema, what is the end result that you want to achieve?

I want to use this library in the c++ project and compile without error. It seems that it is caused by the introduction of the stdatomic.h header file in the new libyang project, because it uses the new features of C11.

**Comment by jktjkt** [comment]
> I want to use this library in the c++ project and compile without error.

In order to *use* a library, you have to *compile* it first. *Compiling* libyang requires a C compiler. It does not work when you try to use a C++ compiler to compile libyang. Then, once you have libyang *compiled*, you have to *install* it. Only then you can *use* libyang.

The above applies even if you want to *use* libayng in a C++ project. You still have to *install* libyang first, and that needs *compiling* libyang, and that needs a C compiler. This procedure works, we're routinely using libyang in C++ projects. What we are **not** doing is *bundling* the library *inside* the C++ project. That just does not work.

How exactly are you trying to *use* libyang in your C++ project?

**Comment by sourcema** [comment]
My project uses the netconf protocol communication, and uses the libnetconf library. I compile libyang with a c compiler. At the same time, I need to use the libyang header file when compiling my project. Compile libyang's compat.h with gcc, the header file reported the above error, because it contains stdatomic.h. So, I would like to ask if there is any solution?

**Comment by jktjkt** [comment]
Since `compat.h` is **not** a header which is *installed* by libyang, I still do not understand what exactly you're doing. Can you please describe this in much higher level of detail, including:
- what platform you're compiling on, and what platform you're targetting,
- what versions of which operating system and compiler you're using,
- how exactly you're triggering the build (a best case is the exact command-line invocation)
- a copy of all the output showing what exactly is going on

**Comment by sourcema** [comment]
> 
Can the compat.h file not be included? I found that it was included when compiling other header files.

1. Both the compilation platform and the target platform are CentOS Linux 7
2. kernel version：3.10.0-693.2.2.rt56.623.el7.x86_64，gcc 5.4
3. my project is compiled through makefile, do I need to upload the complete makefile?
4. I did not save the output, I will upload the output later, there are some other things to deal with now
