### ISSUE TITLE
does LYD_PRINT_WD_ALL not going to implement?

### ISSUE THREAD

**Issue by lyzliyuzhi91** [CESNET/libyang#2016]
I find that LYD_PRINT_WD_ALL_TAG has been implemented, but LYD_PRINT_WD_ALL  not yet. Has it been forgotten?
thanks.

**Comment by michalvasko** [comment]
What makes you think this WD mode has not been implemented?

**Comment by lyzliyuzhi91** [comment]
I search "LYD_PRINT_WD_ALL" in version 2.1.30, but only found in test file and header file, no other codes found in any other .c file. So how such option fullfil its feature? Thanks.

But  anyway, I did misunderstand this option before, I thought it is equal to "report-all" in RFC6243, and so i thought if I call "lyd_print_mem" with "LYD_PRINT_WD_ALL", it would add some extra default value in the string.

**Comment by lyzliyuzhi91** [comment]
```
    const char *source = "{\"ietf-netconf:edit-config\":{\"target\":{\"candidate\":[null]},\"config\":{}}}";
    err = ly_in_new_memory(source, &in);
    if (err != LY_SUCCESS) {
        return err;
    }

    struct lyd_node *out = NULL;
    err = lyd_parse_op(ctx, NULL, in, LYD_JSON, LYD_TYPE_RPC_YANG, NULL, &out);
    if (err != LY_SUCCESS) {
        ly_in_free(in, 0);
        return err;
    }

    char *target = NULL;
    err = lyd_print_mem(&target, out, LYD_JSON, LYD_PRINT_WITHSIBLINGS | LYD_PRINT_SHRINK | LYD_PRINT_WD_ALL);
    if (err != LY_SUCCESS) {
        ly_in_free(in, 0);
        return err;
    }

    printf("target:\n%s\n", target);
```

The final "target" only print 
```
{"ietf-netconf:edit-config":{"target":{"candidate":[null]},"config":{}}}
```

But in libyang1, 
```
    source =
        "{\"ietf-netconf:edit-config\":{\"target\":{\"candidate\":[null]},\"config\":{}}}";
    char *ly_target = NULL;
    struct lyd_node *ly_root2 = lyd_parse_mem(ly_ctx, source, LYD_JSON, LYD_OPT_RPC, NULL);
    lyd_print_mem(&ly_target, ly_root2, LYD_JSON, LYP_WITHSIBLINGS | LYP_WD_ALL);
    printf("ly_target:\n%s\n", ly_target);
```
It print as
```
{"ietf-netconf:edit-config":{"target":{"candidate":[null]},"default-operation":"merge","error-option":"rollback-on-error","config":{}}}
```

**Comment by lyzliyuzhi91** [comment]
emm, It seems the "parser" function do not add default node anymore, and I find "lyd_new_implicit_tree".
My carelessness, sorry & thanks.

**Comment by michalvasko** [comment]
That is a fair observation, I have added information about this to the function. I do not remember exactly anymore why the flags are used that prevent adding the default values but I think it is because every NETCONF server supporting default values should actually send them according to the `with-defaults` parameter of the RPC, which explains it for rpc-replies and notifications. As for the RPCs themselves, it is also expected a NETCONF client will print all the default values and if not then there is a reason for that. So it should not be needed to add them during parsing but as you correctly observer, you can always do that with the separate function.
