### ISSUE TITLE
A question about libyang extension parsing

### ISSUE THREAD

**Issue by pathori** [CESNET/libyang#209]
i have defined some extension and used libyang to parse the extension(Used the extension branch code). The data structure lys_ext populated all the values expect the  value of the argument.   
i have used below example to test and found that "MY_INTERFACES" value not filled in lys_ext structure. Please let me know if I am missing something.

     module my-extensions {
       ...

       extension c-define {
         description
           "Takes as argument a name string.
           Makes the code generator use the given name in the
           #define.";
         argument "name";
       }
     }

   To use the extension:

     module my-interfaces {
       ...
       import my-extensions {
         prefix "myext";
       }
       ...

       container interfaces {
         ...
         myext:c-define "MY_INTERFACES";
       }
     }

**Comment by rkrejci** [comment]
the `extensions` branch is still a work in progress. The extensions are currently supported only in YIN format, not YANG, that should be the issue in your case.

**Comment by pathori** [comment]
I have given the YANG syntax example but actually used the YIN format  to load.

**Comment by rkrejci** [comment]
weird, it is working for me:
```
./yanglint -f yang my-interfaces.yin 
module my-interfaces {
  namespace "urn:if";
  prefix if;

  import my-extensions {
    prefix myext;
  }

  container interfaces {
    myext:c-define "MY_INTERFACES";
  }
}
```

just a note - `lys_ext` is supposed to store the extension definition, so that one in `my-extensions` module. The instance of the `c-define` extension used in `my-interfaces` module is stored in `lys_ext_instance` - are you looking at the correct variable?

**Comment by pathori** [comment]
Yes even I am referring to the same structure lys_ext_instance. Can you please help me to tell the value "MY_INTERFACES" will be stored in which member?

**Comment by rkrejci** [comment]
First, try the yanglint as I've used in my case, do you have the same output?

You can check the `printer_yang.c` code, there is `yang_print_extension_instances()` function that accesses `lys_ext_instance` and print its content. Note, that `lys_ext_instance` is just a generic structure and according to the extension type, the structure is cast to a specific `lys_ext_instance_*` structure. Currently, we have only the `LY_EXT_FLAG` type of extension which expect no additional YANG substatement in it - from libyang point of view, your `c-define` is a flag extension. 

Remember, that the current implementation is still very limiting and many features I plan are not implemented yet. Anyway, if you need just the information about the `c-define`'s argument, you should be able to get it already.

**Comment by rkrejci** [comment]
One more note - since it is a work in progress, it is possible (and probable) that the API including the structures will change with the future changes in this area. Any suggestions about this from the API user are welcome.

**Comment by pathori** [comment]
Thanks a lot I could get the value with lys_ext_instance_flag. 
Some points, 
Is it required to have lys_ext_instance inside lys_ext?
extension support for multiple arguments also in the plan?
May need void *priv in lys_module also like lys_node? some users may want to store the private data at tis level

**Comment by rkrejci** [comment]
1. `lys_ext_instance` inside `lys_ext` - not sure yet, but in future we want to support having any YANG statement in extensions definition, so also the other extension instances can appear there. But maybe they will be inserted the same way as the standard YANG statements - somehow with the plugins. So we will see if the lys_ext_instance will stay in lys_ext as it is now.

2. multiple arguments - it is not allowed by RFC 7950 - argument's cardinality is `0..1`, but we want to support having other YANG statements in extension instances. It will be somehow connected with the extensions plugins, so the YANG module author will be responsible to provide some glue code into libyang to help us with parsing and understanding the extension instance content. This is in the design phase.

3. *priv in lys_module - please open a separate issue on this and let's discuss it there, this issue is about extensions. Anyway, I will need some more specific use case, because priv pointer in schema nodes are actually intended for the data processing
