### ISSUE TITLE
lyd_validate_all takes more than 8 secs.. 2.1.128

### ISSUE THREAD

**Issue by mksheera3** [CESNET/libyang#2326]
Hi, with 549 interfaces, to enter interface config mode it takes more than 8 secs... 

$ time sudo vtysh -c "conf t" -c "interface eth1"

real	0m12.085s
user	0m0.084s
sys	0m0.020s
$

I see, its because of lyd_validate_all. 
libyang is latest, as mentioned in FRR routing, 

$ sudo dpkg -l | grep libyang
ii  libyang1                          1.0.225-1.1                    amd64        parser toolkit for IETF YANG data modeling - runtime
ii  libyang2:amd64                    2.1.128-2~deb11u1              amd64        parser toolkit for IETF YANG data modeling - runtime
ii  libyang2-tools                    2.1.128-2~deb11u1              amd64        parser toolkit for IETF YANG data modeling - executable tools
$

1. tried with removing this API, it takes less time. 
2. apart from solution for this, wanted to understand whats the impact if this API is bypassed.

Thanks..

**Comment by michalvasko** [comment]
Having latest packaged *libyang* version is one thing, having the latest [release](https://github.com/CESNET/libyang/releases) another. I think there were some optimizations since then and I am currently working on another that should improve validation performance further and it should be in the next release before the end of this year. So if you are unable to update (version 3 has some minor NBC changes that FRR is likely incompatible with currently) and want to remove the validation, I am not able to tell you the possible consequences. Obviously, it is expected the data will be valid and if they are not, only FRR developers can tell you the effects.

**Comment by mksheera3** [comment]
Thank you @jktjkt  @michalvasko for quick replies. 

wanted to understand - what lyd_validate_all does ? 
1. if its disabled, on configuration can it create multiple entries in tree ? 
2. if we delete, it wont be updated ? 
3. does it have dependency on "when" statements in yang config file ?

**Comment by michalvasko** [comment]
It does YANG validation which means enforcing all the restrictions defined for [YANG 1.1](https://www.rfc-editor.org/rfc/rfc7950.html) data. If you skip it, the data may be invalid, which is likely not expected by the code you want to change so it may result in undefined behavior - a crash or pretty much anything. There are lots of restrictions checked and duplicates (1.) or `when` conditions (3.) are just two examples, you can find more in the RFC. Please direct any more questions to FRR, I do not think we can help you any more.
