### ISSUE TITLE
 if the xpath  is leafref, the value.leafref of  lyd_node which created by  lyd_new_path  is null 

### ISSUE THREAD

**Issue by ostack** [CESNET/libyang#263]
HI ,i found  if the xpath  is leafref ,the value.leafref of  lyd_node which created by  lyd_new_path  is null ,is this correct?
Thanks

```
API struct lyd_node *
lyd_new_path(struct lyd_node *data_tree, struct ly_ctx *ctx, const char *path, void *value,
                              LYD_ANYDATA_VALUETYPE value_type, int options)
```

**Comment by michalvasko** [comment]
Hi,

if you are using `master` branch, I cannot really comment, because there the leafrefs are a mess. That is why it was completely refactored and committed into `devel` branch for now. In it this is the correct result because `lyd_new_path()` is a `PARTIAL CHANGE`. What that means is described in the documentation.

Regards,
Michal
