### ISSUE TITLE
How to create RPC input anyxml nodes?

### ISSUE THREAD

**Issue by abhikeshav** [CESNET/libyang#275]
Hi,
I am trying to create a full get-config RPC with filter, but getting a null pointer when creating anyxml data node on the filter element. How can I do this? See the below code snippet
```
   struct ly_ctx* ctx = ly_ctx_new(TESTS_DIR);
     const struct lys_module * module = ly_ctx_load_module(ctx, "ietf-interfaces",NULL);
    module = ly_ctx_load_module(ctx, "ietf-netconf",NULL);
    
   // create RPC
    //struct lyd_node *root = lyd_new(NULL, module, "get-config"); 
    struct lyd_node *root = lyd_new_path(NULL, ctx, "/ietf-netconf:get-config", NULL, LYD_ANYDATA_SXML, 0); 
     assert_ptr_not_equal(root, NULL);
    struct lyd_node* filter =lyd_new_path(root, NULL, "filter", NULL, LYD_ANYDATA_SXML, 0);
     assert_ptr_not_equal(filter, NULL);
    struct lyd_node*  source =lyd_new_path(root, NULL, "source", NULL, LYD_ANYDATA_SXML, 0);
     assert_ptr_not_equal(source, NULL);
     lyd_new_path(source, NULL, "running", "", LYD_ANYDATA_SXML, 0);
   //so far no issues

   // create filter.
   // ******* Error occurs here ******
    struct lyd_node* cn =lyd_new_path(filter, ctx, "/ietf-interfaces:interfaces", NULL, LYD_ANYDATA_SXML, 0);
     assert_ptr_not_equal(cn, NULL);
```

**Comment by michalvasko** [comment]
Hi,
the last `lyd_new_path()` call contains several mistakes. But, to begin with, it should be deleted altogether, because the filter was already created when assigning to `filter`, empty, because you did not specify a value.

I am first going to assume you wanted to create a `get-config` RPC with an XPath filter `/ietf-interfaces:interfaces`. If you read the [NETCONF RFC](https://tools.ietf.org/html/rfc6241#section-8.9.5.1), you will learn that XPath filter is specified with 2 attributes of the `filter` element and that is exactly what you should do (`lyd_insert_attr()` may come handy, use `ietf-netconf` module for these attributes).

If, however, you are fine with the standard subtree filter then remove the last `lyd_new_path()` call and replace the 2nd `lyd_new_path()` call with `lyd_new_path(root, NULL, "filter", "<interfaces xmlns=\"urn:ietf:params:xml:ns:yang:ietf-interfaces\"/>", LYD_ANYDATA_CONSTSTRING, 0)`.

Regards,
Michal
