### ISSUE TITLE
Compilation in C++ fails because of use `new` keyword

### ISSUE THREAD

**Issue by arun11299** [CESNET/libyang#286]
In file `tree_internal.h`, function declaration of `lys_ext_dup` makes use of `new` as one of the argument name. `new` being a C++ operator for memory allocation, we cannot use this name.

The argument name should be changed to something else.

**Comment by rkrejci** [comment]
why do you need `tree_internal.h`? It is internal header and you are not supposed to use it in your program.

**Comment by arun11299** [comment]
We had a special need to make use of the referring type which was possible only by accessing `lys_types` struct. Also, it has some useful APIs such as `lys_is_key`, `lys_child`, `lys_get_sibling` etc.

**Comment by rkrejci** [comment]
This is unsafe way of using libyang, `tree_internal.h` and functions accessible via it are not ready for public use. `new` as a function parameter is correct since the function is internal and supposed to be compiled as C code, not as C++. If you think that you need to use some internal function outside the library, please let us know (in a separated issue) and we can discuss it.
