### ISSUE TITLE
Getting the augmented node from the target module

### ISSUE THREAD

**Issue by arun11299** [CESNET/libyang#290]
This is more of a question than an issue. Consider I have two modules, 'mod-a' and 'mod-b':

```
mod-b {
  container a {
    choice b {
      case c {
        ....
      }
      case d {
          ....
       }
     }
   }
 }
```

```
mod-a {
  augment /mod-b:a/mod-b:b/mod-b:c {
     ....
     leaf aug { .... }
   }

   augment /mod-b:a/mod-b:b/mod-b:d {
     ....
     leaf aug_2 { .... }
   }
   
}

```

Now, when I get the target node for the first augment in 'mod-a', which is " /mod-b:a/mod-b:b/mod-b:c", I want to get the node from the perspective of "mod-b" i.e without the augmented portion.
To be more precise, I want the node corresponding to 'case c' as it would have been if I had loaded 'mod-b' instead of 'mod-a'. Do we have an API for this or can it be done by composing existing APIs ?

Thanks.

**Comment by arun11299** [comment]
Currently I am trying to do something with `lys_find_xpath`. But this does not work if the xpath has depth of more than 1.

I get below error:

> libyang[0]: Schema node "test-augment-ly-b1:b1ch1" not found (/test-augment-ly-b1:b1_c/test-augment-ly-b1:b1ch1).

I am using the API like:
`ly_set* found_nodes = lys_find_xpath(ctx_, nullptr, aug_path, 0);`

**Comment by michalvasko** [comment]
Hi,
I don't really understand what is it you are trying to do. Firstly, the augments do not modify `case c` in any way, only its children are modified meaning there are some added (`leaf aug` for one).

Secondly, if you want to do something only with `case c` and its children that are from `mod-b` only, you can normally loop through them and ignore all that are from a different module, quite simply really. Or you can write an XPath expression that will filter some nodes out (I can help you with the expression, but I would need to know exactly which nodes you want to get and which not).

Also, from the error it is obvious the modules you are working with have different names and nodes, so please be consistent, otherwise I can easily suggest something that will not work for your actual use-case.

Regards,
Michal

**Comment by arun11299** [comment]
> Also, from the error it is obvious the modules you are working with have different names and nodes, so please be consistent,

I don't understand this. The xpath that I am using is basically `target_name` field of lys_node_augment. Why do you think the nodes would have different name ?

**Comment by michalvasko** [comment]
Well, the module examples are `mod-a` and `mod-b`, whereas the module in the `lys_find_xpath()` error you provided uses a module named `test-augment-ly-b1`.

Regards,
Michal

**Comment by arun11299** [comment]
Ah.. I see your confusion. My comment #1 was just describing the problem. My second comment is regarding the error that I am actually getting when using `ly_find_xpath` on the actual schema.
