### ISSUE TITLE
lyd_validate issue with ietf-system.yang?

### ISSUE THREAD

**Issue by abhikeshav** [CESNET/libyang#293]
With below code, I'm getting an error. Is this expected?
```c
   struct ly_ctx* ctx = ly_ctx_new(TEST"/models/ietf");   
   const struct lys_module * mm1 = ly_ctx_load_module(ctx, "ietf-system",NULL);
   assert_ptr_not_equal(mm1, NULL);

 struct lyd_node *root = lyd_new_path(NULL, ctx, "/ietf-system:system/authentication/user[name='testuser']", "", LYD_ANYDATA_SXML, 0); 
 assert_ptr_not_equal(root, NULL);
 lyd_print_mem(&buf, root,LYD_XML, LYP_FORMAT|LYP_KEEPEMPTYCONT|LYP_WD_ALL));
 printf("\n%s\n",buf); // so far no issues

 int re=lyd_validate(&root, LYD_OPT_CONFIG|LYD_OPT_NOAUTODEL, NULL); //getting error here
 assert_int_equal(re,0);

```

```
Unknown element "authentication". (path: /ietf-system:system/authentication)
```

**Comment by maixuanhan** [comment]
> `/ietf-system:system/authentication/user[name='testuser']`

Why does only `system` node have got the prefix. Please refer some xpath example at https://tools.ietf.org/html/rfc6020#section-9.13.5

**Comment by rkrejci** [comment]
@maixuanhan - libyang is not that strict, check [`lyd_new_path()` description](https://netopeer.liberouter.org/doc/libyang/devel/group__datatree.html#ga604d6c31968f22ae606525b6df04d6ee) and [general XPath info](https://netopeer.liberouter.org/doc/libyang/devel/howtoxpath.html). If the namespace/prefix is not specified, it can be taken from parent.

@abhikeshav - `authentication` container is under `authentication` if-feature, do you have it enabled? The reson why it is not recognized directly in `lyd_new_path()` is validation optimization. The data tree manipulation function allow you to create even invalid data tree (in various ways). The reason is that you can make it again valid by a set of the following modifications, so it would be problem to validate it all the time, instead, there is the `lyd_validate()` which does it at the specified point when you declare that you did all the changes and now you expect the data tree to be valid.

**Comment by abhikeshav** [comment]
Thanks for the reply @rkrejci. I tried enabling this feature, but still seeing the same issue
```c
   struct ly_ctx* ctx = ly_ctx_new(TEST"/models/ietf");   
   const struct lys_module * mm1 = ly_ctx_load_module(ctx, "ietf-system",NULL);
   assert_ptr_not_equal(mm1, NULL);
   int rs = lys_features_enable(mm1,"authentication"); //enable feature
   assert_int_equal(rs,0);

 struct lyd_node *root = lyd_new_path(NULL, ctx, "/ietf-system:system/authentication/user[name='testuser']", "", LYD_ANYDATA_SXML, 0); 
 assert_ptr_not_equal(root, NULL);
 lyd_print_mem(&buf, root,LYD_XML, LYP_FORMAT|LYP_KEEPEMPTYCONT|LYP_WD_ALL));
 printf("\n%s\n",buf); // so far no issues

 int re=lyd_validate(&root, LYD_OPT_CONFIG|LYD_OPT_NOAUTODEL, NULL); //getting error here
 assert_int_equal(re,0);
```
