### ISSUE TITLE
Leafref path does not use the yang prefix

### ISSUE THREAD

**Issue by arun11299** [CESNET/libyang#306]
Hi,
The path in `lys_type_info_lref` does not make use of the yang (imported) module prefix. It is always (at-least in the non collision cases) making use of the module name instead of the prefix.  Is it the intended behaviour? 

I am not really sure whether it is an issue or not because reading the RFC (rfc6020#section-9.4.4) also appears to be ambiguous to me.

Thanks.

**Comment by michalvasko** [comment]
Hi,
I am not sure why are you digging through the code, if you have a non-working use-case, please start an issue. This is an internal optimization of ours, when we convert every prefix into the corresponding module name during parsing and then always work with the module name. You will find in the YANG grammar that a `prefix` is used, not a module name.

Regards,
Michal

**Comment by arun11299** [comment]
Perhaps I did not put the issue clearly. We are using this xpath (i.e the leafref path) for some external validation. It would have been better if the path was what was originally there in the yang file. 
So:
1) Is there any way to get the orginal leafref path which is there in the yang file ?

2) How are collisions handled (Section 7.1.4). I am sure it is handled correctly, but want to know how and how would the path look in such case.

Thanks.

**Comment by michalvasko** [comment]
Hi,
1.) Yeah, by converting the path back to original by calling `transform_json2xml`. We use it when printing the path back to a model in either YANG or YIN format, However, it is not a public function. Also, if you require exactly the same path then the information is lost, we create the prefixes based on each model own prefix when converting it back.

2.) This is actually one of the reasons we use model names instead of prefixes. A good practice and actually a requirement is having each model its own unique name. No such thing can be said about prefixes, you can define one prefix for model `A` import in model `B` and another for model `A` import in model `C`.

Regards,
Michal
