### ISSUE TITLE
XPath for accessing an item's position within a list

### ISSUE THREAD

**Issue by jktjkt** [CESNET/libyang#316]
As a minimal testcase, I'm trying to write a ``must`` constraint requiring that each item in a list has a certain number which depends on its position. My understanding of [RFC6087](https://tools.ietf.org/html/rfc6087#section-4.5) is that I should use ``ordered-by "user"`` for that.

It seems that ``must`` is ignored for a ``list`` because I can import the following data:

```xml
<?xml version='1.0' encoding='UTF-8'?>
<foo xmlns="http://example.org/test/jkt/1">
<seq>
<item><n>2</n></item>
<item><n>5</n></item>
</seq>
</foo>
```
to a module that uses this schema:
```yang
module test-jkt-1 {
  namespace "http://example.org/test/jkt/1";
  prefix "tj1";

  container seq {

    list item {
      ordered-by "user";
      key "n";
      leaf n {
        type uint8;
        must "false()";
      }
      must "n = position()";
      must "false";
      must "false()";
    }

  }
}
```

When I move the ``must`` constraints out of the ``list item`` and into the enclosing ``container seq``, they are now getting evaluated, but I cannot come up with an XPath which implements what I want.

On the other hand, if the list looks like this, where ``chan:optical-channel`` is a ``grouping`` imported from another module, the ``must`` constraints take effect:

```yang
container roadm {
    container channel-plan {
      list channel {
        uses chan:optical-channel;
        ordered-by "user";
        must "channel-width = 100.0" {
          error-message "Channel bandwidth must be 100 GHz";
        }
        key "center-frequency";
      }
    }
}
```

With the above in place, how do I check an element's position within a list, though? I've tried various bits, but it seems that constructs such as ``must "number(/roadm/channel-plan/channel/center-frequency[position()]/text()) = 192.1";`` are evaluated just for ``position()`` equal to ``1``. This is interesting because when I added some debug output to ``xpath_position()`` in ``src/xpath.c``, I see that it kept returning values 1, 2, 3 when I'm inserting three items into the list.

Furthermore, `` must "number(/roadm/channel-plan/channel[2]/center-frequency/text()) = 192.2";`` works as expected if it's given within the ``list channel`` statement, but it rejects data if it's defined at its parent, the ``container channel-plan``.

**Comment by michalvasko** [comment]
Hi,
it seems to me everything works as expected, but I may be wrong, let's look into it in detail.

Your first example is wrong because the data have a container `foo`, which is not in your model. Also, must expression `false` is wrong, but since XPath expressions are not required to be correct (don't blame us, it was discussed on the *netmod* mailing list), it is printed just as a warning. So, in future I suggest you always use *verbose* verbosity in *yanglint* and use `-s` when loading data to avoid silent errors.

The only problem in your second example is evaluating `position()` only when it equals `1`, if I understand it correctly. Now, this is quite confusing stuff, so I will try to explain how I understand it, but I may be wrong. I tried your first example model with having all must expressions removed but `n == position()`. I changed the data to have 2 list instances with the first one having `n` `1`, the second `n` `2`. Validation still failed on the second instance, I believe correctly. `position()` returns the **context position** (that is a formal term with exact definition, be careful), written [here](https://www.w3.org/TR/xpath/#function-position). When evaluating the `must` expression on the second instance, the XPath **context node** (again a formal term) is the second list instance. I cannot cite any text in case of determining **context size** and **context position** because it is not explicitly defined in YANG 1.1 RFC. Still, the whole context at the beginning of any XPath evaluation is just the **context node** so the **context size** is 1, which then restricts **context position** to being 1, too (citing [Introduction](https://www.w3.org/TR/xpath/#section-Introduction): *The context position is always less than or equal to the context size.*). To summarize, when the must expression is defined for a list, during evaluation the other list instances are not in the XPath context together but separately.

To move forward, one must focus on another sentence from the XPath Introduction: *only predicates change the context position and context size*. The consequence of this sentence in my understanding is that it basically makes no sense to use `position()` or `last()` elsewhere than in a predicate. So, I used a modified version of your model
```yang
module test-jkt-1 {
  namespace "http://example.org/test/jkt/1";
  prefix "tj1";

  container seq {
    must "count(item[position() = n]) = 2";

    list item {
      ordered-by "user";
      key "n";
      leaf n {
        type uint8;
      }
    }

  }
}
```
and the data
```xml
<?xml version='1.0' encoding='UTF-8'?>
<seq xmlns="http://example.org/test/jkt/1">
    <item>
      <n>1</n>
    </item>
    <item>
      <n>2</n>
    </item>
    <item>
      <n>4</n>
    </item>
</seq>
```

The must expression will select all the list instances, whose `n` equals to their position. These data validated successfully and when looking into XPath execution with debugger, all the values were as I expected them to be.

Regards,
Michal

**Comment by jktjkt** [comment]
Thanks for explaining the *context position*, I thought that it was merely a pointer to the entire document. Now I understand that.

However, I'm getting weird results with ``count()``:

```yang
module test-jkt-1 {
  namespace "http://example.org/test/jkt/1";
  prefix "tj1";

  container seq {
    must "count(item) = 4";

    list item {
      ordered-by "user";
      key "n";
      leaf n {
        type uint8;
      }
    }

  }
}
```
```xml
<?xml version='1.0' encoding='UTF-8'?>
<seq xmlns="http://example.org/test/jkt/1">
    <item>
      <n>1</n>
    </item>
    <item>
      <n>2</n>
    </item>
    <item>
      <n>3</n>
    </item>
    <item>
      <n>4</n>
    </item>
</seq>
```

Validation of that fails. I'm getting three calls to ``xpath_count`` in total, the first one returns ``4`` as expected, whereas the other two remaining are both called with an empty set, and therefore return ``0``. If I move this ``must`` from the ``container seq`` to the ``list item {}`` block, it starts working, and it's called eight times in total (I'm testing via ``sysrepocfg --import``).

**Comment by michalvasko** [comment]
Hi,
it works just fine in `yanglint`, but it failed in `sysrepocfg` import for me as well. Please, try it always in `yanglint` (it takes a second) and if it works, create the issue in *sysrepo*. XPath implementation in *libyang* should be quite robust. Anyway, I am looking into the problem.

Regards,
Michal

**Comment by jktjkt** [comment]
Thanks for a quick fix. I was able to achieve what I wanted to.

There's one downside -- because that validation is performed at the level of the whole list (I've been using ``count(/foo/channel[position() = center-frequency * 10 - 1920 + 1]) = count(/foo/channel)`` right now), libyang is not able to point to a list item which actually violates this rule. I was struggling a bit with generalizing this into a "let's switch to ``ordered-by user`` and use the ``preceding-sibling::`` XPath axis", but that one is not supported by libyang.

So in the end, I went back to the drawing board. What I *actually* want is not to enforce a particular order. My list is a list of items with a "central frequency" and "spectral width", and I want to ensure that there are no overlaps. This "one-liner" did the trick :):

```yang
must "count(/foo/channel[
  (center-frequency < current()/center-frequency) and
  (center-frequency * 1000 + (channel-width div 2) > current()/center-frequency * 1000 - (current()/channel-width div 2))
  ]) = 0"
```

Thanks for your help and for teaching me about ``yanglint``, it's definitely useful. There's no bug here, closing.
