### ISSUE TITLE
libyang failed to parse del-instid-leaf message

### ISSUE THREAD

**Issue by fanchanghu** [CESNET/libyang#339]
Hi,
When trying to delete an instance-identifier leaf by `edit-config`, libyang failed to parse the message.
this issue can also be reproduced with `yanglint`:
```
> 
> add ietf-netconf.yang 
> add  Test.yang 
> data d2.xml
libyang[0]: Unexpected end of input data.
libyang[0]: Unexpected character(s) '
libyang[0]: Invalid value "" in "f2" element. (path: /test:C1/f2)
Failed to parse data.
> 
```
Test.yang
```
module test{
	namespace "urn:it:params:xml:ns:yang:test";
	prefix "t";
	
	container C1{
		leaf f1{type string;}
		leaf f2{type instance-identifier;}
	}
}
```

d2.xml
```
<C1 xmlns="urn:it:params:xml:ns:yang:test" xmlns:nc="urn:ietf:params:xml:ns:netconf:base:1.0"><f2 nc:operation="delete"></f2></C1>
```

**Comment by rkrejci** [comment]
@fanchanghu, instead of hiding, I prefer to avoid unnecessary processing and stop it when the value is empty - I'm fixing it in commit 034cb106 (currently fix_emptyinstid branch). However, it does not seem as a complete fix: 
@michalvasko, please look at this - `check_instid_ext_dep()` is not documented and it is unclear to me why it is not part of `resolve_instid()`. My fix covers only the empty value, but in case of invalid value (refering non-existing node) it still prints error from check_instid_ext_dep() and then continue with resolve_instid().

**Comment by fanchanghu** [comment]
Agree to fix it in `resolve_instid()`, my fix is something like a workaround, in fact, it confused me that `check_instid_ext_dep()` return `1` even if the path is illegal.

**Comment by michalvasko** [comment]
Hi,
it should work now in the `devel` branch.

Regards,
Michal
