### ISSUE TITLE
no null pointer check in lyd_merge_node_equal  in file tree_data.c

### ISSUE THREAD

**Issue by ustcpxy** [CESNET/libyang#383]
there is no null pointer check in below code snippets: (tree_data.c:1970)
```
            if (!child1 || !child2 || ((child1_sch ? child1_sch : child1->schema) != child2->schema)
                    || strcmp(((struct lyd_node_leaf_list *)child1)->value_str, ((struct lyd_node_leaf_list *)child2)->value_str)) {
                break;
            }
```
the child1 or child2 's value_str may be NULL.

**Comment by rkrejci** [comment]
Do you have some use case where `value_str` is NULL? I believe it should be always at least `""`.

**Comment by ustcpxy** [comment]
yes, you are right. only if the child1 is a leaf node, the value_str is NON-NULL.
but there is another case, if the child1 is a container node, the value_str is NULL.

below is the yang snippets for example:
list l1
{
container c1
{
}
}

**Comment by rkrejci** [comment]
But there are tests that make sure that there are keys, the for loop is limited by the number of the keys and keys are always the first children.
Do you have some test case (running code) by which I could raise an error?

**Comment by ustcpxy** [comment]
below is my running code snippets:

`
    char * subtree_xpath="/l1/c1"; // for example
    sr_node_t *subtrees = NULL;
    size_t count = 0;
    rc = sr_get_subtrees(np_sess->srs, subtree_xpath, SR_GET_SUBTREE_DEFAULT, &subtrees, &count);
    if (SR_ERR_NOT_FOUND == rc)
    {
        /* it's ok, model without data */
        return 0;
    }
    else if (SR_ERR_OK != rc)
    {
        ERR("Getting subtree (%s) from sysrepo failed (%s).", subtree_xpath, sr_strerror(rc));
        if (NULL != subtrees) {
            sr_free_trees(subtrees, count);
        }
        return -1;
    }

    if (NULL != subtrees)
    {
        sr_tree_to_dt(np2srv.ly_ctx, subtrees, subtree_xpath, false, root);

        for (size_t i = 1; i < count; ++i)
        {
            struct lyd_node *tmp_root = NULL;
            sr_tree_to_dt(np2srv.ly_ctx, subtrees+i, subtree_xpath, false, &tmp_root);
            lyd_merge(*root, tmp_root, LYD_OPT_DESTRUCT);
        }

        sr_free_trees(subtrees, count);
    }
    return 0;
`
there are many instances of list l1 in sysrepo datastore, so I need merge them into one lyd tree.
but the sr_tree does not contain the list key. 
it means the first child of the l1 is c1 in root data tree (*root); it is a container, not a list key.

**Comment by michalvasko** [comment]
Hi,
the documentation for `lyd_merge()` states that both `target` and `source` must be valid, which is not true in your case, there are no keys for the lists. However, the problem is not just in that, what exactly do you expect to have after the final merge? All those separate lists each with its container? *libyang* is unable to perform this because it does not know whether the lists are different instances because they do not have the keys. So, the only result you could theoretically get is only the last list instance with its container, all the previous ones would get "merged out", but it makes no sense to implement this and you must stick to what the documentation says.

Regards,
Michal

**Comment by ustcpxy** [comment]
Hi Michal,
Thanks. I got it.
