### ISSUE TITLE
Consistency check of leafref features of imported modules lead to module installation failure.

### ISSUE THREAD

**Issue by frimpler** [CESNET/libyang#395]
Hi, 

please have a look at this commit: https://github.com/frimpler/libyang/commit/8867006092abd3094e4a6804dcda640562b9ff9f
The new/enhanced tests address issues with feature consistency checks of leafrefs, again, and are in fact an aftermath of the correction made for this pullrequest:
https://github.com/CESNET/libyang/pull/361

Problem Description:
---------------------------
As has already been stated in the mentioned pull request, modules cannot be installed because leafrefs and their feature consistency cannot be resolved correctly. 

Because the available solution didn't work any more when in different module installation context (-> installation of leafref_w_feature1-mod4), I made a deeper investigation in order to find out what's wrong. The reason, why it didn't work, is that none of the schema nodes needed to be implemented in this context (in fact, for test purposes, the module in installation process has no schema nodes at all). This means on the other hand, that none of the augments has to be applied to any imported schema node, which in turn, challenges the leafref resolution, because it needs somehow the completely augmented tree.
When I became aware of this fact, it was clear, that the test case "test_leafref_w_feature1" needed to check more strictly, that imported modules were not implemented (- but unfortunately, they were!)

I think, that (probably not only) the checks for leafrefs and their features should either 
- not be made as long as the target modules are not implemented or
- be done, somehow using temporary contexts/modules, that can be thrown away afterwards.

Regards,
Frank

**Comment by michalvasko** [comment]
Hi Frank,
thanks for the use-case. The referenced commit should fix the problem you encountered, there actually aready was a (quite complex) mechanism for handling these complicated cases with augments, leafrefs and module implemented flags. So, only some fine-tuning was needed for it to work for cases when no module in question is implemented.

Regarding your tests, we would gladly merge them into *libyang* if you create a pull request, but we ahve 2 requests. Please, adhere to our coding style so that the whole code is easily readable. More importantly, the loops you added where you test module implemented flags are not correct. You can keep the test there, but there are always modules that should be implemented. It is always the module that is loaded explicitly (in your case by calling `lys_parse_path()`).

So, in the test `test_leafref_w_feature1` the module `leafref_w_feature1-mod3` will be implemented. However, having an augment, the target node module must also be implemented - `leafref_w_feature1-mod1` - and also, since using an implemented leafref pointing to another module - `leafref_w_feature2-mod1` - that one is also implemented. In the other test `test_leafref_w_feature3` only the first parsed module will be implemented - `leafref_w_feature4-mod1`. It does not have any data, true, but to be consistent and forbid implementing the same module in another revision, the flag will be set.

Regards,
Michal

**Comment by frimpler** [comment]
Hi Michal,

concerning the coding style I don't know what you have in mind. The lines are more or less 1:1 copied from the existing tests, so please tell me what exactly you bothers.

The more important thing:
---------------------------------
The checks at the end of the tests reflect what rfc7895 states in the description of the enum "implement" of leaf "conformance-type":
..."Indicates that the server implements one or more protocol-accessible objects defined in the YANG module identified in this entry. This includes deviation statements defined in the module."...
 
I have of course seen in the code, that the implement flag of the initial module will be set to 1. But this leads IMHO to the error, that when leafref_w_feature1-mod3 will be installed, all other modules become implemented, too. When I read rfc7950, "5.6.5.  Implementing a Module", I think, that it is wrong to do it that way: None of the augments will be applied to the mod3, which is in fact also not "implemented".

Regards,
Frank

**Comment by michalvasko** [comment]
Hi Frank,
there are some minor coding style differences that do not matter, but please, remove the spaces from the inside of parenthesis and add around operators at least. Example `for ( i=0; i<ctx->models.used; i++ ) {` -> `for (i = 0; i < ctx->models.used; i++) {`.

It seems fairly clear to me, but let's see. We start with having implemented the module `leafref_w_feature1-mod3`. Now, it must also implement `leafref_w_feature1-mod1` because there is an implemented augment that targets nodes in this module. Otherwise you will be left with unimplemented `cont1` and an implemented child `cont2` which makes no sense and would be unusable. However, I can simply reference the RFC here, [3rd paragraph](https://tools.ietf.org/html/rfc7950#section-5.6.5). The exact same and argumentation applies for module `leafref_w_feature1-mod2`, its typedef gets used in an implemented node so the RFC tells us clearly what to do, we must make the `path` statement's target node's module implemented.

Regards,
Michal

**Comment by frimpler** [comment]
Ok. 
So the difference in installation of mod3 and mod4 is that mod3 has a path in it, which points to another module (mod1), but mod4 hasn't. And therefore the test_leafref_w_feature1 leaves all 3 modules as "implemented" and test_leafref_w_feature3 only mod4. Am I correct?

**Comment by michalvasko** [comment]
Yeah, you are. `mod3` has both an augment to `mod1` and a path to `mod2`, that is why all three are implemented.

Regards,
Michal

**Comment by frimpler** [comment]
ok, thanx. Test case pull request comes on Thursday.
