### ISSUE TITLE
yanglint assert fail when there are `when` statement defined in augment for action 

### ISSUE THREAD

**Issue by fanchanghu** [CESNET/libyang#399]
Hi,
yanglint assert fail with following steps:
```
> add choice.yang 
> add choice2.yang 
> data -t rpc -r r.xml  d.xml 
yanglint: /root/svn/nfoam/libyang/src/tree_data.c:6597: lyd_defaults_add_unres: Assertion `data_tree_parent->child->prev == msg_sibling' failed.
```

and, I first occured this issue in netopeer2-cli, the cli exit as `Segmentation fault ` with following steps:
1, install choice.yang and choice2.yang 
2, edit-config --target running --config=r.xml
3, user-rpc --content d.xml

however, I'm not sure these are the same issues.

[tmp.zip](https://github.com/CESNET/libyang/files/1498415/tmp.zip)

**Comment by fanchanghu** [comment]
hi
I'm sorry, the file r.xml should be like this:
```
<choice xmlns="http://example.net/zte/choice">
	<f1>2</f1>
</choice>
```
the value should not match the when statement.

**Comment by michalvasko** [comment]
Hi,
now this is a really nasty use-case, which we have never taken into consideration. You are essentially executing an action that is currently not supported because it is condition by a false when. If you update *libnetconf2* and *libyang* `devel` branches it should not crash any more (neither in *yanglint* nor *sysrepo*). However, I am not particularly convinced that I have covered all the use cases of some critical schema part being removed because of when, so feel free to test it further, thanks.

Regards,
Michal
