### ISSUE TITLE
Question: adding tpdf to a module by hand

### ISSUE THREAD

**Issue by lajdzsi** [CESNET/libyang#400]
Hi.
I'm trying to build a schema module (lys_module*) by hand, and when creating my first node (specifically a lys_node_leaf* now) , I could only avoid segfaults by creating a lys_tpdf* for the lys_type.der of the node, and it does create the module with that one leaf of my custom type, but the module does not include the typedef itself, when I print it out. What could I have overlooked? I set tpdf->module to be my generated module, and set the type.der to the typedef, is there any other connection that is necessary for the typedef statement to be included in the module?
Thanks in advance.

**Comment by michalvasko** [comment]
Hi,
I will start by giving you a friendly advice, do not attempt to build `struct lys_module` by hand, otherwise you will likely encounter a lot of instances of such weird behaviour. I will help you this time, but it is also the last time. Look at line 922 in `tree_schema.h` and at the whole `yang_types.c`. Everything should be clear to you then.

Regards,
Michal
