### ISSUE TITLE
Yanglint. Data validation. Error line.

### ISSUE THREAD

**Issue by aksenofontova** [CESNET/libyang#403]
Hello, libyang Team.

Could you help me, how i can get information about which line data error occurred.
It's not enaught in console output.
Example.
> data -t config data_vlan.xml
libyang[0]: Invalid (mixed names) opening (dhcpConfifg) and closing (dhcpConfig) element tags. (path: /my-vlan:vlan/dhcpConfifg)
Failed to parse data.

Thank you, for your work.

**Comment by michalvasko** [comment]
Hi,
we were initially thinking about printing lines on which an error occurred but decided against it in the end because it would be too much work for little gain. So, I suggest you use your favourite text editor or something similar to find the element with typo (`dhcpConfifg`), *yanglint* will not provide any more information.

Reagrds,
Michal

**Comment by aksenofontova** [comment]
Hi, Michal

Thank you for answering.
In the netopeer2 in the rpc-reply this information will not be present too?

Anna.

**Comment by michalvasko** [comment]
Hi Anna,
like I said, no line information is tracked anywhere in *libyang*, so no, it will not be present.

Regards,
Michal
