### ISSUE TITLE
Wrong path reported for error in default value

### ISSUE THREAD

**Issue by iwanb** [CESNET/libyang#416]
Given a leaf with an invalid default value, e.g.:

```
module a {
  namespace "urn:a";
  prefix a_mod;

  leaf my-leaf {
    type uint32 {
      range "1..255";
    }
    default "0";
  }
}
```

The error is reported but it is shown as coming from `/a:fake-default` instead of `/a:my-leaf`.

```
yanglint --verbose a.yang 
err : Value "0" does not satisfy the constraint "1..255" (range, length, or pattern). (/a:fake-default)
err : Module "a" parsing failed.
```

**Comment by michalvasko** [comment]
Hi,
this is intentional. Changing the path to be always correct would require some fairly messy code to be added and we decided it is simply not worth it. Anyway, this is only a problem of invalid default values in schemas (because it uses data validator and must therefore create a fake data node).

Regards,
Michal

**Comment by iwanb** [comment]
Hi,

Ok, thank you. I am trying to find where the error is coming from in a large yang module (100K lines...), do you know any trick to narrow it down?
Also, wouldn't it make sense to not report the /a:fake-default path if it is known to be wrong?

Regards,
Iwan

**Comment by michalvasko** [comment]
Hi,
you always see the exact constraint and the default value, which should make it fairly easy to find it in any file (unless you have several types with similar constraints and defaults, does not make sense). It is reported precisely because it is not known that it is wrong. The function that does the printing does not have this information, it would have to be passed down from functions higher up which is what we would like to avoid.

Regards,
Michal

**Comment by iwanb** [comment]
Thank you, unfortunately there are hundreds of types with that constraint, and hundreds of types/leaves with that default. (That might indicate some design issues but well...)
I did find the issue by going through them but it takes quite some time.

So actually any extra information which could be added to the error message would be useful (like the type being checked, the type of constraint, or any other context).
If there is something like that which would be easy to add, that would be great!
But I can for sure imagine the complexity of tracking these things.

In any case I will track the changes to these Yang files as they are done it should not be a problem to find the culprit anymore.

Best regards,
Iwan

**Comment by michalvasko** [comment]
Hi Iwan,
oh fine, I will try to look at it and think about how to improve it once I finish my current work.

Regards,
Michal

**Comment by iwanb** [comment]
Great!
Maybe logging extra information in the calling functions when an error is detected would be useful?
(As a kind of stacktrace.)
It would add quite a lot of boilerplate though.

I could actually use gdb next time to have a true stacktrace.

Iwan

**Comment by michalvasko** [comment]
Hi Iwan,
it was actually easier than I thought and you should now always be able to uniquely identify the problem node/typedef.

Regards,
Michal
