### ISSUE TITLE
Anchored regex patterns from openconfig models are rejected by libyang

### ISSUE THREAD

**Issue by jeroen-dhollander** [CESNET/libyang#422]
Hey,

In the openconfig models, the regex patterns are usually anchored (i.e. they start with `<` and end with `$`).

For example [openconfig-yang-types.yang](https://github.com/openconfig/public/blob/master/release/models/types/openconfig-yang-types.yang) contains this:
```
  typedef dotted-quad {
    type string {
      pattern '^(([0-9]|[1-9][0-9]|1[0-9][0-9]|2[0-4][0-9]|'       +
              '25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9][0-9]|2[0-4]' +
              '[0-9]|25[0-5])$';
    }
    description
      "An unsigned 32-bit integer expressed as a dotted quad. The
      format is four octets written as decimal numbers separated
      with a period character.";
  }
```

This used to be accepted by libyang, but it is no longer accepted since version 0.14.34 .
This is due to the bugfix for [issue 374](https://github.com/CESNET/libyang/issues/374), which causes all `$` in the pattern to be escaped.

Note: OpenConfig seems to be very consistent in that they anchor every pattern I can find in their modules.

**Comment by jeroen-dhollander** [comment]
Hi,

Thanks for pointing that out. I will raise a bug for the openconfig team, hopefully they can update their YANG modules.

Thanks,

Jeroen

**Comment by YohanPipereau** [comment]
It seems like openconfig has added an extension in https://github.com/openconfig/public/blob/master/release/models/openconfig-extensions.yang#L100 to let people detect which type of regex is used.
Opendaylight seems to be willing to update their YANG parser https://jira.opendaylight.org/browse/YANGTOOLS-1005 . 
I am just asking in case, Do you have a plan to support POSIX regex in a near future ?

**Comment by michalvasko** [comment]
Hi,
I am afraid we will not support this. Mainly because the extension changes meaning of standard YANG statements (`pattern` argument changes meaning to POSIX regex), which is not the way extensions should be used. If, for example, the extension would define a new pattern type and it would be used like
```yang
leaf l {
  type string;
  os-ext:posix-pattern "$abc^";
}
```
implementing support for this in *libyang* would be fairly simple.

We also do not really understand why openconfig needed to add another regex type since you can express same expressions in both regex flavors.

Regards,
Michal

**Comment by YohanPipereau** [comment]
Thanks for the informations. We'll avoid using openconfig YANG models until they are RFC compliant then .
