### ISSUE TITLE
Cannot check leafref if-feature consistency because of an unresolved augment

### ISSUE THREAD

**Issue by abhikeshav** [CESNET/libyang#442]
```yang
module g
{
    namespace "urn:g";
    prefix g;

    extension ac
    {
        argument "name";
    }

    container x
    {
      leaf name
      {
        type string;
      }

      grouping test-grouping
      {
         g:ac test;
      }

      uses test-grouping
      {
          augment "test"
          {
             leaf g
             {
                type leafref
                {
                  path "/x/name";
                }
             }
          }
       }
    }
}

```
Seeing the below error. Any idea if this is expected? Is any workaround possible?
```
./yanglint
> add /models/g.yang 
libyang[0]: Cannot check leafref "/x/name" if-feature consistency because of an unresolved augment. (/g:x/{augment}[test])
libyang[0]: Module "g" parsing failed.
```

**Comment by rkrejci** [comment]
Hi, augmenting extension is not supported. Specification is quite vague about the extension (which is understandable since extension can be actually anything) and it does not say anything about augmenting extensions. It could be done with some effort, but there are some issues to resolve. The main problem I see here is addressing. Extension name (argument's value in general) does not share namespace with standard YANG identifiers (RFC 7950, 6.2.1) so actually this is valid, but breaks the addressing of the uses's augment:
```
grouping test-grouping
      {
         leaf test { type string; }
         g:ac test
         {
           input
           {
           }
         }
      }
```

**Comment by abhikeshav** [comment]
Thanks. Is it possible to have some clarity in the error or does the error need to be checked elsewhere instead of `check_leafref_features()`? Currently, the error message is a bit cryptic.

```
libyang[0]: Cannot check leafref ... if-feature consistency because of an unresolved augment. (path: ...)
```

**Comment by michalvasko** [comment]
Fair enough, I will take a look it and will see what I can do.

Regards,
Michal

**Comment by michalvasko** [comment]
The proper error should now be displayed.

Regards,
Michal

**Comment by abhikeshav** [comment]
Thanks, @michalvasko !
