### ISSUE TITLE
Backslash in quote causes error?

### ISSUE THREAD

**Issue by abhikeshav** [CESNET/libyang#450]
Currently, the below yang snippet causes the below error in `master` branch:
```yang
  extension a {
    description
      "example
          'this is a wrapped \
           line in a text block'        
      ";
  }
```
`libyang` throws the below error and fails to parse the module
```shell
libyang[3]: DICT: inserting "a" with collision 
libyang[0]: Invalid keyword "example
          'this is a wrapped \
           line in a text block'        
      "".
libyang[0]: Module "x" parsing failed.
```

But `pyang 1.7.3` only shows the below warning.
```shell
~>pyang ~/Downloads/x.yang
/Downloads/x.yang:114: warning: the escape sequence "\
" is unsafe in double quoted strings - pass the flag --lax-quote-checks to avoid this warning
```

Should libyang also show a warning message instead of erroring?

**Comment by michalvasko** [comment]
Hi,
libyang error is not very specific, but that is because of the parser we use. However, it should not be changed into a warning, *pyang* should rather change the warning into an error. Referencing [the 3rd paragraph](https://tools.ietf.org/html/rfc7950#page-46) and then the one-line sentence "The backslash MUST NOT be followed by any other character.", it is quite clear.

Just a note, `\n` (encoded as `92` `110`) would be valid but what you have is `\NL` (encoded as `92` `10`) as seen in an [ASCII table](http://www.asciitable.com/).

Regards,
Michal

**Comment by abhikeshav** [comment]
Thanks, @michalvasko !
