### ISSUE TITLE
lyd_new_leaf overwrites node in choice

### ISSUE THREAD

**Issue by lukasmacko** [CESNET/libyang#46]
If a leaf from diffrent choice alternative is added it overwrites previously added node and validation passes.

```C
#include <stdio.h>
#include <stdlib.h>
#include <libyang/libyang.h>

int main(int argc, char **argv)
{
   struct ly_ctx *ctx = ly_ctx_new(".");
   const struct lys_module *module =ly_ctx_load_module(ctx, "test-module", NULL);
   struct lyd_node *root = NULL;
   root = lyd_new(NULL, module, "transfer");
   lyd_new_leaf(root, module, "interval", "15");
   lyd_new_leaf(root, module, "daily", ""); /*ADDING THIS NODE SHOULD CAUSE VALIDATION ERR*/
   if (0 == lyd_validate(&root, LYD_OPT_STRICT | LYD_OPT_NOAUTODEL |LYD_OPT_CONFIG)) {
        puts("Validation passes, but it should fail");
   }

   FILE *out = fopen("out", "w");
   lyd_print_file(out, root, LYD_XML, LYP_FORMAT);
   lyd_free(root);
   fclose(out);
   ly_ctx_destroy(ctx, NULL);
   return 0;
}
```
[test-module](https://github.com/sysrepo/sysrepo/blob/master/tests/data/yang/test-module.yin) needed by code snippet.

**Comment by rkrejci** [comment]
This seems to be the expected behavior. [RFC 6020](https://tools.ietf.org/html/rfc6020#section-7.9.6) says that creating a node from a case causes automatic delete of nodes from other case.

libyang reports validation error when it parses complete data store with nodes from multiple cases - because there is no clue what node (case) is replacement for another one. When using `lyd_new` or `lyd_insert` functions, it is clear what is the replacement, so the last node wins.

The 'LYD_OPT_NOAUTODEL' in `lyd_validate()` applies only to false when-stmt conditions. The choice's autodelete is performed when manipulating with the tree, not when the tree is being validated.
