### ISSUE TITLE
When condition with prefixed value failed

### ISSUE THREAD

**Issue by frimpler** [CESNET/libyang#481]
Hi,

with the testcase test_when_value_prefix() in this commit https://github.com/frimpler/libyang/commit/a9451c16ab9c82ae8e64b915f269377365ee0ecc an issue of the XPATH evaluator is triggered.

### Description
When a when condition is evaluated which contains a prefixed identityref value and this identityref comes from an augmentig module the evaluated expression looks like "identityref = prefix:identityref" and this fails of course. The reason is that on the node side of the equality expression the value is assumed to come from the augmented module (resulting in no prefix) instead of the augmenting module.

### Proposed Solution

The proposed solution in xpath.c (https://github.com/frimpler/libyang/commit/9b58e81db7a8f8ffe9b8a703a58842f25d78f466) uses the module of the actual node to determine the prefix for the value.

**Comment by rkrejci** [comment]
Hi, checking identity via `=` is a bad idea. By `=`, you are checking for string equivalence. Instead, use `derived-from()` or `deri.ed-from-or-self()` functions to check identityref values.

**Comment by rkrejci** [comment]
So what is the problem with `derived-from-or-self()`? The `base` of identities works similarly to OOP classes, so if there are identities derived from your `inner-indicator`, they should be just specialised inner-indicators, but still an inner-indicator. And if there are no derived identities, the `-or-self` will work for you to match only the `inner-indicator` value.

It was already discussed in IETF mailing lists, so I'm pretty sure that a) it is not prohibited to use `=` in this case, but b) it is mostly useless and it does not have the effect you want since it really checks the string equivalence (by XPath spec).

**Comment by frimpler** [comment]
There is e.g. the standardized module ietf-routing which is using exactly the described pattern:
...
container routing-protocols {
   ...
   leaf type {
      type identityref {
         base routing-protocol;
      }
      ...
      container static-routes {
         when "../type='rt:static'";
      }
}

**Comment by rkrejci** [comment]
Can you provide a link? I see `derived-from-or-self()` in RFCs:
* https://tools.ietf.org/html/rfc8022
* https://tools.ietf.org/html/rfc8349

**Comment by frimpler** [comment]
Currently we are using revision 2015-10-16 of ietf-routing which uses the equality expression. And in our model there are some more modules. As far as I can see quickly
ietf-x509-cert-to-name@2014-05-06
bbf-fast-base@2017-10-26
bbf-melt-base@2016-07-18
bbf-selt-base@2016-07-18
I don't know if there are newer revisions avoiding the '='.

**Comment by rkrejci** [comment]
I've dive more into the issue.
1. schema authors should use `derived-from()` or `derived-from-or-self()` functions to check identityref values in XPath expressions, see [this thread](https://www.ietf.org/mail-archive/web/yang-doctors/current/msg00886.html). Equality check is a bad idea and it really complicates a lot of things.
2. equality comparison (`=`) was used widely so far, so the tools should try to do their best to correctly compare identities even with `=`. libyang does it and I was wrong, supposing that it is just a silly string comparison. But it is not perfect and this issue is such a case.
3. I'm afraid that the proposed solution is not correct. Or maybe it is correct, but I'm afraid about the side effects of changing `local_mod` when calling `cast_string_elem()`. I believe that the problem is elsewhere, in a code which does not reflect changes in storing identityref values. I'm going to prepare pull request using Frank's test case, please check it then, feedback welcomed. Anyway, because of my limited knowledge of the xpath implementation, I want to wait with merge for @michalvasko (currently on vacation, should be back at the end of April).

**Comment by frimpler** [comment]
Hi Radek,

Thank you for re-considering our argumentation. 
I also wanted say, that we are usually not free to change modules even if we understand your argumentation. 
Concerning the proposed solution: we do our best to provide a way to ship around problems, but finally you decide, whether the way we did it matches your concepts. However, it's always the test case which formulates our request.

Best regards,
Frank

**Comment by rkrejci** [comment]
Yes, I understand. Regarding the solution, what if the schema is written this way (modified test case you provide):
```
augment "/wvp:outer" {
  container inner {
    when "../wvp:indicator='inner-indicator'";
      leaf text {
        type string;
      }
   }
}
```
The change is in string to compare, here it is without prefix. So far, this was working (with you test data). But with your as well as my fix it is not working anymore and actually I don't know how to make it working. As I wrote, from XPath point of view, this is a string comparison. We can do something with the string on the left side, since it is evaluated. But `inner-indicator` on the right side is just a string and it is taken into comparison as it is. In case there is a prefix, we do a replacement when parsing schema to have module name (internally used to identify schema) instead of prefix. But in this case we are not able to detect that it is something else than just string comparison.

So my question is if the limitation that the identity value in xpath expression is always prefixed works for you.
