### ISSUE TITLE
regex with backslash errors out as "Invalid Keyword"

### ISSUE THREAD

**Issue by aniruddha-a** [CESNET/libyang#491]
One of the `leaf` in my yang, had a regex _pattern_ [statement] that contained a backslash escape and I got an `Invalid keyword` error. To check if it was due to the regex, I tried to pass the same/similar value to `yangre` and I can see the error:

     $ yangre -p '"[0-1](.[1-3])+"' "1.2"
     $ echo $?
     0
     $ yangre -p '"[0-1](\.[1-3])+"' "1.2"    # <-- Note explicit escape of DOT
     yangre error: Invalid keyword "[0-1](\.[1-3])+"".

the regex here is a sample one, but its valid PCRE.

**Comment by michalvasko** [comment]
Hi,
so yet again, this error is due to YANG encoding ([this](https://tools.ietf.org/html/rfc7950#page-46)). Contrary to the section I referenced, you have used `\` followed by a `.` which is illegal. It should be `\\.` instead. To avoid this confusion, modules should always enclose patterns in `'` and not `"`, then `\` is correctly interpreted as `\` and not a special character.

I think if you searched issues a bit, you would have found a similar one, there were at least 3 other people having the same problems.

Regards,
Michal

**Comment by aniruddha-a** [comment]
Sorry to have missed the issue, and thanks for the reference. Will close the issue.
