### ISSUE TITLE
Segfault when augmenting and deviating in the same yang file

### ISSUE THREAD

**Issue by samuel-gauthier** [CESNET/libyang#497]
I created a module that inherits from openconfig yangs, but I need to change some of the attributes. I am making use of yang deviations to achieve this. What I am doing seems to work with pyang (https://github.com/mbj4668/pyang) but not with libyang. I have created 3 test modules to demonstrate the problem I see. I used libyang 0.14.80 for this test.

augment.yang
```yang
module augment {
  namespace "uri:augment";
  prefix augment;

  import main { prefix main;}
  import container { prefix container;}

  augment "/main:config" {
    container augment {
      uses container:top;
    }
  }
  deviation /main:config/augment:augment/augment:test {
    deviate replace {
      type uint16;
    }
  }

}
```

main.yang
```yang
module main {
  namespace "uri:main";
  prefix main;

  container config {
  }
}
```

container.yang
```yang
module container {
  namespace "uri:container";
  prefix container;

  grouping top {
    leaf test {
      type string;
    }
    leaf test2 {
      type string;
    }
  }
```

```
$ pyang augment.yang -f tree
module: augment
  augment /main:config:
    +--rw augment
       +--rw test?    uint16
       +--rw test2?   string

$ yanglint
No saved history.
> add augment.yang
libyang[0]: Schema node not found. (path: /main:config/augment:augment)
libyang[0]: Invalid value "/main:config/augment:augment/augment:test" of "deviation".
libyang[0]: Module "augment" parsing failed.
libyang[0]: Internal error (/opt/dev/libyang/src/tree_schema.c:4252).
Segmentation fault (core dumped)
$ yanglint -v
yanglint 0.14.80
```

Apparently, libyang refuses on purpose to deviate and augment in the same module. I came up with the attached patch, although I don't know the code well enough to be sure whether it is correct or not.
Unit tests are passed on top of libyang 0.14.80.

[0001-support-deviations-after-augments.txt](https://github.com/CESNET/libyang/files/1972523/0001-support-deviations-after-augments.txt)

Note that deviating the same node from another yang file (another module) works.

**Comment by michalvasko** [comment]
Hi,
I have made some changes and now it should work much better meaning no crashes. However, the main problem remains, you are augmenting what are technically your nodes (this specific message is not printed only because deviations are resolved before augments). It is true that this restriction we impose ourselves just so that we could simplify the code and avoid certain corner cases. We thought it reasonable and supporting it to be useless. Your use-case seems acceptable but is there any reason why you have decided to use a foreign grouping and then deviating it? The same result is achieved by simply writing the grouping yourself, exactly as you want it. You get no compliance by using some standardized grouping, the nodes in `uses` belong to the namespace (model) of the `uses` itself.

Regards,
Michal

**Comment by samuel-gauthier** [comment]
Hi,

Thanks for the crash fix.

We re-use openconfig models on our side, because they are well
made, and used by other people.

Though, we could not use the model as it. We had to make a couple
of changes, to move parts of the model into our existing yang
tree (hence the augments). And we have to deviate what we import
because there are things we don't support.

You're right, we could copy paste the content, but it seemed
better to augment / deviate, to follow new versions of the source
model, and to see how much we deviate from the model.

You're also right that we don't get compliance, but at least we
are close, which is still better than nothing.

Regards,
Samuel

**Comment by michalvasko** [comment]
Hi Samuel,
we will not support deviating your own module because there is really no reason to. Using some standardized models is always preferable and normally, you use deviations to mark features you do not support. However, in this case there is no point in doing so because the nodes from the grouping become **nodes from your model** once they are used in `uses`. If you define the modified grouping yourself, you **will not lose any compliance** whatsoever. Once the model is loaded it will be exactly the same as what you have now.

Regards,
Michal
