### ISSUE TITLE
Trouble using Libyang schema (lys_node) without the Libyang datatree (lyd_node)

### ISSUE THREAD

**Issue by jeroen-dhollander** [CESNET/libyang#677]
Hey all,

In our product we're using the Libyang schema to parse our YANG files, but we've implemented our own data storage.

This means we write our own code to do things like syntax validation, pre-commit validation, leafref/must evaluation, pattern matching, and the like.

While working on this we've encountered a few pieces of information that are required for this but that are not exposed through the public Libyang API,
and we wanted to see if you were open to making these pieces public.

If you agree with this we can obviously provide push requests for this.

So far we've encountered problems in 3 areas:

1) Range information is not public

Range information is stored as instances of `lys_restr`, but all that contains is the range string that was entered in the YANG.
To actually parse and process this range, we really would like access to the `len_ran_intv` struct (which is populated by `resolve_len_ran_interval` in the private header `resolve.h`).

2) Pattern information is not public

Similarly, pattern information is only exposed as strings in the same `lys_restr` structures.
To parse patterns we would like to use the `pcre` structure (which is populated by `lyp_check_pattern` in the private header `parser.h`).

This is further inconvenienced by the fact that `parser.h` includes `tree_internal.h` which uses a variable called `new`, which means we can not include this header from our c++ code.

3) XPath information is not public

Finally, the XPath information used for leafrefs, `must` and `when` statements is again only exposed as strings.
To parse this we need to use the `lyxp_expr` structure, 
which is populated by first calling `lyxp_parse_expr` (in the private header `xpath.h`), 
followed by a call to `reparse_or_expr` (which is not exposed in any header but instead is a `static` method inside `xpath.c`).

So would it be possible to expose these pieces of information through some public APIs?

Thanks in advance,

Jeroen

**Comment by rkrejci** [comment]
Hi,
in case of point 2, the pcre should be already stored in `ly_restr` if you compile libyang with enabled cache. It is filled by lyp_precompile_pattern(). But yes, we could make the mentioned functions public. However, consider our current work on (branch) libyang2. The part regarding the schemas should be done in January/February and it already contains everything you want in (something we call compiled) schema tree nodes - instead of strings, we store range as array of numeric boundaries, pattern contains the pcre structures and lyxp_expr is stored in must/when structures. Hard to say how much of work you already have, so how big problem for you is to move to libyang2. We are trying to keep the changed API as similar as possible, but to optimize data validation and to improve code maintainability, we have to do some changes mainly in schema tree. Obviously, we would also appreciate any feedback about changes in libyang2.

**Comment by jeroen-dhollander** [comment]
Hey Radek,

Thanks for the reply. 

I took a quick look at the Libyang 2 schema, and it looks like it indeed exposes everything we need.
So as far as I'm concerned that means I see no need to do anything for this on the current master branch.
For now we can use these methods by applying a small patch exposing those methods when checking out Libyang.

I will open a work-item to investigate moving to Libyang 2 in a few months.

Thanks again for all the work on the Libyang parser, it is an invaluable tool for us.
