### ISSUE TITLE
code review issue for hash_table.c

### ISSUE THREAD

**Issue by fanchanghu** [CESNET/libyang#768]
Hi,
It seems L718 should be in an 'else' branch below:

https://github.com/CESNET/libyang/blob/4dde2f60f06a3bb055cb7c248026396065b66f01/src/hash_table.c#L713-L718

**Comment by michalvasko** [comment]
Hi,
it took me a minute (some time since I wrote this), but I believe it is correct and I tried to clarify it with some comments. The point is that `rec->hits` are adjusted in the `if` only so that when the `rec` is copied on the next line, `hits` is correct (`crec->hits` is lost after the copy). But `rec` is always being removed, which is performed by invalidating it by setting `hits` to `-1`.

Regards,
Michal

**Comment by fanchanghu** [comment]
Oh, you are right, thanks for your explanation.
