### ISSUE TITLE
Assert failed in hash_table.c

### ISSUE THREAD

**Issue by fanchanghu** [CESNET/libyang#770]
Hi,
I have met an error like: 'lyht_find_collision: Assertion `(*last)->hits == 1' failed.' , but it is very very hard to reproduce this issue with libyang API (due to the pointer value is created randomly ), so I try to reproduce it just use the function in hash_table.h

here is the code:
```
int main()
{
    struct hash_table *ht;

    ht = lyht_new(1, sizeof(int), set_values_equal_cb, NULL, 1);
    if(!ht) {
        return -1;
    }

    int a[] = { 0, 1, 2, 3, 4, 5, 6, 7, 8 };

    lyht_insert(ht, &a[0], 0);

    lyht_insert(ht, &a[1], 1);
    lyht_insert(ht, &a[2], 2);
    lyht_insert(ht, &a[3], 3);

    lyht_insert(ht, &a[4], 0);

    lyht_remove(ht, &a[1], 1);
    lyht_remove(ht, &a[2], 2);
    lyht_remove(ht, &a[3], 3);

    lyht_insert(ht, &a[5], 5);
    lyht_insert(ht, &a[6], 6);
    lyht_insert(ht, &a[7], 7);

    lyht_insert(ht, &a[8], 0); // core dump here

    return 0;
}
```

By the way, I'm confused why there are two values(0 and -1) for unused position?  It is easier if we could use just one value(like 0) for that.

**Comment by michalvasko** [comment]
Hi,
thanks for the nice test, I have added it into *libyang* tests. You are using an older version so I had to change it a bit and the assert I got was different, but the problem reproduced and I think I have fixed it, my bad really.

To give a bit of context, the hash table implementation is described at `hash_table.h:69`. Based on that, if you open [wiki](https://en.wikipedia.org/wiki/Linear_probing#Deletion), you should understand why there are both `0` and `-1` for empty values (`-1` is technically an invalid value, not empty). Also a final note, we have used lazy deletion because it is easier to implement plus should even be a bit faster when there are not many deletions performed during hash table life-time, which should be *libyang* use-cases.

Regards,
Michal
