### ISSUE TITLE
Hang in lys_parse_path due to binary data in YANG file

### ISSUE THREAD

**Issue by jvijtiuk** [CESNET/libyang#771]
Hi,

the following file causes a hang. I've let yanglint run for about 20 minutes, so I think it is safe to assume that this is really a hang, since the data is not valid YANG in any way.

```
<95><95><95><95>@<95>^B^@<95><95><95><95><95><9D><95>^A
```

Here is the xxd output of the file, since I'm not sure if github will display it properly:

```
user@pc:~/libyang/build$ xxd ~/hang.yang 
00000000: 9595 9595 4095 0200 9595 9595 959d 9501  ....@...........
```

Regards,
Juraj

**Comment by michalvasko** [comment]
Hi Juraj,
you are right, it seems more input is expected than is available for some reason. However, all of this is outside *libyang* code, the problem seems to be in some auto-generated code so I am unable to fix it.

But if you are keeping these files somewhere (or can easily generate them again), we could try it in the new *libyang* once its out. We wrote YANG parser from scratch, so we should be able to fix any problem there.

Regards,
Michal

**Comment by jvijtiuk** [comment]
Well, most of the files that caused issues so far have been reported as issues here on GitHub.

I have some other files locally that crash the current version of the parser that I still have to report, since I am still cleaning them up. I will open new issues for those files, so the new parser can be tested with those too. Setting the AFL fuzzer up with the new parser shouldn't be much work either, especially if the API stays the same.

Regards,
Juraj

**Comment by jvijtiuk** [comment]
I have just now noticed that the new libyang is available in the libyang2 branch. The libyang2 parser doesn't hang on this file and reports an error.
