### ISSUE TITLE
Segmentation fault in lys_parse_path due to unprintable characters in bit value on libyang2 branch

### ISSUE THREAD

**Issue by jvijtiuk** [CESNET/libyang#780]
Hi,

the following file crashes yanglint built on the libyang2 branch. The issue seems to be caused by the non printable characters on line 9. Since the characters are non printable, I've attached a zip with the file below.

[crash2.zip](https://github.com/CESNET/libyang/files/3172397/crash2.zip)

Regards,
Juraj

**Comment by rkrejci** [comment]
I'm not fully satisfied with the solution with the error message `unexpected end-of-input`. But since libyang  parses all the data as a NULL-terminated strings, it is not able to detect that the NULL-byte in the UTF character is not the end of string but part of some not-allowed UTF character. To be able to detect this corner case error correctly, we would have to change API of the parser and it would actually just introduce some other troubles. So, at the end, I believe that this fix is enough.
