### ISSUE TITLE
libyang 1.0 needs to use different extension directory based on ABI version

### ISSUE THREAD

**Issue by eqvinox** [CESNET/libyang#794]
since libyang 1.0 is a new SO ABI version, and extension modules don't have a SOVERSION, a separate directory needs to be used for libyang1 extensions so they can be kept separate from libyang0 extensions.

the "simple" fix would be to just change `PLUGINS_DIR` to use `.../libyang1` instead of `.../libyang`.

However, maybe the directory should also be added to the `pkg-config` file as a separate variable so it can be retrieved with `pkg-config --variable`.

**Comment by michalvasko** [comment]
Hi,
there are library versions stored in each plugin so there should never be an incompatible plugin loaded. Having said that, separating *libyang* versions 0 and 1 may be a good idea, we just have different priorities, but we would accept a pull request. However, the whole project would have to be renamed to libyang1 (so that PC files do not collide, for one, and the PLUGINS_DIR can also be added to it) and that would also change the include file to `libyang1/libyang.h`, if both versions are to be allowed to be installed on the same machine. I, personally, think this is redundant to be allowed.

Regards,
Michal
