### ISSUE TITLE
performance issue in `lyd_diff` with large configs

### ISSUE THREAD

**Issue by eqvinox** [CESNET/libyang#834]
cf. https://github.com/FRRouting/frr/issues/4788

```
# Children      Self  Command  Shared Object        Symbol                                        
# ........  ........  .......  ...................  ..............................................
#
    80.57%     0.00%  ripd     [unknown]            [.] 0x00007f36c7851ca0
    80.24%     0.00%  ripd     [unknown]            [.] 0x000055ca04bd1730
    77.79%    77.69%  ripd     libyang.so.0.16.105  [.] lyd_diff
    77.42%     0.00%  ripd     [unknown]            [.] 0x0000000000000080
     6.84%     0.00%  ripd     [unknown]            [.] 0000000000000000
     2.34%     0.00%  ripd     libyang.so.0.16.105  [.] 0x00007f36c7617078
     2.34%     2.34%  ripd     libyang.so.0.16.105  [.] 0x0000000000078084
     2.30%     0.00%  ripd     libyang.so.0.16.105  [.] 0x00007f36c75b0470
     1.10%     0.00%  ripd     [unknown]            [.] 0x000055ca04c49de0
     1.08%     1.02%  ripd     libyang.so.0.16.105  [.] lydict_remove
     0.96%     0.92%  ripd     libc-2.28.so         [.] __strlen_avx2
     0.93%     0.00%  ripd     [unknown]            [.] 0x000055ca04c51430
     0.87%     0.83%  ripd     libpthread-2.28.so   [.] __pthread_mutex_lock
     0.74%     0.71%  ripd     libpthread-2.28.so   [.] __pthread_mutex_unlock_usercnt
     0.69%     0.00%  ripd     [unknown]            [.] 0x00000034322f302e
     0.67%     0.61%  ripd     libc-2.28.so         [.] __strncmp_avx2
     0.63%     0.61%  ripd     libc-2.28.so         [.] _int_malloc
     0.59%     0.00%  ripd     libyang.so.0.16.105  [.] 0x00007f36c75b0400
     0.59%     0.59%  ripd     libyang.so.0.16.105  [.] 0x00000000000113fd
```

This is with 2000 items being incrementally added to the config.  It seems that `lyd_diff` needs some architectural change to not scale O(n²) (or is it even O(n³)?) with config size.

**Comment by michalvasko** [comment]
Hi,
what exactly is the use-case when `lyd_diff()` is used? If `sr_commit()` of some changes, then I would suggest to use the new *sysrepo* from `devel`. Commit (which was renamed to `sr_apply_changes()`) was greatly simplified and should be considerably faster and require less memory. Also, `lyd_diff()` is not even called anymore.

Regards,
Michal

**Comment by rwestphal** [comment]
Hey @michalvasko, I hope you're doing well :)

Our use case is that we're using libyang directly in FRR, with Sysrepo integration being a separate plugin.

We use `lyd_node` structures to hold the configuration of our routing daemons. Configuration changes are done in a candidate configuration, and then committed to the running configuration. In the commit process, FRR uses `lyd_diff()` to compare the candidate to the running configuration. The output of `lyd_diff()` is used to know which FRR configuration callbacks need to be called to commit the candidate configuration. Similar to Sysrepo, FRR transactions are pseudo-atomic (all or nothing) and follow a two-phase commit protocol (validate/prepare + abort/apply). You can find more details [here](https://github.com/opensourcerouting/frr/wiki/Architecture).

The problem @eqvinox reported is that `lyd_diff()` is not scaling very well when comparing large data trees. I think a lot of work was done recently to optimize `lyd_new_path()`, `lyd_dup()`, `lyd_free()` and other functions thanks to the new caching mechanism (which uses lots of hash tables). But maybe `lyd_diff()` wasn't optimized in the same way since it's not a hot function for other users of the library. Would that be a fair assessment?

In FRR, when the transactional-CLI mode is not used, every configuration command translates to a full configuration transaction. So if we have 2000 commands in the startup configuration, this means 2000 transactions and 2000 times that `lyd_diff()` is called. Hence our concern with the performance of this function.

**Comment by michalvasko** [comment]
Hi Renato,
good to hear from you again :)

This is exactly what *sysrepo* does, as well, but I guess you are duplicating the functionality for a reason. So, I believe some optimizations were performed for `lyd_diff()`, as well but there may be space for more. This function, among others, will be rewritten in the new *libyang* so we will not be doing any more optimizations on the existing code. If it is important to you, you can take a look yourself, sorry. But be aware that generating a diff simply is an expensive operation so you may want to try to limit the times the function is called instead.

Regards,
Michal

**Comment by rkrejci** [comment]
Regarding the new implementation in libyang2 - I'm thinking about changing the resulting structures to make it compatible/usebale for [YANG Patch](https://tools.ietf.org/html/rfc8072). New `lyd_diff()` is covered by #863
