### ISSUE TITLE
A question about leafref.

### ISSUE THREAD

**Issue by fanchanghu** [CESNET/libyang#84]
Hi,
I read sysrepo code today, and I found that it had supported leafref now by using the type and value of its target node. You can find this feature in the function `sr_libyang_leaf_get_type` and `sr_libyang_leaf_copy_value` in sysrepo.

but when we use `lyd_parse_xml(np2srv.ly_ctx, &config_xml, LYD_OPT_EDIT);` in netopeer for edit-config, the type for leafref node is not `LY_TYPE_LEAFREF` but its target node's type with `LY_TYPE_LEAFREF_UNRES`, and its value is null( its `value_str` is OK, but for many other types, like int, bits, using `value_str` is not convenient). So I think we need set the value for leafref node with its target node's type, then we can convert this value to `sr_val_t` for sysrepo conveniently.

**Comment by michalvasko** [comment]
Hi,
the logic of `struct lyd_node_leaf_list` attribute values is a bit different albeit a bit confusing. If `value_type | LY_TYPE_LEAFREF_UNRES`, then the actual `LY_DATA_TYPE` stored in `value_type` is the type of the leafref target, because otherwise you would not be able to learn the type (`value.leafref` is NULL, it is left unresolved as learnt from the flag`). I will let sysrepo guys know about this.

Regards,
Michal
