### ISSUE TITLE
A question about default, mandatory on valid data tree?

### ISSUE THREAD

**Issue by foxge** [CESNET/libyang#852]
Hi
I met the following issue, see rfc7950.
https://tools.ietf.org/html/rfc7950#section-8.1

```
   o  If the constraint is defined on configuration data, it MUST be
      true in a valid configuration data tree.

   o  If the constraint is defined on state data, it MUST be true in a
      valid state data tree.
```

but the mandatory attribute is ignored in config data tree in my application, what happened?
It is that I can not call lyd_validate in state data tree ?

model looks like the following:
```
container A {
   config false;
   leaf a1 {
     type string;
     mandatory true;
   }
}
```
input xml message looks like:
```
<get>
   <filter>
     <A xmlns="urn:A"/>
   </filter>
</get>
```
I found the <get> rpc is passed in my application.

**Comment by fredgan** [comment]
I get your point, but I am not sure your yang model.

I find the document in https://tools.ietf.org/html/rfc7950#section-7.6.5.
Maybe it can help something.

```
The "mandatory" statement, which is optional, takes as an argument
   the string "true" or "false" and puts a constraint on valid data.  If
   not specified, the default is "false".

   If "mandatory" is "true", the behavior of the constraint depends on
   the type of the leaf's closest ancestor node in the schema tree that
   is not a non-presence container (see Section 7.5.1):

   o  If no such ancestor exists in the schema tree, the leaf MUST
      exist.

   o  Otherwise, if this ancestor is a case node, the leaf MUST exist if
      any node from the case exists in the data tree.

   o  Otherwise, the leaf MUST exist if the ancestor node exists in the
      data tree.

   This constraint is enforced according to the rules in Section 8.
```

**Comment by rkrejci** [comment]
@foxge, your question (what you are actually doing) is not very clear. The "input xml" is supposed to be probably NETCONF's \<get\> operation (despite it is incomplete RPC and namespace is missing). What data do you actually validate and how?

**Comment by foxge** [comment]
for example.
```
module demo {
  namespace "urn:demo";
   container A {
     description "this is a state tree.";
     leaf a1 {
       type string;
       mandatory true;
     }
   }
}
```
the xml message from client is 
```
<rpc>
   <get>
     <A xmlns="urn:demo"/>
   </get>
</rpc>
```
in the above case, If I want the constraint of a1 mandatory attribute is forced on the request data tree, must I call lyd_validate on it explicitly ?

**Comment by fredgan** [comment]
On my understanding of YANG, your message from client is an rpc operation. But your YANG model demo has no rpc statments matching for it.

**Comment by foxge** [comment]
Focus on the "mandatory true;" statement in leaf a1, how do I let it be affect on the request data tree like the above <get> rpc.  Need I explicitly call lyd_validate on the data tree resulted from get rpc?

**Comment by fredgan** [comment]
I think the answer is "YES, you need".

lyd_validate is used to check the data and the YANG model.

In fact, you can use yanglint tool to check it in another way. yanglint also use the function  lyd_validate.

```
yanglint -t rpc -f xml ./demo.yang ./demoinput.xml
```

**Comment by foxge** [comment]
Okay, I guess so.
Thank you .

**Comment by rkrejci** [comment]
@foxge, I'm still missing namespaces in your RPC message, if the \<get\> is standard NETCONF get RPC, then its content (`<A xmlns="urn:demo"/>`) is invalid - see [RFC 6241](https://tools.ietf.org/html/rfc6241#appendix-C). 

If it is supposed to be a filter, you cannot validate (speaking about various constraints) filter according to the schema it is supposed to filter. The subtree filters in NETCONF's get or get-config have a [specific rules](https://tools.ietf.org/html/rfc6241#section-6). If you want to validate input data of any RPC, the restrictions must be present in the definition of the RPC itself (that is what the proposed yanglint command will do).

If you are going to validate result of get operation, you still cannot force the mandatory restriction defined in data actually returned as anyxml. Because of the subtree filter, I can get just subset of the data actually present in the server's datastore, so the mandatory nodes can be filtered out.

**Comment by foxge** [comment]
Yes，you are right.
