### ISSUE TITLE
Validation Performance Enhancements 

### ISSUE THREAD

**Issue by GalaxyGorilla** [CESNET/libyang#894]
Hey,

we are currently investigating performance issues on FRR where libyang is used for configuration processing. We noticed an oddity on the validation, which appears to be rather slow. There is the flag [LYD_VAL_OK](https://netopeer.liberouter.org/doc/libyang/master/group__validityflags.html#ga1000ce3f941e7713a26ba32890c6c4d6) which is to our understanding used to optimize the validation handling (it shows if a node is already validated?). However, diving into the code we have seen that it is only used at places which have less in common with the validation process.

In [this commit](https://github.com/CESNET/libyang/commit/e3886b) we can see that it was used before. What is the context of those changes and what is the purpose behind that flag? Do you see any other "low hanging" possibilities which we should approach for performance enhancements regarding the validation? Our focus is primarily on rather flat trees where you e.g. have a _lot_ of leafs under a single node.

**Comment by michalvasko** [comment]
Hi,
that commit tried to put some order in those validation flags. I seem to remember I was going to fix some bug (that something was not being validated when it should have been because of these flags being set incorrectly) but when I learned what a mess they are, I significantly refactored them.

The intention was to set the corresponding flag when it is discovered it needs to be validated (for example, when a leafref was parsed, set the `LYD_VAL_LEAFREF` flag). Then, when this validation happens (optionally, is skipped because of `LYD_OPT_TRUSTED` option), unset this flag. You understanding of `LYD_VAL_OK` is correct but these changes caused the flag not be used directly. Once a node is fully validated, all these flags should be unset and 0 (`LYD_VAL_OK`) left.

It is possible there are places where this is not the case (specific validation is not skipped even though the flag is not set) so you can take a look keeping in mind what I wrote. Also, be careful, there are some validation tasks that must  **always** be performed, such as `when` evaluation. This task is not cached using any flag on purpose because to keep track of all the cases in which it actually needs to be performed is extremely demanding and just not worth it.

Regards,
Michal

**Comment by GalaxyGorilla** [comment]
Just to clarify: such flags are _only_ used within single runs of validations right? So what I am actually looking for is some state to keep between e.g. two runs of validations. This way, if you have let's say such a flat tree with a root and a lot of leafs (leaf-list) as children, when you add one more leaf then the whole tree doesn't need to be validated (only the single leaf). Is such a naive optimization actually feasible?

**Comment by michalvasko** [comment]
Hi,
no, those flags should be preserved and the particular validation task is skipped the next time the whole validation runs. Tree operations should correctly set these flags back when they perform a change that may cause the particular property not to be valid anymore. That is the idea.

Regards,
Michal

**Comment by GalaxyGorilla** [comment]
That actually sounds very good. So a simple potential test would be to take a big tree and and validate that tree multiple times without changing it. The validations after the first one should cause close to zero overhead right?

**Comment by michalvasko** [comment]
Hi,
in theory, yes. But it depends on the data tree because many tasks may be required to be performed for every validation (what I was talking about before).

So you can try to do some measurements but I think I know already what you will find out. YANG is complex, much more that it seems, and probably those most demanding tasks are those that need to be executed every time. Such as checking the whole tree for default values. Because how are you supposed to know that by that last node you added into the tree you have not changed the result of a when expression of a default node at some completely different place in the tree and it needs to be created now? Again, you could, in theory, cover this situation by some complicated system of flags or whatever so that you do not have to check the whole data tree.

The problem is that you will never be able to cover all the cases because of YANG complexity, so it would result in an endless loop of fixing newly discovered non-working cases. Also, all these optimizations would be targeted on a specific use-case (such as validation) and would cause inefficiencies for other operations (such as modifying the data tree and checking all the cached flags/whatever). The result would be that tasks would take the same amount of time, if not more, compared to the state without the optimizations, overall. Not even mentioning the final code complexity.

These are our experiences from the whole *libyang* development. The current code is probably a mix of the general idea of how efficient validation can be and then facing the harsh reality of it being impossible, hence my uncertainty about validation details. Just one of the reasons we are working on the new *libyang*, insights such as this allow for a much better and simpler internal design. That will, in turn, allow optimizations that can actually imrpove the overall performance and can still be reasonably maintainable.

Regards,
Michal

**Comment by GalaxyGorilla** [comment]
So i did a quick test, I simply duplicated the validation calls so the second validation happens with the very same data tree. The time needed to perform my test tasks got up by 50%. So this is better than 100% ;) but there seems to be some overhead involved :-/. Any hints what could be the issue?

About yang ... I have not too much experience with it but enough to get a feeling for it. It is quite a beast. I completely understand that one needs to keep a balance here between code complexity (which will also affect runtime) and the level of detail in which certain cases are covered. I personally think that discussions like this one are quite important and valuable because they give an impression what it means to make changes here :).

Anyway, I will try to do some more testing for now, maybe an opportunity for improvements opens up.

**Comment by michalvasko** [comment]
Like I wrote before, I think checking default values takes a significant amount of time (`lyd_wd_add()`) but maybe some other tasks as well. Try running the second validation with `callgrind` or `perf` and the results should clearly point to the most demanding tasks.

Regards,
Michal

**Comment by GalaxyGorilla** [comment]
Well, I did :). For me this is really not obvious ... it seems the mandatory subtree stuff really takes the time:

<img width="628" alt="grafik" src="https://user-images.githubusercontent.com/5798605/66640828-f0cfd280-ec19-11e9-9bc6-f59dbb3c7553.png">

**Comment by michalvasko** [comment]
Could you attach the `callgrind` output file please? The call graph should provide a bit more information.

Regards,
Michal

**Comment by rkrejci** [comment]
Hi, just a side note illustrating problems with the flags - there is an issue  CESNET/Netopeer2#472 which seems to be caused by `LYD_VAL_LEAFREF` flag, because the leafref was invalidated even in the case the leafref itself even its original target value did not changed, but actually the target of the leafref changed due to the predicate in the leafref's path.

The proposed fix right now is to remove/do not use the `LYD_VAL_LEAFREF` flag since there are cases when the leafref become invalid as a side effect of a change _anywhere_. In libyang2, it was not planned to use this flag and the value is supposed to be validated always.

**Comment by GalaxyGorilla** [comment]
Here are three different outputs where I add 1000, 2000 and 4000 routes (e.g. leafs) to FRRs ripd:

[ripd.zip](https://github.com/CESNET/libyang/files/3717168/ripd.zip)

Many thanks for having a look :)

**Comment by michalvasko** [comment]
Hi,
so looking at `lyd_validate()` in those files, I think `lyd_check_mandatory_tree()` is the only function that is probably not respecting `LYD_VAL_MAND` flags and so performs some redundant work. If you decide to optimize this be aware that there may also be problems with this flag not being correctly set when it should be and it just did not manifest because the flag was ignored.

More importantly, based on these graphs, validation takes 9% of all the instructions, which does not really seem to be a number high enough to focus the optimizations on. What I would focus on instead are `lytype_store()` and `lytype_find()` which take 46% of all the instructions. In particular, you can take a look at `ipv4_prefix_store_clb()` because when I wrote I really did not care much for efficiency because I did not think it may ever matter. So, it may not be difficult to optimize it. As for the user types in general, it is probably a task better suited for us, so we will think about what can be done there and let you know.

Regards,
Michal

**Comment by GalaxyGorilla** [comment]
Hey, the `lytype_*` funs you mention are actually less of a problem, they are related to usage pattern fixes which we are currently investigating and testing. So far it looks fine.

The validation is one of the next big things we run into, that's why I want to improve it. I'll have a look into `lyd_check_mandatory_tree` next week.

**Comment by GalaxyGorilla** [comment]
Hey again, just a little update:

This is the code which is responsible for the 'slow' performance of the validation in our case:

https://github.com/CESNET/libyang/blob/master/src/tree_data.c#L740-L754

For every route that I add in FRR's ripd I get additional 12 calls into the `LYS_LIST` case.

**Comment by GalaxyGorilla** [comment]
So the only real chance for optimization I can see so far is:

https://github.com/CESNET/libyang/blob/master/src/tree_data.c#L527

This is called quite often and due to the loop

    LY_TREE_FOR(data, iter) {
        if (iter->schema == schema) {
            ly_set_add(set, (void*)iter, LY_SET_OPT_USEASLIST);
        }
    }

with `ly_set_add` there are a lot of memory allocations. Maybe it is possible to get the data siblings in another way without the copying?

**Comment by michalvasko** [comment]
I assume you mean calling `lyd_get_node_siblings()` as part of validating `mandatory`, right? Like I said before, I believe all those calls can be skipped if `LYD_VAL_MAND` flag is honored.

My idea is that the whole tree needs to be recursively searched for nodes with `LYD_VAL_MAND` and then do all the work in `lyd_check_mandatory_subtree()` only for nodes that have this flag. But whether this is possible I cannot say without thorough analysis of this flag, validation, and all the checks that are performed. I should be able to take a look in the next days but you can try that, too. Having the pull request ready and passing tests would make it much easier for me.

Regards,
Michal

**Comment by GalaxyGorilla** [comment]
Meh, it seems I messed with my setup too much. So I checked again and `lyd_check_mandatory_tree` as well as `lyd_check_mandatory_subtree` are used a constant number of times for a single validation (3 and 94 times) independent of the number of routes I put in the config. So I think that settles that we cannot optimize this using those flags.

**Comment by michalvasko** [comment]
Well, I still think it can be optimized except it could reduce the time needed only by a constant based on what you said. If you think it is not worth it then fine, we are fine either way.

Regards,
Michal
