### ISSUE TITLE
unable to refine a case statement

### ISSUE THREAD

**Issue by kwatsen** [CESNET/libyang#918]
Using a `grouping` that contains a `choice` and trying to `refine` an `if-feature` statement into it fails to validate with a message like:

```
err : Invalid value "<snip2>" of "refine". (<snip2/>)
err : Refine substatements not applicable to the target-node. (<snip2, again)
```
Modifying the refine-path to target an arbitrary `container` node inside the `case` statement validates fine.

Note that [7.13.2](https://tools.ietf.org/html/rfc7950#section-7.13.2) says:
```
   o  A leaf, leaf-list, list, container, choice, case, anydata, or
      anyxml node may get additional "if-feature" expressions.
```

So, refining a `case` statement should be okay, right?

**Comment by fredgan** [comment]
@kwatsen Thank you for your report. Yes, it is as what you said.

@rkrejci Hi Radek, I find that this issue is caused by that the parse part is the implement of YANG1.0(RFC6020), But after Aug 2016, YANG1.1 (RFC7950) is published. The `refine` ability is strenghened. `if-feature` function is added to `refine` in YANG1.1 and some other functions.

**Comment by kwatsen** [comment]
Fix confirmed.  Thanks!
